refactor: 피드백 관련 코드 리팩토링
woowacourse-teams/2022-levellog pull request #139
Opened 2022-07-27 07:41 UTC by 2yujeong

## 구현 기능
- [x] DTO 파일명 변경
- [x] DTO에 생성 로직 몰아넣기
- [x] 서비스 @Transactional 리팩토링
- [x] 매개변수 순서 정리
- [x] Id 변수명 구체화
- [x] 검증 로직에 쓰이는 Repository 메소드 find -> exists 변경
- [x] 도메인 검증 로직 추가(피드백 항목들 길이 검증)
- [x] 피드백 작성자만 수정 / 삭제할 수 있도록 update / delete 방어 로직 추가
- [x] Domain, Repository 테스트

## 논의하고 싶은 내용
- 예외 메시지 구체화(dev용 메시지, 클라이언트 메시지)는 상위 예외 클래스 리팩 후 추가로 더 수정하도록 미뤄뒀습니다.

Close #131

2022-07-27 13:15 UTC, nailseong requested changes
고생하셨읍니다. 컨벤션 관련 피드백 위주로 남겼읍니다. 확인 후 반영 부탁합니다.

2022-07-27 13:15 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/CreateFeedbackDto.java
> +public class CreateFeedbackDto {
### 제안
```suggestion
public class FeedbackCreationDto {
```

<img width="421" alt="image" src="https://user-images.githubusercontent.com/68512686/181246715-c61b6e31-f020-4bfa-a3e2-ce67b7aeba07.png">

2022-07-27 13:15 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackContentDto.java
>  public class FeedbackContentDto {
```suggestion
@Getter
@EqualsAndHashCode
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class FeedbackContentDto {
```
정적 팩토리 메서드를 도입했으니까 생성자는 PRIVATE으로 변경해주세요

2022-07-27 13:15 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackDto.java
>  @AllArgsConstructor
```suggestion
@EqualsAndHashCode
@AllArgsConstructor(access = AccessLevel.PRIVATE)
```
ditto

2022-07-27 13:15 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbacksDto.java
>  @AllArgsConstructor
```suggestion
@EqualsAndHashCode
@AllArgsConstructor(access = AccessLevel.PRIVATE)
```
ditto

2022-07-27 13:15 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
> +                    .willThrow(new MemberNotFoundException("존재하지 않는 멤버"));
```suggestion
            final String token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiaWF0IjoxNjU4ODkyNDI4LCJleHAiOjE2NTg5Mjg0Mjh9.G3l0GRTBXZjqYSBRggI4h56DLrBhO1cgsI0idgmeyMQ";
            given(jwtTokenProvider.getPayload(anyString())).willReturn("1");
            given(jwtTokenProvider.validateToken(token)).willReturn(true);

            final Long levellogId = 1L;

            given(feedbackService.findAll(levellogId))
                    .willThrow(new MemberNotFoundException("존재하지 않는 멤버"));
```

2022-07-27 13:15 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
> +                    .willThrow(new MemberNotFoundException("존재하지 않는 멤버"));
추가로 다른 mocking 코드에도 불필요한 `any`가 많이 보여요.

2022-07-27 13:15 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
> +                    .hasMessageContaining("피드백은 1000자 이하여야 합니다.");
```suggestion
           assertThatThrownBy(() -> feedbackContentDto.toEntity(roma, levellog))
                    .isInstanceOf(InvalidFieldException.class)
                    .hasMessageContaining("피드백은 1000자 이하여야 합니다.");
```

2022-07-27 13:15 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +        assertThat(feedbacks).hasSize(2).containsExactly(savedFeedback2, savedFeedback1);
```suggestion
        // then
        assertThat(feedbacks).hasSize(2)
            .containsExactly(savedFeedback2, savedFeedback1);
```

2022-07-27 13:15 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +        assertThat(feedbacks).hasSize(2).contains(savedFeedback1, savedFeedback2);
```suggestion
        // then
        assertThat(feedbacks).hasSize(2)
            .contains(savedFeedback1, savedFeedback2);
```

2022-07-27 13:15 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +                    message + " feeadbackId : " + feedback.getId() + ", memberId : " + member.getId());
```suggestion
                    message + " feedbackId : " + feedback.getId() + ", memberId : " + member.getId());
```

2022-07-27 13:15 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +        return feedbackRepository.save(feedback).getId();
```suggestion
        return feedbackRepository.save(feedback)
            .getId();
```

2022-07-27 16:19 UTC, kbsat requested changes, later dismissed
안녕하세요 이브 😊
피드백 도메인 리팩토링 하느라 고생많으셨습니다.
여러 곳에서 복붙의 흔적이 보이는데.. 👀  놓치신 부분에 대해 리뷰 남겨드립니다 😁
확인해보시고 반영부탁드립니다 👍

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +@Transactional(readOnly = true)
readOnly 잘 붙여주셨군요 💯

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
>      @Column(length = 1000)
```suggestion
    @Column(length = FEEDBACK_CONTENT_MAX_LENGTH)
```

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
>          this.study = study;
update 할 때도 validateFeedback을 걸어주었면 좋을 것 같아요. 😊

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
> +    boolean existsByLevellogIdAndFromId(Long levellogId, Long fromId);
👍

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
>          if (!feedback.isAssociatedWith(member)) {
메서드명이 `validateAuthor`이고 예외 메세지들도 보면 `"자신이 남긴 피드백만 삭제&수정할 수 있습니다."` 인데 실제 로직을 보면 피드백 작성자인지를 검사하는 것이 아니라 피드백 받은 사람도 통과하는 것으로 보여요.

피드백을 받은 사람도 삭제 수정 가능해보이네요!👀

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackDto.java
> +                feedback.getUpdatedAt());
현재 FeedbackDto는 받은 사람에 대한 정보를 담고있지 않아요. 회의 때 해리가 이야기한대로 수정해보면 어떨까요? 👀

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
> +    public static final int FEEDBACK_CONTENT_MAX_LENGTH = 1000;
```suggestion
    private static final int FEEDBACK_CONTENT_MAX_LENGTH = 1000;
```

2022-07-27 16:19 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
> +        }
피드백 항목이 많은데 어떤 피드백이 1000 자 이하인지도 알려주면 더 상세한 예외메세지가 될 것 같아요.

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
> +                .then().log().all();
updateFeedback에 대한 테스트 메서드인데 작성에 대한 요청을 수행하면서 문서까지 만들고 있네요😂 ( 몇군데 더 보이긴 하네요 )
`RestAssuredTemplate` 을 활용해서 한번 바꿔보아요 😊

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
> +                .getId();
요청을 한번 더 찌르는 것보다 Location Header의 값을 추출하는 것은 어떨까요?

```java
final String savedLocation = RestAssuredTemplate.post("/api/levellogs/" + rick_levellogId + "/feedbacks", romaToken,
                givenRequest)
        .getResponse()
        .extract()
        .header(HttpHeaders.LOCATION);
final long updateId = Long.parseLong(savedLocation.split("/")[5]);
```

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +@Import(JpaConfig.class)
`JpaConfig.class` 를 붙이는 이유가 무엇인지 알고있나요? 😎

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +        feedbackRepository.flush();
`flush`를 하는 이유는 무엇일까요?

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +}
```suggestion
}

```
마지막 줄은 꼭 개행해주세요 🫠

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
> +}
```suggestion
}

```
ditto

2022-07-27 16:19 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
> +    class updateNickname {
DisplayName은 "생성자는" 인데 updateNickname 이네요 😗

2022-07-28 02:55 UTC, SuyeonChoi submitted a review, later dismissed
이브 수고하셨습니다!👍👍
서비스에서 검증하는 부분을 도메인으로 변경하는 것을 고민해보면 좋을거 같아요!

2022-07-28 02:55 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
> +    class updateNickname {
생성자 테스트로 정정하고 도메인 로직인 `updateNickname`에 대한 테스트도 추가하면 좋을거 같아요😊

2022-07-28 02:55 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +        assertThat(isExist).isTrue();
존재하지 않는 경우 테스트도 추가하면 좋을거 같네요!

2022-07-28 02:55 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackContentDto.java
> +    public Feedback toEntity(final Member member, final Levellog levellog) {
```suggestion
    public Feedback toFeedback(final Member member, final Levellog levellog) {
```
이렇게 메서드명을 변경한다면 사용할 때 어떤 엔티티 객체가 리턴되는지 알기 쉽다고 생각해요. 이브의 취향대로 반영하셔도 될거 같아요.
`FeedbackContentDto.toFeedback(member, levellog);`

2022-07-28 02:55 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                       @RequestBody @Valid final CreateFeedbackDto request,
`CreateFeedbackDto`가 update에서도 사용되는군요
혹시 이브도 이에 대한 고민을 해보셨나요? 이브의 생각이 궁금합니당😋 https://github.com/woowacourse-teams/2022-levellog/pull/149#discussion_r931092375

2022-07-28 02:55 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +            throw new InvalidFeedbackException("같은 팀에 속한 멤버만 피드백을 작성할 수 있습니다.");
여기서도 더 많은 정보를 담는건 어떨까요?
```suggestion
            throw new InvalidFeedbackException("같은 팀에 속한 멤버만 피드백을 작성할 수 있습니다. memberId :" + memberId + " teamId : " + teamId);
```

2022-07-28 02:55 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +        validateSelfFeedback(member, levellog);
도메인에서 검증의 책임을 가질 수는 없을까요?
팀의 멤버인지 검증하는 로직은 Team이, 피드백 작성자인지 검증하는 로직은 Feedback이 책임을 갖는건 어떨까요? 👀
이 외에 다른 검증 로직도 고려해볼 수 있을거 같아요

2022-07-28 04:41 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackContentDto.java
>  public class FeedbackContentDto {
정적 팩토리 메소드는 엔티티에서 DTO로 변환할 때의 편리성을 위해 도입했어요!
from()만 남기고 AllArgs 생성자는 private으로 닫으면, 테스트 코드에서 Request 목적으로 DTO를 생성할 때 Feedback 도메인까지 생성해서 넣어줘야 해서 AllArgs 생성자는 public으로 열어놓는 게 좋을 거 같아요😀

2022-07-28 04:44 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/CreateFeedbackDto.java
> +public class CreateFeedbackDto {
https://github.com/woowacourse-teams/2022-levellog/pull/139#discussion_r931722075
해당 DTO가 update 요청에서도 쓰이기 때문에 페퍼의 코멘트를 참고하여 FeedbackWriteDto로 변경했습니다🙂

2022-07-28 05:14 UTC, OzRagwort reviewed
수고하셨습니다 이브

`FeedbackNotFoundException`에 사용하지 않는 메서드가 있는데 그것도 지워주시면 좋을 것 같아요!

제가 꼼꼼하지 못하게 짰던 코드 잘 수정해주셔서 감사합니다 😢 👍

2022-07-28 05:14 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +        final Levellog levellog = levellogRepository.save(new Levellog(toMember, team, "levellog"));
언젠가 리뷰어님에게 테스트는 메서드에 대한 명세 역할도 하기 때문에 이름 같은 경우도 테스트만을 위한 `fromMember1`, `fromMember2`보다는 `이브`, `알린`과 같은 식으로 만드는게 좋을 것 같다고 들었어요.  

문서화되는 것도 아니고 테스트는 돌아가니 꼭 고쳐야 하는건 아닐 수도 있지만 이브는 어떻게 생각하는지 궁금해요!

그리고 profile.img도 fromMember1, fromMember2, toMember가 모두 같은 것도 왜 같지? 원래 같은건가? 하고 모호하게 이해할 수도 있지 않을까 해요! (물론 여기서는 간단한 도메인이기 때문에 안그렇겠지만요 )
isHost도 모두가 host네요 😄

2022-07-28 05:14 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +}
[github에 업로드할 파일 끝에 개행을 추가해야하는 이유와 자동화 방법](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/) 😄

2022-07-28 05:14 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +    @DisplayName("findAllByLevellog 메서드는 입력된 레벨로그에 등록 모든 피드백을 조회한다.")
```suggestion
    @DisplayName("findAllByLevellog 메서드는 입력된 레벨로그에 등록된 모든 피드백을 조회한다.")
```

2022-07-28 05:14 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
> +            final String feedback = "feedback".repeat(126);
가능하다면 1000자 초과를 테스트하기위해 경계선 값으로 테스트하면 어떨까요? 

지금은 1008자일 때 에러가 발생하는 테스트인데 1001~1007자에서는 에러가 발생할지 안 발생할지 모호할 수 있을 것 같아요 😄

2022-07-28 05:14 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +            throw new FeedbackAlreadyExistException(levellogId);
레벨로그 Id를 주기보다는 그냥 이곳에서 메시지를 만들어서 주어도 좋을 것 같기도 해요. 다른 예외들도 다 그렇게 하고 있어서요 😄

2022-07-28 05:52 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +@Import(JpaConfig.class)
Auditing이요!!!!!!!!

2022-07-28 05:53 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +        feedbackRepository.flush();
제가 넣은 코드가 아니었는데,, 빼는 걸 깜빡했습니다,,, 흑흑

2022-07-28 07:39 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackTest.java
> +class FeedbackTest {
given, when, then 명시해주세요.

2022-07-28 08:22 UTC, nailseong approved these changes
고생하셨읍니다.

2022-07-28 08:29 UTC, OzRagwort approved these changes
수고하셨습니다 !

2022-07-28 08:39 UTC, merged

2022-07-28 09:27 UTC, OzRagwort commented
어우 많아