refactor: Auth 도메인 리팩토링
woowacourse-teams/2022-levellog pull request #147
Opened 2022-07-27 10:58 UTC by nailseong

## 구현 기능
- [x] DTO 클래스명 변경
- [x] 서비스에서 `@Transactional` 추가하기
- [x] 커스텀 예외에 대한 구체 메세지 작성
  - [x] 예외 로그에 많은 정보를 담되, 간단한 메세지로 표현
- [x] 인수테스트 예외케이스 추가
- [x] 서비스테스트 보강

## 논의하고 싶은 내용
- `@LoginMember` -> `@Authentic` & `@NoAuthentication` -> `@PublicAPI`
  - 어노테이션 이름 변경했는데 관련한 의견 or 더 좋은 이름 추천받아용

Close #132

2022-07-27 19:05 UTC, SuyeonChoi requested changes
릭 Auth 도메인 리팩토링하시느라 수고하셨습니다!
리뷰하면서 추가적인 예외사항이나 큰 이슈는 없는거 같네요. 역시 믿고 있었습니다👍👍

import 구문이 순서대로 정렬되도록 리포맷팅만 반영해주시면 바로 approve하겠습니다.
그 외의 생각은 릭이 확인하시고 원한다면 반영하면 될거 같아요. 
`@DirtiesContext` 옵션에 대해 궁금한 점이 있어서 코멘트 남겼는데 답변 기다리겠습니다,,🙏

저는 `@PublicAPI` 마음에 듭니다! 더 좋은 이름이 생각나면 추후에 코멘트 남길게요〰️

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/docs/asciidoc/auth.adoc
> +operation::auth/login/github-fail[]
adoc 예외 케이스 문서화 형식도 현재는 제각각이라 팀끼리 이야기해보는게 좋을거 같아요. 생각나서 여기서 적고 갑니다🐾

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/dto/TokenDto.java
> +public class TokenDto {
해당 클래스는 Github OAuth로부터 access token을 받기 위한 객체인데 `TokenDto`라는 클래스명이 전 많이 추상적으로 느껴지네요,, 깃허브로부터 발급되는 토큰인지, 저희 서비스에서 발급해주는 토큰인지 헷갈릴 수 있다고 생각합니다. 
이제 DTO에서 `Request`와 `Response` 키워드를 제한하고, 이미 `GithubAccessTokenDto`가 존재해서 이렇게 클래스명을 지을 수도 있다고 생각해요. 저도 코드를 작성할 때 불편함이 느껴져서 DTO 클래스 네이밍은 다시 한번 이야기 해봐도 좋을거 같습니다.

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/domain/OAuthClient.java
> +    String getAccessToken(String authorizationCode);
정확한 파라미터 네이밍👍

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
>      private final JwtTokenProvider jwtTokenProvider;
```suggestion
    private final OAuthClient oAuthClient;
    private final JwtTokenProvider jwtTokenProvider;
    private final MemberService memberService;
```

클래스에서 사용되는 순서대로 필드 순서를 리팩터링하면 가독성을 아주 살짝 높일 수 있다고 생각해요!

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
> +    private final String clientMessage;
클라이언트 메세지와 예외 로그를 위한 분리👍👍👍

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
> +import com.woowacourse.levellog.authentication.support.Authentic;
```suggestion
import com.woowacourse.levellog.authentication.support.Authentic;
import com.woowacourse.levellog.authentication.support.AuthorizationExtractor;
import com.woowacourse.levellog.authentication.support.JwtTokenProvider;
```
import 문 포맷팅 확인해주세요!

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
>              assertThat(tokenResponse.getId()).isNotNull();
```suggestion
            assertAll(
                () -> assertThat(Long.parseLong(payload)).isEqualTo(savedMemberId);
                () -> assertThat(tokenResponse.getProfileUrl()).isEqualTo("rick.org");
                () -> assertThat(tokenResponse.getId()).isNotNull();
            );  
```
하나의 테스트에서 여러개의 assert문을 사용하는 경우 assertAll()을 사용해보는건 어떨까요?

참고) [StackOverflow - assertAll vs multiple assertions in JUnit5](https://stackoverflow.com/questions/40796756/assertall-vs-multiple-assertions-in-junit5)

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
> +class OAuthServiceTest extends ServiceTest {
`OAuthControllerTest`에서 입력값에 대한 테스트를 하고 있지만 단위테스트의 관점에서 `OAuthServiceTest`에서도 예외를 테스트하는건 어떨까요?

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/OAuthControllerTest.java
> +    class login {
👀

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
> +    @Deprecated
🥲

2022-07-27 19:05 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)
classMode 옵션을 `AFTER_EACH_TEST_METHOD`로 변경한 이유가 무엇인가요? 
혹시라도 다른 곳에서 테스트 후 context를 재생성하지 않는 경우를 고려한다면 테스트마다 시작하기 이전에 context 재생성하는 것이 더 안전하다고 생각했습니다.
궁금해서 질문하고 갑니당🤓🤓

2022-07-28 01:27 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
>      @Override
return 전에 한 줄 개행 컨벤션 확인해주세요!

2022-07-28 01:27 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/authentication/support/Authentic.java
> +public @interface Authentic {
저는 Authentic 보다는 LoginMember가 더 직관적으로 다가오는데 이 어노테이션의 네이밍에 대해서 간단하게 얘기해 보는 것도 좋을 거 같아요👀

2022-07-28 01:27 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
>      @CrossOrigin
login 메소드에 이 어노테이션을 따로 붙여준 이유가 있을까요?

2022-07-28 01:41 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
> +class FeedbackServiceTest extends ServiceTest {
컨트롤러 테스트도 모든 컨트롤러의 모든 서비스를 상속받아 테스트하는데 이곳도 그렇게 하셨네요 혹시 어떤 이점을 노리신 건지 알 수 있을까요?

2022-07-28 01:41 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/application/OAuthServiceTest.java
> +            final LoginDto tokenResponse = oAuthService.login(
given when then 구분이 명확하지 않은 것 같아요.

개인적으로 when에서는 이 테스트에서 검증하고 싶은 코드만 작성하는 편이고 이코드에서는 로그인 부분 같아요.

혹시 릭만의 기준이 있다면 공유해주세요 !

2022-07-28 01:41 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)
classMode를 `AFTER_EACH_TEST_METHOD`로 바꾸면서 인수 테스트가 끝나고 데이터를 모두 지워 테스트 격리를 하는 방식으로 이해했습니다. 

테스트한 데이터가 남은 상태로 다른 테스트가 실행되면 제대로된 테스트가 되지 않을 수도 있기 때문인 것 같아요. 그렇다면 classMode가 문제가 아니라 테스트 격리가 제대로 되지 않은게 문제가 아닐까? 생각되기도 합니다.

그렇다면 반대로 다른 테스트에서 데이터가 남는 상태로 인수테스트가 실행되면 의도하지 않은 데이터가 남아있기 때문에 문제가 되지 않을까요? 

인수 테스트만을 본다면 데이터를 다 초기화하고 실행하는게 더 좋아보여요. 

데이터가 남아서 문제가 된 테스트에서 데이터를 지우고 테스트를 실행하는 방식을 적용해보면 어떨까요?

2022-07-28 02:07 UTC, kbsat approved these changes
릭 고생하셨습니다. 간단한 리뷰 남겨놨으니 확인해보세요 😊

2022-07-28 02:07 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/authentication/dto/TokenDto.java
> +public class TokenDto {
동의합니다

2022-07-28 02:07 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
>      @CrossOrigin
`@CrossOrigin`은 삭제해도 좋을 것 같네요 ^>^

2022-07-28 02:07 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
> +    }
`clientMessage`를 사용하기로 하면 이 메서드는 지워도 될 것 같아요. 
해당 메서드가 남아있으면 잘못 사용해서 예외 메세지가 null인 응답이 클라이언트에게 날라갈 수도 있을 것 같네요 😇

2022-07-28 02:07 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
> +    protected LevellogException(final String message, final HttpStatus httpStatus, final String clientMessage) {
개인적으로 message를 한 곳에 모는 것을 선호합니다.
```suggestion
    protected LevellogException(final HttpStatus httpStatus, final String message, final String clientMessage) {
```

2022-07-28 02:07 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
> +    protected OAuthService oAuthService;
거슬렸는데 잘 바꿔주셨군요 👍
해당 서비스는 위에 모아두는 것도 좋을 것 같네요

2022-07-28 02:07 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/OAuthControllerTest.java
> +        void login_nullAndEmptyCode_exceptionThrown(final String code) throws Exception {
```suggestion
        void nullAndEmptyCode_exceptionThrown(final String code) throws Exception {
```
는 어떠신가요? 메서드 명에 대한 정보는 클래스에서 충분히 표현될 것 같아요 😁

2022-07-28 02:07 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)
DirtiesContext에서 격리가 제대로 되지 않아서 이 메서드를 `AFTER_EACH_TEST_METHOD`로 바꿔 준 것 같아요. 
- 인수테스트 중 마지막에 실행한 테스트의 마지막 데이터가 지워지지 않는 문제

`@OzRagwort` 나머지 테스트에서는 Transactional로 격리되어있는 것을 확인 했는데 혹시 다른 테스트의 격리 문제라고 생각하신 이유는 무엇일까요?

2022-07-28 05:13 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/common/exception/LevellogException.java
> +    }
해당 생성자는 `@Deprecated` 처리했습니다.

2022-07-28 05:36 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)
테스트 시작 전 모든 데이터를 지우고 테스트가 끝난 뒤 모든 데이터를 지우는 방식이면 공유하는 데이터베이스 관점에서 완벽한 테스트 격리라고 볼 수 있을 것 같아요. 

그런데 테스트에서 Transactional을 쓰는건 그런 동작이 아니라 일단 돌리고 테스트가 끝나면 롤백해주는 방식으로 알고있어요. 

인수 테스트에서 데이터가 지워지지 않은 상태로 다른 테스트가 실행되면 그 테스트는 데이터를 남긴 인수 테스트에 의존적인 테스트가 된다고 생각해요. 

`AFTER_EACH_TEST_METHOD`는 테스트가 끝나면 데이터를 지워주지만 반대로 인수테스트가 시작될 때 만약 데이터베이스에 값이 남았다면 그 값을 만든 테스트에 의존적인 테스트가 될 것 같습니다. 

그렇기 때문에 서로 완벽하게 테스트 격리가 되지 않았다고 생각했습니다 !

2022-07-28 05:41 UTC, OzRagwort approved these changes
수고하셨습니돵 😄

2022-07-28 05:43 UTC, 2yujeong approved these changes

2022-07-28 05:43 UTC, SuyeonChoi approved these changes
**신뢰 기반!** 👍

2022-07-28 05:44 UTC, merged