refactor: Member 도메인 리팩토링
woowacourse-teams/2022-levellog pull request #148
Opened 2022-07-27 13:17 UTC by kbsat

## 구현 기능
공통으로 지켜야할 컨벤션
- [x] DTO 클래스명 변경
- [x] DTO 정적 팩터리 메서드 추가(new로 생성 방지)
- [x] 도메인 검증 로직 추가
- [x] 도메인 테스트 추가
- [x] 서비스에서 @transactional 추가하기
- [x] 매개변수에서는 객체 ➡️ id 값들 순서
- [x] 커스텀 예외에 대한 구체 메세지 작성
- [x] 예외 로그에 많은 정보를 담되, 간단한 메세지로 표현
- [x] 컨트롤러테스트에서 문서화를 위한 예외케이스를 추가 (Mocking)
- [x] 서비스테스트 보강

##  논의하고 싶은 내용
- 아직 클라이언트 , 서버 단의 예외 메세지를 분리하지 않았습니다. 해당 부분은 릭꺼 머지되면 할 예정입니다. 👨‍🦽

Close #130

2022-07-27 13:49 UTC, nailseong requested changes
고생하셨읍니다. 피드백 남겼으니 확인 후 반영 부탁합니다

2022-07-27 13:49 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
>          final Member member = new Member(request.getNickname(), request.getGithubId(), request.getProfileUrl());
```suggestion
        final Member member = request.toEntity();
```

2022-07-27 13:49 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
>      private String nickname;
```suggestion
    @Column(nullable = false, length = NICKNAME_MAX_LENGTH)
    private String nickname;
```

2022-07-27 13:49 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
>      private String profileUrl;
```suggestion
    @Column(nullable = false, length = PROFILE_URL_MAX_LENGTH)
    private String profileUrl;
```

2022-07-27 13:49 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
> +        validateProfileUrl(this.profileUrl);
검증 메서드 호출을 this 전 or 후를 정해보면 좋을것 같네용

2022-07-27 13:49 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
>                                                 @RequestBody @Valid final NicknameUpdateDto nicknameUpdateDto) {
```suggestion
    @PutMapping
    public ResponseEntity<Void> updateNickname(@LoginMember final Long memberId,
                                               @RequestBody @Valid final NicknameUpdateDto request) {
```

2022-07-27 13:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +                    .hasMessageContainingAll("멤버 중복", String.valueOf(newSaveDto.getGithubId()));
`hasMessageContainingAll ` 이런 유용한 메서드도 있네용 ㅋㅋ 👍

2022-07-27 13:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
> +            perform.andDo(document("myinfo/update-nickname-invalid-length"));
```suggestion
            // docs
            perform.andDo(document("myinfo/update/nickname-invalid-length"));
```

2022-07-27 13:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
> +            perform.andDo(document("myinfo/update-nickname-blank"));
```suggestion
            // docs
            perform.andDo(document("myinfo/update/nickname-blank"));
```

2022-07-27 13:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
> +            perform.andDo(document("myinfo/update-nickname-blank"));
MyInfoAcceptanceTest에도 `myinfo/update-nickname`이 있어요. `myinfo/update/nickname`으로 변경 부탁합니당

2022-07-27 20:11 UTC, SuyeonChoi requested changes, later dismissed
로마〰️ Member 도메인 리팩터링과 인수테스트 작성하느라 수고 많으셨습니다🔥🔥

`MemberRepository`에서 `existsByGithubId()` 에 대한 테스트가 누락되었는데 확인부탁드릴게요!
(추가로 `MemberRepositoryTest`도 리팩터링하면 좋을거 같습니당ㅎㅎ)

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
> +        validateProfileUrl(this.profileUrl);
this 전에 투표 하고 갑니다〰️🗳

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
>      }
도메인 로직인거 같은데 검증로직을 호출하기 때문에 상단에 선언하신 걸까요? 아니면 검증로직이 `private`라서 하단에 선언한건가요? (저도 비슷한 문제를 고민했습니다,,,🌟🌟)

- 도메인 메서드 순서 컨벤션: `필드 → 생성자 → 검증 → 도메인로직 → 게터세터`
- https://github.com/woowacourse-teams/2022-levellog/pull/149#discussion_r931094868

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
> +                "닉네임은 " + NICKNAME_MAX_LENGTH + "자 이하여야합니다. [현재 길이:" + nickname.length() + "]");
예외메세지 정말 꼼꼼하게 작성하셨네요👍

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
> +    }
private 메서드라 클래스 하단으로 위치 변경해주세요!

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
>          final Member member = new Member(request.getNickname(), request.getGithubId(), request.getProfileUrl());
```suggestion
        final Member member = request.toMember();
```
서비스에서 객체를 생성하지 않고 `MemberRequestDto`에서 엔티티로 만들어주면 어떨까요?

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
> +        // TODO githubId를 안받아도 될듯? GithubProfileDto에 이미 정보가 존재함. + save의 예외 발생을 이용하면 로직 간단해질듯
좋은 아이디어네요 로마👍👍👍 리팩터링 가시죠🔥🚀

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
>      @Test
코멘트가 작성되지 않아서 여기에 씁니다,,!
`findMemberById`에서 id에 해당하는 멤버가 존재하지 않는 예외 테스트도 추가하는건 어떨까요?

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +
불필요한 개행인거 같습니닷,,!

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +            assertThat(id).isEqualTo(savedMember.getId() + 1);
given부터 트랜잭션과 격리수준이 보장되어야 통과될거 같아요.
save 테스트처럼 `assertThat(memberRepository.findById(id)).isPresent();` 정도로 검사해도 되지 않을까요?

2022-07-27 20:11 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/presentation/MemberController.java
> +    public ResponseEntity<MembersDto> searchBy(@RequestParam(defaultValue = "") final String nickname) {
api를 하나로!!!👍👍👍👍👍

2022-07-28 02:32 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
>          final String token = login("로마")
.getToken()은 개행할 필요 없어 보여요!

2022-07-28 02:32 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +        @DisplayName("saveIfNotExist 메서드는 깃허브 아이디로 저장된 멤버가 있으면 가입된 멤버의 ID를 반환한다.")
"saveIfNotExist 메서드는" class의 DisplayName과 중복되네요👀

2022-07-28 02:32 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
> +        checkSameGithubId(request);
위에 남긴 피드백과 비슷한 내용인데, saveIfNotExist에서 checkSameGithubId와 똑같은 검증 로직(memberRepository.existsByGithubId)을 수행한 후 save를 호출하고 있어요 
트랜잭션이 보장되고 현재 save 메소드는 saveIfNotExist 내에서만 호출이 된다는 걸 고려하면 save 메소드에서도 checkSameGithubId 로직을 수행할 필요가 있을까요?

2022-07-28 02:32 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
>      public Long save(final MemberCreateDto request) {
현재 save 메소드는 saveIfNotExist 메소드 내부에서만 호출이 되고 있어요
OAuth 로그인만 허용하는 정책이라면 private으로 바꿔도 되지 않을까요?

2022-07-28 04:27 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/member/domain/Member.java
> +        validateProfileUrl(this.profileUrl);
this 전에 하도록 수정하겠습니다 😊

2022-07-28 05:24 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
> +        checkSameGithubId(request);
저는 오히려 save에서 검증하는 것이 더욱 필요하다고 생각해요.
오히려 뺀다면 saveIfNotExist에서 exist 체크하는 것을 빼는 것이 더 좋을 것 같아요

2022-07-28 05:31 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +            assertThat(id).isEqualTo(savedMember.getId() + 1);
해당 부분에서는 saveIfNotExist에서 NotExist일 경우 진짜 새로 멤버를 저장하는지를 테스트하기 위해 이렇게 짰습니다.
saveIfNotExist의 경우 Exist할 경우 존재하는 id가 출력되고 해당 id로 findById를 하게되면 당연히 isPresent하게 됩니다.
따라서 원하는 테스트를 위해서는 이와 같이 검증해야된다고 생각합니다.

2022-07-28 06:09 UTC, nailseong approved these changes
믿고있었습니다.

2022-07-28 06:27 UTC, OzRagwort approved these changes
제 기준에서 큰 문제가 없다고 생각되어서 Approve 합니다. 수고하셨습니다. 

그냥 승인하기 아쉬워서 억까 한 번 해봤습니다.

2022-07-28 06:27 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
> +                    .andExpect(jsonPath("message").value("닉네임은 50자 이하여야합니다."));
꼼꼼한 테스트 굿...

2022-07-28 06:27 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
>                      status().isBadRequest()
위에 다른 테스트처럼 `.andExpect(jsonPath("message").value("nickname must not be blank"));` 같이 추가해도 좋을 것 같아요 

그리고 해당 메서드의 매개변수 `invalidNickname` 같은 네이밍도 꼭 잘못된 값인지 알 필요 없이 그냥 `nickname`이어도 되지 않을까요? (레벨 1 느낌의 리뷰한번 해봤습니당)

2022-07-28 06:44 UTC, 2yujeong approved these changes

2022-07-28 06:47 UTC, merged