refactor: Levellog 도메인 리팩토링
woowacourse-teams/2022-levellog pull request #149
Opened 2022-07-27 13:51 UTC by SuyeonChoi

## 구현 기능
- [x] DTO 클래스명 변경
- [x] DTO 정적 팩터리 메서드 추가
- [x] 도메인 검증 로직 추가
  - [x] 도메인 테스트 추가
- [x] 서비스에서 `@Transactional` 추가하기
- [x] 매개변수에서는 객체 ➡️ `id` 값들 순서
- [x] 커스텀 예외에 대한 구체 메세지 작성
- [x] 예외 로그에 많은 정보를 담되, 간단한 메세지로 표현
- [x] 컨트롤러 예외케이스 추가
- [x] 서비스테스트 보강
- [x] `findBy().ifPresent()` ➡️ `exist()` 분기처리문으로 예외처리 변경
- [x] DTO에 `equals` & `hascode` 구현
- [x] Rest Docs 예외 케이스 문서화

## 논의하고 싶은 내용
코멘트로 남겨두었습니다😄

Close #128

2022-07-27 13:55 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWriteDto.java
> +public class LevellogWriteDto {
레벨로그 create와 update 모두 사용되는 DTO입니다.
`LevellogDto`가 response로 존재해서 request 쓰기 작업과 관련된 DTO는 클래스명이 중복되지 않기 위해 이렇게 작성해보았습니다. 어떻게 생각하시나요? 더 좋은 의견 받습니다!

2022-07-27 13:55 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
> +    }
private 이면서 `update`에서 사용되지만 메서드지만 검증 로직이라서 사용되는 함수보다 상단에 위치시켰습니다.

저희 팀 컨벤션 두개가 상충하여 발생하는 문제인데 어떻게 생각하시나요?

- `순서 : 필드 → 생성자 → 검증 → 도메인로직 → 게터세터`
- `private` 메서드는 하단에 위치한다.

2022-07-28 02:37 UTC, kbsat requested changes
안녕하세요 페퍼 구현하시느라 고생하셨습니다 😊
전반적으로 잘 짜주셔서 리뷰 드릴 부분이 많이 없네요 ^.^ 한 번 남겨봤으니 보시고 수정부탁드립니다

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
>                  .filter(document("feedback/save"))
왜 given에서 document를 생성할까요 😂

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
>                  .when()
deleteId도 Find 요청을 한번 더 보내서 찾는 것이 아니라 Location에서 정보를 빼서 써도 좋을 것 같네요.

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
> +        assertThat(actual).hasValue(levellog);
hasValue 👍

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
> +    class ExistsByAuthorIdAndTeamIdTest {
Nested 클래스에도 DisplayName을 달아주세요.

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
> +                            "레벨로그를 수정할 권한이 없습니다. memberId : " + member.getId() + " levellogId : " + levellog.getId());
`hasMessageContainingAll`을 써봐도 좋을 것 같네요

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
> +        void updateContent_contentBlank_Exception(final String invalidContent) {
이 클래스에서는 메서드 네이밍이 세 번째 단락에 위치한 Exception이 첫 글자가 대문자이고다른 클래스에서는 exception을 사용하셨는데 하나로 통일하면 좋을 것 같아요 ( 개인적으로 소문자 추천 ㅋ )

2022-07-28 02:37 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +    class SaveTest {
NestedClass 네이밍에 Test를 굳이 안붙여도 될 것 같아요

2022-07-28 02:39 UTC, nailseong requested changes
고생하셨읍니다. 피드백 남겼으니 확인 후 반영 부탁합니다.

2022-07-28 02:39 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +        void save_nameNullOrEmpty_Exception(final String content) throws Exception {
응답 메시지가 `유효하지 않은 토큰입니다.` 라고 나와요. 확인 부탁합니다.

2022-07-28 02:39 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +        void save_nameNullOrEmpty_Exception(final String content) throws Exception {
전체적으로 응답의 상태 코드만 검증하고 있는데요. 메시지도 최대한 검증해주세요

2022-07-28 02:39 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/LevellogAcceptanceTest.java
>                  .getTeamId();
AcceptanceTest에 구현된 픽스처를 사용하지 않는 방향으로 리팩토링 해주세요. (`RestAssuredTemplate` 활용)

2022-07-28 02:39 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWriteDto.java
> +public class LevellogWriteDto {
`LevellogDto`와 필드가 같네요. 하나의 dto로 합치는건 어떨까요

2022-07-28 02:39 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
> +    }
지금 배치 괜찮습니다. (저는)

2022-07-28 04:25 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
> +        final boolean isNotAuthor = !author.equals(member);
밑에 작성된 isAuthor()와 로직이 중복되네요👀
전체적으로 Author인지 검증하고 예외를 터트리는 로직이 도메인과 서비스에서 조금 분산되어 있는 느낌인데 책임을 한 곳에 몰아줘도 좋을 거 같아요!

2022-07-28 04:25 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogDto.java
> +public class LevellogDto {
여기서는 `@NoArgsConstructor`를 붙여주지 않은 이유가 있을까요??

2022-07-28 04:25 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +            final Long teamId = teamRepository.save(
teamRepository를 이용해서 팀을 생성했다가 삭제하는 로직은 없어도 될 거 같아요!

2022-07-28 04:25 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>          @ParameterizedTest
`@ParameterizedTest`로 문서화를 하는 경우 마지막에 실행된 테스트로 스니펫이 생성되는 걸로 알고 있어요!
컨트롤러 테스트의 목적이 예외 케이스 문서화라면 문서로 남기기 위한 한 가지 경우에 대해서만 테스트를 진행해도 괜찮지 않을까요?
공백이나 null에 관한 여러가지 테스트는 하위 계층 테스트에서도 충분한 거 같아요!

2022-07-28 08:39 UTC, OzRagwort reviewed
다른 리뷰가 고쳐지면 Approve 해도 될 것 같습니다. 수고하셨어요

2022-07-28 08:39 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +                .orElseThrow(() -> new LevellogNotFoundException("레벨로그가 존재하지 않습니다. id : " + levellogId));
우리 id는 외롭게 두지 않기로 한게 생각나네요 혹시 조금 더 구체적으로 id 대신 levellogId는 어떠세요?

2022-07-28 08:39 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>          @ParameterizedTest
~~예외 케이스 문서화와 방어 로직이기 때문에 다 하는거 좋다고 생각합니다! 구현이 복잡한 것은 아니니까요~~

2022-07-28 08:59 UTC, SuyeonChoi reviewed
리뷰 반영했습니다!

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogDto.java
> +public class LevellogDto {
추가하였습니다👍

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWriteDto.java
> +public class LevellogWriteDto {
오 그렇네요 반영하였습니다👍

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
>                  .filter(document("feedback/save"))
@2yujeong 🥺

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +    class SaveTest {
code analysis의 테스트명 warning을 없애기 위해 붙여보았습니다.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/28749734/181430091-1de5a698-c33a-44fc-adc7-705b8f10c546.png">

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
> +                            "레벨로그를 수정할 권한이 없습니다. memberId : " + member.getId() + " levellogId : " + levellog.getId());
에러 메세지 포맷보단 중요한 정보를 포함하는지 확인하는 목적으로 사용할 수 있겠군요👍

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
> +        void updateContent_contentBlank_Exception(final String invalidContent) {
소문자 통일로 반영하였습니다👍

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>          @ParameterizedTest
감사합니다 이브! 반영했어요👍

2022-07-28 08:59 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +        void save_nameNullOrEmpty_Exception(final String content) throws Exception {
넵 반영하였습니다!!

2022-07-28 10:28 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
>                  .when()
@2yujeong 🥺🥺

2022-07-28 11:09 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/FeedbackAcceptanceTest.java
>                  .when()
Feedback 도메인 리팩할 때 고쳤습니당!!

2022-07-28 11:13 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +                .orElseThrow(() -> new LevellogNotFoundException("레벨로그가 존재하지 않습니다. id : " + levellogId));
넵 에러 메세지에도 `levellogId`로 반영했습니다!

2022-07-28 11:22 UTC, nailseong approved these changes
고생했어잉...

2022-07-28 11:24 UTC, kbsat approved these changes
approve 하겠습니다.ㅇ

2022-07-28 11:25 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +            final Long teamId = teamRepository.save(
`assertThatThrownBy(() -> levellogService.save(request, memberId, teamId))` 에서 `teamId`에 아무 변수나 삽입하기 꺼려지더라구요,, 팀을 저장하고 삭제하여 확실하게 존재하지 않는 `id`로 검증해보았습니다!

2022-07-28 11:26 UTC, 2yujeong approved these changes

2022-07-28 11:28 UTC, merged