feat: 인터뷰 질문 CRUD 구현
woowacourse-teams/2022-levellog pull request #167
Opened 2022-07-31 21:01 UTC by SuyeonChoi

## 구현 기능
- 구현한 기능을 적습니다.

## 논의하고 싶은 내용
- 논의할 내용을 적습니다.

## 공유하고 싶은 내용
- 학습한 내용, 공유할 내용 등을 적습니다.
- 위키에 작성했다면 링크 첨부, 없는 경우 삭제

## 기타
- 기타 추가할 내용이 있다면 추가합니다.
- 없는 경우 삭제

Close #이슈번호

2022-08-01 04:55 UTC, nailseong approved these changes
고생했어용 딱히 손볼 부분 없네요.... (무지성 approve아님)

2022-08-01 04:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    private String content;
```suggestion
    @Column(nullable = false)
    private String content;
```

2022-08-01 05:09 UTC, kbsat requested changes
안녕하세요 페퍼 😊
전반적으로 잘 구현해주셔서 딱히 리뷰드릴 말이 없네요~!
아래 내용은 사소한 내용들이긴 한데 한번 참고해보시면 좋을 것 같아요! 😁

2022-08-01 05:09 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    }
생성자와 같은 역할과 완전 동일한 역할을 하는데 정적 팩토리 메서드로 뺀 이유가 있을까요? 👀

2022-08-01 05:09 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interview_question/exception/InvalidInterviewQuestionException.java
> +public class InvalidInterviewQuestionException extends LevellogException {
어느 시점에 사용되는지 주석으로 적어주면 코드를 이해하는데 도움이 될 것 같아요😇

2022-08-01 05:09 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +                                       @Authentic final Long memberId) {
`@PathVariable` 끼리 붙여주면 좋을 것 같아요. 😊

2022-08-01 05:09 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
> +                .then().log().all();
```suggestion
        return get("/api/levellogs/" + levellogId + "/interview-questions", fromMemberToken).getResponse();
```
`RestAssuredTemplate.get` 을 활용해보는 건 어떨까요?

2022-08-01 05:09 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
> +            participantRepository.save(new Participant(team, alien, false));
👍

2022-08-01 05:09 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
> +            final String content = "스프링이란?".repeat(255);
```suggestion
            final String content = "a".repeat(256);
```
위와 같이 하는 것이 엣지케이스를 볼 수 있어서 좋아보이네요! 😊

2022-08-01 05:09 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
> +                            , String.valueOf(levellog.getId()));
개행 기준이 모호한것 같아요~!

2022-08-01 05:09 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
> +                    .isEqualTo(updatedContent);
여기는 한줄로 표현해도 되지 않을까용
```suggestion
            assertThat(interviewQuestion.getContent()).isEqualTo(updatedContent);
```

2022-08-01 05:37 UTC, 2yujeong reviewed
굿페퍼🍀👍🏼 크게 고칠 내용은 없어보여요!!! 고생하셨습니다!

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
특정 레벨로그와 작성자에 대한 조회인데 findAll이라는 네이밍이 말 그대로 저장된 인터뷰 질문 전체를 가져오는 기능처럼 느껴져요👀 나중에는 질문 전체 조회 혹은 내가 받은 질문 조회 등등 인터뷰 질문 조회와 관련된 기능들이 많이 추가될 거 같은데 findBy처럼 메소드 명을 좀 더 구체적으로 써주는 게 좋을 거 같아요!

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/application/InterviewQuestionService.java
> +                .findById(memberId)
```suggestion
        return memberRepository.findById(memberId)
```
중요한 건 아니지만👀

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +                    "인터뷰 질문에 대한 쓰기 권한이 없습니다. 현재 memberId : " + member.getId() + " 인터뷰 질문 작성자 memberId  : "
삭제 중에 예외가 발생했을 때는 쓰기 권한이 없다는 에러 메시지 보다는 좀 더 상황에 맞게 써주는 게 좋을 거 같아요!
추가로 memberId는 클라이언트 입장에서는 알 필요가 없는 에러 로그일 거 같은데, dev용 메시지와 클라이언트 메시지를 분리해주는 건 어떨까요??

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionAcceptanceTest.java
> +     * Scenario: 피드백 삭제
시나리오 수정이 안 되어 있네요..!

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
> +        final Team team = teamRepository.save(
```suggestion
    private Team saveTeamAndTwoParticipants(final Member participant1, final Member participant2) {
        final Team team = teamRepository.save(
```

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
> +        @DisplayName("존재하지 않는 멤버가 작성한 인터뷰 질문 작성을 요청하면 예외를 던진다.")
```suggestion
        @DisplayName("존재하지 않는 멤버가 인터뷰 질문 작성을 요청하면 예외를 던진다.")
```

2022-08-01 05:37 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
> +        @DisplayName("존재하지 않는 인터뷰 질문을 수정하면 예외를 던진다.")
```suggestion
        @DisplayName("존재하지 않는 인터뷰 질문을 삭제하면 예외를 던진다.")
```

2022-08-01 05:51 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
> +            final String content = "스프링이란?".repeat(255);
오 엣지 케이스!!! 해당 부분 외에 다른 테스트에도 반영하였습니다👍👍

2022-08-01 05:51 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
> +                    .isEqualTo(updatedContent);
객체지향생활체조에 따라 `.`을 한줄에 하나씩 써야하나 했었는데 저희 레벨로그 코드에서 `.isEqualTo()`는 한 줄에 사용하고 있었네용! 반영하였습니당👍

2022-08-01 05:51 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/exception/InvalidInterviewQuestionException.java
> +public class InvalidInterviewQuestionException extends LevellogException {
`같은 팀이 아닌 멤버만 인터뷰 질문 작성 요청을 보낸 경우` 해당 예외를 던지고 있는데요, 이 예외는 권한과 관련되어 있으므로 `UnauthorizedException.class`에서도 처리할 수 있을거 같아요. 해당 예외를 삭제하고 `InterviewQuestionNotFoundException.class`에는 예외에 대한 주석을 추가하였습니다.

(이 외에 develop 브랜치에 있는 코드에서도 예외에 대한 주석 처리가 부족한거 같네요,,🥲)

2022-08-01 05:51 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    }
서비스나 dto에서 직접 도메인을 생성하지 않고 도메인 내부에서 생성의 책임을 갖도록 정적 팩토리 메서드를 활용해보았습니다!

2022-08-01 05:52 UTC, SuyeonChoi reviewed
릭,롬 멋진 리뷰 감사합니다🙇‍♀️
열심히 반영하였는데 다시 한번 확인 부탁드리겠습니다!

2022-08-01 07:54 UTC, OzRagwort approved these changes
수고하셨어요 페퍼 ! 제가 남긴 부분과 다른 리뷰 수정하고 머지해도 좋을 것 같아요

2022-08-01 07:54 UTC, OzRagwort commented on backend/src/docs/asciidoc/interview-question.adoc
> +=== 인터뷰 질문 상세 조회 성공
문서화에서 볼 때는 인터뷰 질문 상세 조회라고 이해할 것 같은데 실제로는 목록 조회가 되는 것 같아요 !

2022-08-01 07:54 UTC, OzRagwort commented on backend/src/docs/asciidoc/interview-question.adoc
> +operation::interview-question/update/exception-unauthorized[]
진짜 꼼꼼한 테스트 ㅠㅠ 배우겠습니다 👍

2022-08-01 07:54 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    private Member to;
이 to 변수가 사용되는 곳이 있을까요? 정적 팩터리 메서드에서도 levellog의 author를 to로 만드는 것 같아요. 

혹시 꼭 필요한게 아니라면 사용할 때 levellog의 author를 쓰고 `Member to`는 지우는 건 어떤가요?

2022-08-01 07:54 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    public void validateAuthor(final Member member) {
꼼꼼한 검증 좋습니당

제 개인적으로는 이름만 보니 뭔가 모호한 것 같기도 했어요 인가에 대한 검증을 표현하고 싶다면 `validateUnauthorizedAuthor`라거나 인터뷰 질문의 author에 대한 검증이라는 것을 표현하고 싶다면 `validateInterviewQuestionAuthor`와 같이 조금 명확해도 좋을 것 같아요

2022-08-01 08:08 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    private Member to;
숟가락 얹으면 `from` -> `author`는 어때용?

2022-08-01 08:16 UTC, nailseong reviewed
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/68512686/182104452-40fc41da-bb33-45cb-8721-45030ae9736c.png">
`interview_question` -> `interviewquestion` 패키지 이름변경해주세요.

2022-08-01 09:51 UTC, kbsat approved these changes
잘 고쳐주셨네요 ^.^ 다음 리뷰 때 만나요.. 이만 approve 하겠습니다.

2022-08-01 09:51 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/InterviewQuestionTest.java
> +            final String content = "a".repeat(256);
👍

2022-08-02 01:33 UTC, SuyeonChoi commented on backend/src/docs/asciidoc/interview-question.adoc
> +operation::interview-question/update/exception-unauthorized[]
알린도 충분히 잘하시는걸용👍 저와의 PR 경쟁만 릴랙스 해주시져🌟

2022-08-02 01:33 UTC, SuyeonChoi commented on backend/src/docs/asciidoc/interview-question.adoc
> +=== 인터뷰 질문 상세 조회 성공
오 꼼꼼한 리뷰 감사합니다👍👍👍👍👍

2022-08-02 01:52 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +                    "인터뷰 질문에 대한 쓰기 권한이 없습니다. 현재 memberId : " + member.getId() + " 인터뷰 질문 작성자 memberId  : "
```java
public void validateAuthor(final Member member, final String errorMessage) {
        final boolean isNotAuthor = !from.equals(member);
        if (isNotAuthor) {
            throw new UnauthorizedException(
                    errorMessage + " 로그인 memberId : " + member.getId() + " 인터뷰 질문 작성자 memberId  : " + from.getId()
                            + " 인터뷰 질문 id : " + getId() + " levellogId : " + levellog.getId());
        }
    }
```
구체적인 상황에 맞는 에러 메세지를 인자로 받아 사용할 수 있도록 위와 같이 수정했습니다. 
dev용 메세지와 클라이언트 메세지는 현재도 `UnauthorizedException` 클래스에서 분리되어있지 않나요??

```java
public class UnauthorizedException extends LevellogException {

    private static final String CLIENT_MESSAGE = "권한이 없습니다.";

    public UnauthorizedException(final String message) {
        super(message, CLIENT_MESSAGE, HttpStatus.UNAUTHORIZED);
    }
}
```

2022-08-02 01:54 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    public void validateAuthor(final Member member) {
좋은 의견 감사합니다 알린👍
`validateInterviewQuestionAuthor`로 변경하여 보다 명확해졌네요ㅎㅎ

2022-08-02 02:05 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
내가 누군가에게 작성한 레벨로그의 인터뷰 질문 목록을 조회하는 API입니다. 
가장 단순하게는 `findByLevellogIdAndMemberId`로 변경할 수 있을거 같은데요, 조건이 많다 보니 불가피하게 길어져서 아쉽네요,,
혹시 추천할만한 메서드명이 있으실까용?? 🥺🥺

2022-08-02 02:19 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +    private Member to;
저도 레벨로그로부터 `to`를 얻어오니 해당 도메인에 선언할 필요가 없다고 느꼈어요! 반영했습니당ㅎㅎ
피드백도 비슷한거 같은데 반영하면 좋을거 같아요!

릭의 숟가락도 반영했습니다👍

2022-08-02 02:19 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
`findByLevellogIdAndMemberId`도 괜찮은데 나중에 특정 레벨로그에 대해 내가 받은 인터뷰 질문 조회 기능도 추가된다면 메소드 명이 겹칠 거 같아요🤔 저는 조금 길어지더라도 `findByLevellogIdAndFromMemberId`나 `findByLevellogAndFromMember`가 괜찮을 거 같습니당! 근데 지금 보니까 FeedbackController도 findByLevellogId가 아니라 findAll로 되어있네요...👀 FeedbackController랑 맞춘다면 `findByFromMember`도 괜찮을 거 같아요

2022-08-02 02:23 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
제 기준 맘에드는 메서드 명(컨트롤러 메서드라고 가정하면)
- `findByLevellogAndFromMember`
- `findMyInterviewQuestionByLevellog` -> 길지만 ................ ...!

2022-08-02 02:31 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
# findByLevellogAndAuthor

2022-08-02 02:33 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
`findAllMyInterviewQuestionsByLevellog` 저도 알린과 비슷하네요 😊

2022-08-02 02:46 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/interview_question/presentation/InterviewQuestionController.java
> +    public ResponseEntity<InterviewQuestionsDto> findAll(@PathVariable final Long levellogId,
조회하다: `find`
목록 반환: `all`
현재 로그인한 멤버가 작성한 인터뷰 질문: `MyInterviewQuestion`

레벨로그는 인자로 받기에 생략하였습니다.

⬇️최종⬇️
# findAllMyInterviewQuestion

2022-08-02 02:52 UTC, merged

2022-08-02 02:55 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interview_question/domain/InterviewQuestion.java
> +                    "인터뷰 질문에 대한 쓰기 권한이 없습니다. 현재 memberId : " + member.getId() + " 인터뷰 질문 작성자 memberId  : "
맞아요 제가 리팩했습니당