feat: 사전 질문 CRUD 구현
woowacourse-teams/2022-levellog pull request #168
Opened 2022-07-31 21:11 UTC by OzRagwort

## 구현 기능
- 인터뷰 진행 전에 인터뷰이에게 사전 질문을 작성해줄 수 있다.
- 인터뷰 진행 시 인터뷰이 피드백 작성 화면에서 사전 질문을 확인할 수 있다.

## 논의하고 싶은 내용
- 사전질문 엔티티가 레벨로그와 누가 사전질문을 작성하는건지를 @ManyToOne으로 가지는데 괜찮은가유

Close #160

2022-08-01 05:15 UTC, SuyeonChoi requested changes
알린 인터뷰 사전 질문 CRUD 구현하시느라 수고 하셨습니다!👏👏
주말동안 CRUD를 끝내시다니,,🚀

Service와 도메인에서 방어 로직을 추가적으로 구현하면 더 좋을거 같아요!!
추가적인 테스트가 더 필요하겠지만... 우리의 3차 데모데이를 위해서 화이팅 해봅시당🔥🔥🔥

2022-08-01 05:15 UTC, SuyeonChoi commented on backend/src/docs/asciidoc/preQuestion.adoc
> +==== url의 레벨로그 id가 잘못된 경우
```suggestion
==== url의 레벨로그 id와 사전 질문의 레벨로그 id가 일치하지 않는 경우
```
이렇게 변경하는건 어떨까요? `url의 레벨로그 id가 잘못된 경우`만 보면 존재하지 않는 레벨로그를 요청한 느낌이 들어서 처음에 헷갈렸네요,,! 문서화도 열심히 했으니 조금 더 상세하게 설명하면 이해하기 쉬울거 같아요🙂

2022-08-01 05:15 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private void validateQuestion(final String question) {
```suggestion
    private void validatePreQuestion(final String question) {
```
현재 `인터뷰질문`과 `사전인터뷰` 도메인 용어가 혼용될 수 있으니 비록 특정 도메인 내부라고 하더라도 정확한 용어를 사용하는게 헷갈리지 않을거 같아요!

2022-08-01 05:15 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    }
`update`에서 검증만 해주고 있는데 어떻게 사전 질문 내용이 업데이트되는 걸까요..?🤭
도메인 로직에 대한 테스트가 추가되어야할거 같아요!

2022-08-01 05:15 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +            throw new InvalidFieldException("입력한 levellogId와 사전 질문의 levellogId가 다릅니다. 입력한 levellogId : " + levellogId);
해당 부분에 대한 검증은 `PreQuestion`도메인이 책임질 수 있지 않을까요?

2022-08-01 05:15 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        final Member from = getMember(memberId);
같은 레벨 인터뷰 팀에 속한 멤버만 사전 인터뷰 질문을 남길 수 있도록 방어 로직이 필요할거 같습니다🤓🤓

2022-08-01 05:27 UTC, nailseong requested changes
알린 고생많았어요. 피드백 확인 후 반영 부탁해용 😉

2022-08-01 05:27 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andDo(print());
```suggestion
            final ResultActions perform = mockMvc.perform(put("/api/levellogs/1/pre-questions/1")
                            .header(HttpHeaders.AUTHORIZATION, "Bearer " + TOKEN)
                            .contentType(MediaType.APPLICATION_JSON)
                    .andDo(print());
```

2022-08-01 05:27 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andDo(print());
```suggestion
            final ResultActions perform = mockMvc.perform(put("/api/levellogs/1/pre-questions/1")
                            .header(HttpHeaders.AUTHORIZATION, "Bearer " + TOKEN)
                            .contentType(MediaType.APPLICATION_JSON)
                    .andDo(print());
```
ditto

2022-08-01 05:27 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andDo(print());
```suggestion
            final ResultActions perform = mockMvc.perform(delete("/api/levellogs/1/pre-questions/1")
                            .header(HttpHeaders.AUTHORIZATION, "Bearer " + TOKEN)
                            .contentType(MediaType.APPLICATION_JSON)
                    .andDo(print());
```
ditto

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
> +    }
사전 질문 상세 조회를 public으로 열어주어도 괜찮나요? 작성자가 아니면 조회하지 못하도록 해야하지 않을까요?

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
조회를 요청한 사용자가 작성자가 아닌 경우라면 어떻게 되어야하나요?

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
```suggestion
    public void update(final PreQuestionDto request, final Long preQuestionId, final Long levellogId, final Long memberId) {
        final PreQuestion preQuestion = getPreQuestion(preQuestionId);
        
        // preQuestion의 from이 member가 아니면 예외를 던지는 로직
        
        validateLevellog(preQuestion, levellogId);

        preQuestion.update(request.getPreQuestion());
    }
```
이런식으로 예외 던지는 상황을 쪼개는건 어떨까요?
지금은 `PreQuestion` PK에 해당하는 값이 존재해도 작성자가 아닌경우라면 `PreQuestionNotFoundException`이 터지네요

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
ditto

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private String preQuestion;
```suggestion
    @Column(nullable = false)
    @Lob
    private String preQuestion;
```

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    }
update 메서드는 검증만 하나요? 🤔

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +    private final int interviewerNumber = 0;
```suggestion
    privat int interviewerNumber = 0;
```
😮‍💨

2022-08-01 05:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +    private final boolean isClosed = false;
ditto

2022-08-01 05:58 UTC, kbsat requested changes
고생하셨습니다 알린 😊
조금 수정할 사항들 올려보았으니 한번 더 고생좀해주세요 😁

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
preQuestion은 바깥에서 getPreQuestion 해서 인자로 가져오고 levellogId는 메서드 안에서 getLevellog를 하는데 한 방식으로 통일시키는 것이 좋을 것 같아요. 👀

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +            throw new InvalidFieldException("내 글의 사전 질문을 작성할 수 없습니다.");
```suggestion
            throw new InvalidFieldException("내 레벨로그에 사전 질문을 작성할 수 없습니다.");
```
헷갈릴 우려가 있습니다. 정확한 도메인 이름을 사용해주세요! 🤤

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    }
실제 update 동작은 일어나지 않는건가요? 😱

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +                preQuestion.getId());
48번 라인은 개행하지 않았는데 여기서는 개행을 해주셨네요? 🤔

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/exception/PreQuestionNotFoundException.java
> +    }
```suggestion
    private static final String ERROR_MESSAGE = "사전 질문이 존재하지 않습니다.";
    
    public PreQuestionNotFoundException(final String message) {
        super(message, ERROR_MESSAGE, HttpStatus.NOT_FOUND);
    }
```
이건 어떨까요? 클라이언트 입장에서는 사전 질문인지 작성한 사전 질문인지 알 필요가 없어 보여서요 😁

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
> +                                       @Authentic final Long memberId) {
`@PathVariable` 끼리는 붙여주면 좋을 것 같아요

2022-08-01 05:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
> +    public ResponseEntity<Void> save(@RequestBody @Valid final PreQuestionDto createDto,
```suggestion
    public ResponseEntity<Void> save(@RequestBody @Valid final PreQuestionDto request,
```
같은 클래스의 update 메서드에서는 request를 사용하고 있더라구요 😗

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +        final RestAssuredResponse loginResponse2 = login("이브");
테스트 아래에서 `loginResponse1.getToken()` 과 `loginResponse2.getMemberId()` 이런 방식의 요청을 계속 보내는데 이를 미리 변수로 빼놓으면 이해하는데 테스트 코드를 이해하는데 도움이 될 거 같아요.

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +                .header(HttpHeaders.LOCATION, equalTo("/api/levellogs/" + levellogId + "/pre-questions/1"));
```suggestion
                .header(HttpHeaders.LOCATION, notNullValue());
```
테스트하고자 하는 목적에 따라 다르겠지만 저는 위 정도면 충분해보여요.
기존 코드는 테스트 격리에 따라서 영향을 받을 것 같아서 위 방법이 좋아보이네요 😎

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +                .split("/pre-questions/")[1];
`사전 질문 수정하기` 테스트인데 생성에 대한 문서를 계속 생성해주고 있네요.
post 요청이 계속해서 일어나는데 이를 픽스쳐로 뺄 수는 없을까요? 🤔

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +        response.statusCode(HttpStatus.NO_CONTENT.value());
수정이 잘 되었는지 테스트해주지 않아서 예외를 못잡았네요 🥲

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +                .split("/pre-questions/")[1];
이것도 마찬가지로 `사전 질문 조회하기` 인데 생성 요청 문서를 만들어주고있네요 👀

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +        response.statusCode(HttpStatus.NO_CONTENT.value());
실제 삭제 되었는지도 검증해주면 좋을 것 같아요.

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
> +                    new Team("잠실 네오조", "트랙룸", LocalDateTime.now().plusDays(3), "profile.img"));
👍

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
> +public class PreQuestionServiceTest extends ServiceTest {
PreQuestionServiceTest에 누락된 테스트가 많이 보이네요.
`findById`, `update`,`deleteById` 테스트 코드 추가해주세요.

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andReturn().getResponse().getContentAsString().contains("preQuestion must not be blank");
체이닝을 억지로 사용하려니 더 복잡해보여요 😂
한 줄에 점 하나씩이라는 규칙도 위반하고 있네요

2022-08-01 05:58 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .save(preQuestionDto, 1L, 4L);
`doThrow`와  `given().willThrow` 의 차이는 무엇일까요?

2022-08-01 06:34 UTC, nailseong reviewed
put, delete 요청에 잘못 코멘트를 달았네용 확인 부탁해요

2022-08-01 06:34 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andDo(print());
```suggestion
            final ResultActions perform = mockMvc.perform(get("/api/levellogs/1/pre-questions/1")
                            .header(HttpHeaders.AUTHORIZATION, "Bearer " + TOKEN)
                            .contentType(MediaType.APPLICATION_JSON)
                    .andDo(print());
```
get 요청에 body는 지워주세요

2022-08-01 06:34 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andDo(print());
```suggestion
            final ResultActions perform = mockMvc.perform(get("/api/levellogs/1/pre-questions/1")
                            .header(HttpHeaders.AUTHORIZATION, "Bearer " + TOKEN)
                            .contentType(MediaType.APPLICATION_JSON)
                    .andDo(print());
```
ditto

2022-08-01 07:25 UTC, 2yujeong requested changes

2022-08-01 07:25 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
> +    }
이건 인터뷰어끼리 서로 사전 질문 공유를 원하는 크루들이 있어서(질문 겹치는 거 방지) 논의해 봐도 좋을 거 같아요!
그런데 정책하고는 별개로 저는 사전 질문 상세 조회 기능을 특정 레벨로그에 대해 내가 쓴 사전 질문을 조회하는 기능으로 이해했는데, 코드를 보면 특정 레벨로그에 대한 모든 사전 질문이 조회되는 거 같아요!  특정 레벨로그에 대한 모든 사전 질문 조회 기능이 필요할까요??

2022-08-01 07:25 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionTest.java
> +public class PreQuestionTest {
update 테스트도 필요할 거 같아요!

2022-08-01 07:25 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
> +    public String getPreQuestionId() {
쓰이는 곳이 없네요👀

2022-08-01 07:25 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .contains("입력한 levellogId와 사전 질문의 levellogId가 다릅니다. 입력한 levellogId : 1");
contains()에서 반환되는 true / false를 이용해 검증하는 로직이 없는 거 같아요! contains()에 아무 값이나 입력해도 반환된 false를 검증하는 데가 없어서 테스트가 통과되네요

2022-08-01 07:33 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .save(preQuestionDto, 1L, 4L);
```suggestion
            BDDMockito.willThrow(new InvalidFieldException("사전 내용은 공백이나 null일 수 없습니다."))
                    .given(preQuestionService)
                    .save(preQuestionDto, 1L, 4L);
```
BDDMockito.willThrow는 Mockito.doThrow와 같은 동작을 해요. BDD 스타일(given, when, then)을 위해서 BDDMockito의 메서드를 사용해주세요. 😉

2022-08-02 02:55 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/presentation/PreQuestionController.java
> +    }
릭과 이브가 말한 것 처럼 특정 레벨로그에 내가 작성한 사전 질문이 조회되어야 합니다. 수정했습니다!

2022-08-02 03:39 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        final Member from = getMember(memberId);
방어 로직 추가했습니다

2022-08-02 03:40 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
사전 질문을 작성한 사람이 아니라면 예외가 발생하도록 수정했습니다.

2022-08-02 03:40 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
조금 더 정확하고 구체적으로 예외를 잡을 수 있도록 수정했습니다. 가능하면 메서드 하나가 하나의 일만 하도록 수정하면서 수정해봤습니다.

2022-08-02 03:41 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +    private final int interviewerNumber = 0;
전체 포맷팅하다가 실수로 넣었나봅니다 ㅠㅠ 수정했습니다!

2022-08-02 03:42 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
Levellog를 파라미터로 주도록 수정했습니다.

2022-08-02 03:42 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +            throw new InvalidFieldException("내 글의 사전 질문을 작성할 수 없습니다.");
도메인 이름을 쓰는 방식으로 수정했습니당

2022-08-02 03:42 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    }
수정했습니다!

2022-08-02 03:43 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/exception/PreQuestionNotFoundException.java
> +    }
수정했습니다

2022-08-02 03:43 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +        final RestAssuredResponse loginResponse2 = login("이브");
이것을 포함하여 여러가지를 변수로 빼거나 메서드 분리를 하여 코드를 조금 더 읽기 쉽게 수정했습니다

2022-08-02 03:44 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +                .split("/pre-questions/")[1];
픽스처로 빼봤습니다!

2022-08-02 03:44 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +        response.statusCode(HttpStatus.NO_CONTENT.value());
ㅠㅠ  꼼꼼한 테스트에 신경써야겠네요

2022-08-02 03:44 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
> +public class PreQuestionServiceTest extends ServiceTest {
추가했습니다

2022-08-02 03:45 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .andReturn().getResponse().getContentAsString().contains("preQuestion must not be blank");
수정했습니다! 실제로 검증이 안되고 있다는 리뷰도 적용하여 이 부분을 더 간단하고 정확하게 동작하도록 수정했습니다.

2022-08-02 03:47 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredResponse.java
> +    public String getPreQuestionId() {
이제 생겼습니다. . . ! 쓰려고 만들고 안썼네요..ㅠ

2022-08-02 03:47 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .save(preQuestionDto, 1L, 4L);
오 감사합니다 mock 테스트는 참 신기하네요

2022-08-02 03:50 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                    .save(preQuestionDto, 1L, 4L);
[BDD 방식](https://github.com/woowacourse-teams/2022-levellog/pull/168#discussion_r934221818)

doThrow는 when을 사용하는데 given().willThrow는 given을 사용합니다. 해당 코드가 있는 부분이 given이므로 given/when/then 스타일을 맞추기 위해 BDDMockito.willThrow()를 쓰는 것이 더 이해하기도 쉬울 것 같습니다.

2022-08-02 04:05 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +        response.statusCode(HttpStatus.NO_CONTENT.value());
서비스에서 테스트를 충분히 해준다면 괜찮을 것 같기도 하네요.

2022-08-02 04:33 UTC, nailseong requested changes
소소한 코멘트 남겼습니다. 확인 후 괜찮으면 반영해주세용.

2022-08-02 04:33 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
이 검증 메서드는 `findById`, `update`, `delete`에서 호출하고 있는데요. 이 메서드에서 예외가 터지는 케이스는 테스트가 없네요.
혹시 getPreQuestion 에서 미리 예외가 터져서 지금 메서드가 불필요한건 아닐까요?

2022-08-02 04:33 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/exception/PreQuestionNotFoundException.java
> +    private static final String ERROR_MESSAGE = "사전 질문이 존재하지 않습니다.";
```suggestion
    private static final String CLIENT_MESSAGE = "사전 질문이 존재하지 않습니다.";
```
조금 사소하지만....ㅎㅎ

2022-08-02 04:33 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     * Scenario: 사전 등록 생성하기
```suggestion
     * Scenario: 사전 질문 생성하기
```

2022-08-02 04:33 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     * Scenario: 사전 등록 수정하기
ditto

2022-08-02 04:33 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     * Scenario: 사전 등록 조회하기
ditto

2022-08-02 04:33 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     * Scenario: 사전 등록 제거하기
ditto ㅎㅎ

2022-08-02 04:33 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +                .statusCode(HttpStatus.NOT_FOUND.value());
👍

2022-08-02 04:33 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private String preQuestion;
필드이름이 preQuestion이네요. DB에서 조회할 때 쿼리가 `SELECT pre_question.pre_question ...` 형태겠는데요.
levellog처럼 `content`는 어떨까요?

2022-08-02 05:52 UTC, kbsat requested changes
안녕하세요 알린 ^.^ 요청드린 사항 잘 고쳐주셨네요.
추가로 작업하신 부분도 리뷰 남겨드렸으니 확인 부탁드립니다 😊

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private String preQuestion;
저도 동의합니다. **_interviewQuestion_** 에서도 `content`를 사용하고 있기도 하고
`preQuestion` 보다는 `content`가 괜찮아 보이네요.

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
해당 `validateIsAuthor`는 똑같은 동작으로 `PreQuestion`의 생성자에 존재하는 걸 확인했습니다.
( 차이가 있다면 서비스에서 하는 `validateIsAuthor()`는 UnauthorizedException 을 던지고 도메인에서는 InvalidFieldException을 던집니다. ) 
해당 검증의 책임을 PreQuestio의 책임으로만 부여해주면 어떨까요?

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateExistParticipantByMember(levellog.getTeam(), from);
메서드 이름이 이해하기 좀 어려운 것 같아요.

```suggestion
        validateSameTeamMember(levellog.getTeam(), from);
```
요런건 어떨까요?? 이건 적용하지 않으셔도 됩니다 😊

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        final Member from = getMember(memberId);
`from` 보다는 `questioner`는 어떨까요?
questioner라는 말이 더 명료하게 느껴져요.

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    }
```suggestion
    private void validateIsAuthor(final Levellog levellog, final Member member) {
        if (levellog.isAuthor(member)) {
            throw new InvalidFieldException("내 레벨로그에 사전 질문을 작성할 수 없습니다.");
        }
    }
```

타입이 levellog인데 변수명이 author인게 어색해요🥲

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private Member from;
```suggestion
    private Member author;
```
from 보다는 author 어떠신가요?

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
> +    boolean existsByLevellogAndFrom(Levellog levellog, Member member);
해당 부분에 대한 Repository 테스트가 빠졌군요 👀

2022-08-02 05:52 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
> +        final PreQuestion preQuestion = preQuestionRepository.save(new PreQuestion(levellog, from, content));
```suggestion
        final Member levellogAuthor = memberRepository.save(new Member("알린", 12345678, "알린.img"));
        final Team team = teamRepository.save(new Team("선릉 네오조", "목성방", LocalDateTime.now().plusDays(3), "네오조.img"));
        final Levellog levellog = levellogRepository.save(Levellog.of(levellogAuthor, team, "알린의 레벨로그"));

        final Member questioner = memberRepository.save(new Member("로마", 56781234, "로마.img"));
        final String content = "로마가 쓴 사전 질문입니다.";
        final PreQuestion preQuestion = preQuestionRepository.save(new PreQuestion(levellog, questioner, content));
```
개행을 적절히 사용하면 가독성을 늘릴 수 있을 것 같아요.

2022-08-02 05:52 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
>          }
getter를 사용하는 것 보다 preQuestion 객체에게 메세지를 보내는 것이 더 명료하겠네요.
```suggestion
    private void validateFromMember(final PreQuestion preQuestion, final Member member) {
        if (preQuestion.isNotSameAuthor(member)) {
            throw new UnauthorizedException("자신의 사전 질문이 아닙니다.");
        }
```

2022-08-02 06:12 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        final Member from = getMember(memberId);
아니면 `author`

2022-08-02 07:45 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
맞습니다 ㅠㅠ 지금은 중복 검증이라 돌고있지 않네요! 수정했습니다.

2022-08-02 08:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
>          }
```suggestion
    private void validateFromMember(final PreQuestion preQuestion, final Member member) {
        if (!preQuestion.isSameAuthor(member)) {
            throw new UnauthorizedException("자신의 사전 질문이 아닙니다.");
        }
```

boolean 형을 반환하는 isXXX와 같은 메서드는 특별한 상황이 아니면 긍정형으로 만들라고 들었습니다. isNotXX로 만들면 긍정형으로 검증해야할 때 !isNotXXX가 되어 부정에 부정이 되기 때문입니다. 그래서 이 부분을 제안 처럼 수정해봤습니다.

2022-08-02 08:12 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/PreQuestionRepositoryTest.java
> +        final PreQuestion preQuestion = preQuestionRepository.save(new PreQuestion(levellog, from, content));
개행 신경 써 보겠습니다. 그리고 from 을 questioner로 쓰는게 더 좋아보여서 테스트 전체적으로 수정해봤습니다 !

2022-08-02 08:13 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestionRepository.java
> +    boolean existsByLevellogAndFrom(Levellog levellog, Member member);
이부분은 중복 검증 로직을 제거하면서 빠졌습니다 👍

2022-08-02 08:13 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    }
이부분과 도메인 엔티티에서 잘못썼던 것 같습니다. 수정했습니다!

2022-08-02 08:13 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        final Member from = getMember(memberId);
questioner으로 수정했습니다!

2022-08-02 08:14 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateExistParticipantByMember(levellog.getTeam(), from);
더 짧고 명확해진 것 같아서 적용했습니다

2022-08-02 08:15 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    }
중복 검증을 제거했습니다

2022-08-02 08:16 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private String preQuestion;
수정했습니다

2022-08-02 08:16 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     * Scenario: 사전 등록 생성하기
수정했습니다 ㅠ

2022-08-02 08:16 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/exception/PreQuestionNotFoundException.java
> +    private static final String ERROR_MESSAGE = "사전 질문이 존재하지 않습니다.";
굿굿 조아효

2022-08-02 08:18 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/domain/PreQuestion.java
> +    private Member from;
좋습니당

2022-08-02 09:33 UTC, 2yujeong approved these changes
고생 많으셨어요 알린!!!! 감사합니다!!

2022-08-02 09:33 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateLevellog(preQuestion, levellog);
이 검증 로직에 대해 예외가 발생하는 경우는 어떤 상황일까요??
상황이 잘 생각나지 않아서 질문 남깁니다👀

2022-08-02 09:33 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
> +            participantRepository.save(new Participant(team, questioner, false));
given을 작성해 준 이유는 테스트 흐름을 파악하기 위함인가요??

2022-08-02 09:33 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                            .value("preQuestion must not be blank"));
```suggestion
           perform.andExpectAll(
                    status().isBadRequest(),
                    jsonPath("message").value("preQuestion must not be blank")
            );
```
코드가 더 깔끔해질 거 같아요!

2022-08-02 10:53 UTC, kbsat approved these changes
알린 고생했어요. 코드가 훨씬 깔끔해졌네요.
테스트도 많이 작성되었구요! 다음에도 화이팅합시다 😉

2022-08-02 12:01 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateLevellog(preQuestion, levellog);
@2yujeong path variable이 잘못된 경우 예외가 발생할거 같네용
`/api/levellogs/{알린의 레벨로그id}/pre-questions/{페퍼의 레벨로그에 달린 사전질문 id}`

2022-08-02 12:01 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateLevellog(preQuestion, levellog);
@2yujeong path variable이 잘못된 경우 예외가 발생할거 같네용
`/api/levellogs/{알린의 레벨로그id}/pre-questions/{페퍼의 레벨로그에 달린 사전질문 id}`

2022-08-02 12:12 UTC, nailseong requested changes
알린 너무 잘 리팩토링 해주셨네요!! 살짝 아쉬운 부분 피드백 남겼어요. 확인해 보시고 괜찮으면 반영 부탁합니다 😉

2022-08-02 12:12 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateMyQuestion(preQuestion, questioner);
```suggestion
        preQuestion.validate(levellog, questioner);
```
객체에게 메시지를 던져볼까요? (메서드 이름은 적절하게 변경해주세요^^)

2022-08-02 12:12 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/prequestion/dto/PreQuestionDto.java
> +public class PreQuestionDto {
```suggestion
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class PreQuestionDto {
```

2022-08-02 12:12 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     */
```suggestion
    /*
     * Scenario: 사전 질문 수정하기
     *   given: 1개의 레벨로그와 2명의 사용자(페퍼, 이브)가 있다.
     *   given: 이브가 페퍼에게 작성한 사전 질문이 있다.
     *   when: 이브는 페퍼의 레벨로그에 쓴 사전 질문 수정을 요청한다.
     *   then: 204 No Content 상태 코드를 응답받는다.
     */
```
이게 좀 더 명확하지 않을까요...?

2022-08-02 12:12 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/PreQuestionAcceptanceTest.java
> +     */
ditto

2022-08-02 12:12 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
> +            final Member questioner = memberRepository.save(new Member("로마", 56781234, "로마.img"));
```suggestion
            final Team team = saveAndGetTeam("선릉 네오조", 1);
            final Member author = saveAndGetMember("알린");
            final Member questioner = saveAndGetMember("로마");
```
이런 식으로 메서드 추출을 하면 테스트 가독성이 더 올라간다고 생각해요. 알린은 어떠신가요? 🤔

2022-08-02 12:12 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                            .value("preQuestion must not be blank"));
👀

2022-08-02 12:12 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +    }
```suggestion
    private ResultActions requestPut(final String url, final String token, final String requestContent)
            throws Exception {
        return mockMvc.perform(put(url)
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestContent))
                .andDo(print());
    }
```
메서드로 잘 추출해주셨군요!!!!!!!!!!!!!!!!!!!!! 💯
requestXXX 메서드 이름을 http method이름을 따라가는게 명확하지 않을까요? 테스트에서만 쓰이는 메서드니까요 😉

2022-08-02 12:12 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +    }
```suggestion
    private ResultActions requestUpdate(final String url, final String token, final Object request)
            throws Exception {
        final String requestContent = objectMapper.writeValueAsString(request);
        return mockMvc.perform(put(url)
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestContent))
                .andDo(print());
    }
```
조금더 날카롭게 깎을 수 있지 않을까요? 🤔

2022-08-02 12:18 UTC, SuyeonChoi requested changes
알린 많은 리뷰를 반영해서 코드가 확실히 더 깔끔해졌네용👏👏👏👏👏
도메인에 책임분리를 리뷰했는데 다소 아쉬워서 한번 더 RC 보냅니당,,, 조금만 더 **화이팅**!

+) 추가 궁금증
> 사전질문 엔티티가 레벨로그와 누가 사전질문을 작성하는건지를 @ManyToOne으로 가지는데 괜찮은가유

위의 내용을 논의하고 싶다고 하셨는데 어떤 이유에서 논의가 필요한건가요? 현재 문제가 있을까요?🧐

2022-08-02 12:18 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +            throw new UnauthorizedException("자신의 사전 질문이 아닙니다.");
다른 예외와 비교해서 `UnauthorizedException`을 던질 때는 정보를 상대적으로 적게 주는거 같네요🥲🥲
로그에는 더 구체적인 정보를 던져줘서 개발, 운영 환경에서도 디버깅이 쉽도록 하면 좋을거 같아요!
추가적으로 사전 질문 id, 현재 요청한 멤버 id, 사전질문을 작성한 멤버 id 정도를 넘겨주는건 어떨까요?

2022-08-02 12:18 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateMyQuestion(preQuestion, questioner);
꼼꼼한 방어로직 좋습니다👍👍👍

2022-08-02 12:20 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    public Long save(final PreQuestionDto request, final Long levellogId, final Long memberId) {
알린이랑 이야기를 나눈거 같은데 `자기 자신에게는 사전 질문을 작성할 수 없다`는 부분도 검증이 된걸까요?

2022-08-02 12:22 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateMyQuestion(preQuestion, questioner);
해당 검증 부분에 대한 책임이 도메인으로 완전하게 분리되지 않은거 같아요!
오류를 던지는거까지 도메인이 책임지는건 어떨까요?

https://github.com/woowacourse-teams/2022-levellog/pull/168#discussion_r934139455

2022-08-02 12:22 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        }
```suggestion
        preQuestion.validate(levellog);
```
이런식으로 책임을 도메인에게 넘겨줄 수 있을거 같습니다!

2022-08-03 01:47 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateLevellog(preQuestion, levellog);
페퍼의 코멘트가 맞습니다 감사합니다 😄

2022-08-03 01:54 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
> +            participantRepository.save(new Participant(team, questioner, false));
이 부분은 팀에 참가자가 잘 레벨로그가 작성된 상황에서 사전 질문만 없는 상황을 만들고 싶어서 이렇게 작성해봤습니다. 

다른 사용자의 사전 질문을 삭제하는 등 다른 예외는 다른 테스트에서 작성하기 때문입니다 !

2022-08-03 01:55 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +                            .value("preQuestion must not be blank"));
오 감사합니다

2022-08-03 03:54 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/application/PreQuestionServiceTest.java
> +            final Member questioner = memberRepository.save(new Member("로마", 56781234, "로마.img"));
오 좋아요 수정했습니다

2022-08-03 03:59 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/PreQuestionControllerTest.java
> +    }
오 좋아요 더 추상화시켜서 쓸 수 있겠네요

2022-08-03 04:02 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    public Long save(final PreQuestionDto request, final Long levellogId, final Long memberId) {
그 검증을 도메인과 서비스 둘 다 하고있었는데 중복 검증인 것 같아서 서비스에서는 제외했습니다.
지금은 도메인 엔티티에서 검증하고 있습니다.

2022-08-03 04:10 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        validateMyQuestion(preQuestion, questioner);
수정해봤습니다!

2022-08-03 04:10 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +        }
감사합니다 배워갑니당

2022-08-03 04:52 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/prequestion/application/PreQuestionService.java
> +    public Long save(final PreQuestionDto request, final Long levellogId, final Long memberId) {
`PreQuestion` 도메인이 `Levellog`를 알고 있고, `Levellog` 도메인은 `Team`을 알고 있습니다. 도메인끼리 협력하고 있으니 도메인에서 검증을 할 수 있을거 같은데 알린은 어떻게 생각하시나요? 지금은 객체 생성 시 검증 로직이  도메인과 서비스에 흩어져있는 느낌이 들어서요. 한 곳에서 일관성있게 관리하면 어떨까요?

+) 자기 자신에게 피드백을 작성할 수 없다는 검증은 레벨로그 도메인에서 하고 있네요
```java
public class Levellog extends BaseEntity {

    ...

    public void validateSelfFeedback(final Member member) {
        if (isAuthor(member)) {
            throw new InvalidFeedbackException(" [levellogId : " + getId() + "]", "자기 자신에게 피드백을 할 수 없습니다.");
        }
    }
}

```

2022-08-03 06:39 UTC, SuyeonChoi approved these changes
알린 수고하셨습니다👏👏 리뷰 반영 감사해용👍

2022-08-03 06:41 UTC, nailseong approved these changes
고생했어용

2022-08-03 06:41 UTC, merged