feat: 인터뷰 역할 관련 기능을 추가한다.
woowacourse-teams/2022-levellog pull request #171
Opened 2022-08-01 06:26 UTC by nailseong

## 구현 기능
- 팀 상세 조회 API Response 변경
- 팀 생성 API Request 변경
- 팀 참가자에 대한 나의 인터뷰 역할 조회 API 구현

## 논의하고 싶은 내용
### `Participants`를 단위 테스트 하기 좋은 구조로 개선하기
- `TeamService`의 비즈니스 로직을  최대한 `Participants` 일급 컬렉션에 할당했어요.
  - 다만 모든 public 메서드가 id에 의존적이여서 단위 테스트를 할 수 없어요...😢😢😢😢
### 이상해진 TeamController.findById
- `@PublicAPI`와 `@Authentic`이 공존하는게 조금 이상한데 더 좋은 방법이 있을까용?
  - 팀 상세조회시 `interviewer` & `interviewee`를 조회하기 위해서 
    - `@Authentic` 을 사용해서 로그인한 멤버의 ID를 받아요.
    - 기존 스펙대로 로그인하지 않아도 조회를 할 수 있도록 `@PublicAPI`를 붙여요.

## 기타
- `TeamController.findById` 때문에 `LoginMemberResolver` 코드에 변경이 생겼어요

Close #162

2022-08-01 08:26 UTC, kbsat requested changes
고생하셨습니다 릭 😁
추가적으로 고민해볼 내용들을 리뷰로 남겨보았습니다. 그럼 20000

2022-08-01 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
> +        }
슬프군요 🥲

2022-08-01 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
> +        }
메서드로 추출해봐도 좋을 것 같아요! 👀
혹은 participants 도메인에 책임을 넘겨도 될 것 같네요.

2022-08-01 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +        return linear.subList(from, from + interviewerNumber);
toInterviewerIds 와 toIntervieweeIds 내부 로직을 메서드 추출할 수 있을 것 같아요.

2022-08-01 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +    }
private 메서드를 아래로 빼주세요 😊

2022-08-01 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/TeamCreateDto.java
> +    @Positive
`@Positive`도 있군요  👍

2022-08-01 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/presentation/TeamController.java
> +        final InterviewRoleDto response = teamService.findMyRole(teamId, targetMemberId, memberId);
명세랑 다르긴 하지만 `@PathVariable` 이름도 targetMemberId로 바꾸면 어떨까요?
`@Authentic`으로 반환하는 값이 memberId인데 PathVariable과 헷갈릴 우려가 있어서요.
```suggestion
    @GetMapping("/{teamId}/members/{targetMemberId}/my-role")
    public ResponseEntity<InterviewRoleDto> findMyRole(@PathVariable final Long teamId,
                                           @PathVariable final Long targetMemberId,
                                           @Authentic final Long memberId) {
        final InterviewRoleDto response = teamService.findMyRole(teamId, targetMemberId, memberId);
```

2022-08-01 08:26 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +     *   given: 페퍼, 이브, 릭이 등록되어 있고, 페퍼가 로그인 상태이다.
명료한 시나리오 👍

2022-08-01 08:26 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +        final RestAssuredResponse loginResponse4 = login("로마");
아래에서 getToken() 과 getMemberId() 만을 사용하는 걸 봐서 미리 변수로 빼놓는다면 이해가 더 쉬울것 같다는 생각이 들어요.

2022-08-01 08:26 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +     */
```suggestion
     * Scenario: 팀 참가자에 대한 나(페퍼)의 역할 조회하기
     *   given: 팀이 등록되어 있다.
     *   given: 페퍼 계정으로 로그인되어 있다.
     *   when: 나(페퍼)는 같은 팀의 참가자인 릭에 대한 나의 역할을 조회한다.
     *   then: 200 Ok 상태 코드와 interviewer를 응답 받는다.
     */
```

2022-08-01 08:29 UTC, SuyeonChoi approved these changes
릭! 역할 기능 구현하시느라 고생 많으셨습니다ㅎㅎ
틈틈히 테스트까지 리팩토링 잘 해주셨네요👍👍
크게 변경을 요청드릴 부분이 없어서 어푸루브 하겟습니닷!🚀

2022-08-01 08:29 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +            perform.andDo(document("team/create/exception/interviewerNumber/not-positive"));
snippet은 생성되는데 `team.adoc`파일에서 추가를 안해주는거 같아요! 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/28749734/182100032-0ff60b50-c24e-45ab-9696-722ab8bff3e8.png">

2022-08-01 08:29 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +    private final List<Participant> values;
일급컬렉션에서 관리👍
public 메서드가`id`테스트가 힘들다고 하셨는데, 저는 일급컬렉션은 사용하되, 해당 부분을 service에서 테스트하는 것도 충분하다고 생각했습니다🤓

2022-08-01 08:29 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/dto/TeamCreateDto.java
> +    public TeamCreateDto(final String title, final String place, final LocalDateTime startAt,
👍

2022-08-01 08:29 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +        linear.addAll(participantIds);
오 참가자들을 두번 반복하는 리스트를 만들어서 구현하셨군요👍

2022-08-01 08:29 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +                    "팀 생성시 인터뷰어 수는 " + MIN_INTERVIEWER_NUMBER + "명 이상이어야 합니다. 입력한 인터뷰어 수 : [" + interviewerNumber + "]");
```suggestion
            throw new InvalidFieldException("팀 생성시 인터뷰어 수는 " + MIN_INTERVIEWER_NUMBER + "명 이상이어야 합니다. "
                    + "입력한 인터뷰어 수 : [" + interviewerNumber + "]");
```
개행을 한번 해도 좋을거 같네요!

2022-08-01 08:57 UTC, OzRagwort approved these changes
더 나은 코드가 될 제안이 잘 안보여서 저는 approve 할게요! 수고하셨습니다.

2022-08-01 08:57 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +    private RestAssuredResponse createTeam(final String token, final String title, final int interviewerNumber,
지금은 이 메서드가 사용되지는 않는 것 같아요 다시 사용하려고 남긴게 아니라면 지워도 좋을 것 같아요 !

2022-08-01 08:57 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +                .get("/api/teams/{teamId}/members/{memberId}/my-role", teamId, loginResponse3.getMemberId())
하나 배워갑니당

2022-08-01 08:57 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +    private ResultActions requestPost(final String url, final String token, final Object body) throws Exception {
이렇게 메서드 분리를 하니 확실히 깔끔해 보이네요 !

2022-08-01 09:46 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +    public boolean isValidParticipantNumber(final int participantNumber) {
팀에 포함된 멤버 수보다 인터뷰어 수가 많은 경우에 대한 예외 처리를 위해 선언된 메소드 같은데, 이 메소드는 현재 테스트에서만 쓰이고 있네요
프로덕션 코드에서도 이 메소드를 활용한 예외 처리 로직이 추가돼야 할 것 같아요

2022-08-01 09:46 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +    @DisplayName("같은 팀 참가자에 대한 나의 역할 조회하기 - observer")
위에 작성된 findMyRole_interviewer와 응답 값은 다르지만 똑같은 API에 대한 테스트인데, 응답 값이 다른 각각의 경우에 대해 2개의 인수 테스트와 문서화가 필요할까요??

2022-08-01 09:46 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +    private RestAssuredResponse createTeam(final String token, final String title, final int interviewerNumber,
쓰이지 않고 있네요!

2022-08-01 09:46 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +            @DisplayName("참가자가 3명이고, 인터뷰어 수는 2명이면 인터뷰어와 인터뷰이를 포함해서 응답한다.")
서로가 서로의 인터뷰어이자 인터뷰이인 경우에 대한 테스트인가요??
테스트 이름이 조금 헷갈려서 물어봅니다👀

2022-08-01 16:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/TeamAcceptanceTest.java
> +    @DisplayName("같은 팀 참가자에 대한 나의 역할 조회하기 - observer")
비용이 비싼 인수 테스트로 하나의 기능의 성공 케이스를 2번 체크하고 있어서 비효율적으로 보일 수 있겠네요.
2개의 인수 테스트를 작성한 이유는 제 생각에 로직이 꽤 복잡하기 때문이에요. 2가지 케이스가 모두 통과하는지 테스트 해보고싶었어요. (마음의 안정 ㅎ)
문서화까지 한 이유는 `"INTERVIEWER"` & `"OBSERVER"`응답을 모두 겸사겸사 문서화하자는 생각이었습니당.

2022-08-01 16:52 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +            @DisplayName("참가자가 3명이고, 인터뷰어 수는 2명이면 인터뷰어와 인터뷰이를 포함해서 응답한다.")
앗 맞아요. 참가자가 `n` 명이고, 인터뷰어 수가 `n - 1` 명인 경우를 테스트하고 싶었는데, 이름을 명확하게 바꿔야곘네요 ㅎㅅㅎ

2022-08-01 16:59 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +            perform.andDo(document("team/create/exception/interviewerNumber/not-positive"));
와... 이걸 보네... 🥵

2022-08-02 04:18 UTC, 2yujeong approved these changes
MockEntityFactory 배우고 갑니다👍🏼

2022-08-02 05:19 UTC, OzRagwort approved these changes
수고하셨습니다 릭 ! 

인터뷰 역할 관련 기능을 구현하시면서 `MockEntityFactory`도 추가가 되었는데 신기한 기능같아요. 

이 부분도 PR 설명 부분에 어떻게 쓰는지 왜쓰는지 간단하게 추가해주시면 좋을 것 같아요!

2022-08-02 05:19 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsTest.java
> +            );
바로 `List.of()`로 넣지 않고 `new ArrayList<>()`로 넣어주는 이유는 리스트를 가변으로 만들기 위함인가요??

2022-08-02 05:19 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
> +        }
이 부분만 주석으로 설명해놔도 좋을 것 같아요. 지금은 다른 코드들과 연관지어서 보다보니 이해가 되지만 나중에 다시 보면 헷갈릴 수도 있을 것 같아요

2022-08-02 05:19 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/common/domain/MockEntityFactory.java
> +    public static <T extends BaseEntity> T setId(final Long id, final T entity) {
BaseEntity에 id를 넣으면서 이런 것도 가능해졌네요. 신기신기합니다 😄

2022-08-02 05:23 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsTest.java
> +            );
엇 맞아요. 그런데 테스트 해보니까 가변 & 불변 여부에 상관없이 테스트가 통과하네요 ㅎㅎ

2022-08-02 10:34 UTC, kbsat approved these changes
고생하셨습니다 릭
어려운 구현이었는데 잘 구현해주셨네요 👍

2022-08-02 10:34 UTC, kbsat commented on backend/src/docs/asciidoc/team.adoc
> +include::{snippets}/team/find-my-role/observer/http-response.adoc[]
좋네용 👍

2022-08-02 10:34 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/common/domain/MockEntityFactory.java
> +package com.woowacourse.levellog.common.domain;
대박이네 👀

2022-08-02 10:34 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsTest.java
> +    }
```suggestion
    private Member getMember(final String nickname, final Long memberId) {
        final Member member = new Member(nickname, ((int) System.nanoTime()), nickname + ".com");

        return MockEntityFactory.setId(memberId, member);
    }
```
👀

2022-08-02 10:34 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsTest.java
> +        @CsvSource(value = {"2:1:2, 3", "2:4:5, 1", "4:3:4, 5, 1, 2"}, delimiter = ':')
😊

2022-08-02 10:34 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +                final int interviewerNumber) {
👍

2022-08-02 10:35 UTC, merged