feat: MyInfo API 추가
woowacourse-teams/2022-levellog pull request #177
Opened 2022-08-02 03:56 UTC by kbsat

## 구현 기능
- MyInfo 관련 기존 API URL 수정(api/myInfo -> api/my-info)
- 내가 쓴 모든 레벨로그 조회 API
- 내가 참여한 모든 팀 조회 AP

## 공유하고 싶은 내용
- ⚠️ **MyInfo 관련 URI가 변경되었습니다. 머지 전에 프론트에게 전달해야합니다.**

Close #157

2022-08-02 05:19 UTC, 2yujeong reviewed
고생하셨습니다! 존재하지 않는 memberId로 myInfo를 요청하는 경우에 대한 예외 시나리오 테스트 정도만 추가되면 좋을 거 같아요!

2022-08-02 05:19 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        final List<Levellog> levellogs = levellogRepository.findAllByAuthor(author);
```suggestion
        final List<Levellog> levellogs = levellogRepository.findAllByAuthorId(authorId);
```
어차피 LevellogWithIdDto를 생성할 때 멤버 객체를 가져 오겠지만 코드 상 더 깔끔해 보이는 거 같아요👀

2022-08-02 05:19 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +    @DisplayName("findAllByAuthroId 메서드는")
```suggestion
    @DisplayName("findAllByAuthorId 메서드는")
```

2022-08-02 05:19 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +            memberRepository.save(new Member("알린", 2222, "alien.img"));
알린은 없어도 되겠네용

2022-08-02 05:19 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +    class FindAllByMemerId {
```suggestion
    class FindAllByMemberId {
```

2022-08-02 06:00 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        final List<Levellog> levellogs = levellogRepository.findAllByAuthor(author);
사실 존재하지 않는 member 요청에 대한 검증을 하기 위해서 해당 `getMember()`를 사용하도록 코드를 작성했습니다.

2022-08-02 06:01 UTC, nailseong requested changes
고생하셨습니다. 가벼운 피드백 남겼으니 확인 후 반영 부탁해요.

2022-08-02 06:01 UTC, nailseong commented on backend/src/docs/asciidoc/myinfo.adoc
>  operation::myinfo/findAllToMe[]
```suggestion
operation::myinfo/findAllReceivedFeedbacks[]
```

2022-08-02 06:01 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +            memberRepository.save(new Member("알린", 2222, "alien.img"));
헐... 너무해

2022-08-02 06:01 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        final Member author = getMember(authorId);
매개변수로 들어온 authorId에 해당하는 member가 DB에 존재하는지 먼저 확인하는 의도인가요?

2022-08-02 06:01 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWithIdDto.java
> +    private String content;
응답 dto로 보이는데 validation 어노테이션을 달아준 이유가 있나요?

2022-08-02 06:01 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +
```suggestion
```

2022-08-02 06:01 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +
ditto

2022-08-02 06:01 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +
ditto

2022-08-02 06:01 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +
ditto

2022-08-02 06:11 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        final Member author = getMember(authorId);
네 존재하지 않는 Member라면 MemberNotFoundException을 터뜨리기 위해서 위와 같이 작성했습니다.

2022-08-02 06:13 UTC, kbsat commented on backend/src/docs/asciidoc/myinfo.adoc
>  operation::myinfo/findAllToMe[]
오 큰일날뻔..

2022-08-02 07:16 UTC, OzRagwort requested changes
수고하셨습니다 로마 간단한 것들 적어봤습니다. 로마 파이팅!

2022-08-02 07:16 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
> +                .body("levellogs.content", contains("레벨로그1 내용", "레벨로그2 내용"));
```suggestion
        response.statusCode(HttpStatus.OK.value())
                .body("levellogs.id", contains(Integer.parseInt(levellogId1), Integer.parseInt(levellogId2)))
                .body("levellogs.content", contains("레벨로그1 내용", "레벨로그2 내용"));
```

이 코드 있는 위에 levellogId1과 levellogId2를 선언만하고 사용하지 않는 것 같아요. then에서 검증하면서 사용하거나 변수 선언을 안해도 될 것 같아요 

이 코드의 밑에 있는 `findAllMyTeams()`와 통일성을 생각하면 변수 선언을 하지 않는게 좋아보여요!

2022-08-02 07:16 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogRepositoryTest.java
> +                new Team("선릉 브라운조", "무중력 광장", LocalDateTime.now().plusDays(1), "campus.png"));
```suggestion
        final Team team = teamRepository.save(
                new Team("선릉 브라운조", "무중력 광장", LocalDateTime.now().plusDays(1), "campus.png"));
        final Team team2 = teamRepository.save(
                new Team("선릉 네오조", "수성방", LocalDateTime.now().plusDays(1), "campus2.png"));
```

귀찮을 수도 있지만 테스트에서 사용되는 값이 조금씩 다르면 어떨까요? 테스트는 메서드의 명세이기 때문에 실제 데이터같은 값을 넣어주는게 좋다는 리뷰를 받았었어서 생각이 났습니다!

2022-08-02 07:16 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/ParticipantRepositoryTest.java
> +    @DisplayName("findAllByMember 메서드는 해당 멤버가 포함된 모든 partiipant를 반환한다.")
```suggestion
    @DisplayName("findAllByMember 메서드는 해당 멤버가 포함된 모든 participant를 반환한다.")
```

구웃

2022-08-02 11:19 UTC, SuyeonChoi reviewed
로마 수고하셨습니다! 👏👏👏
저는 추가로 피드백 드릴게 별로 없네용ㅎㅎ
다른 분들이 피드백 주신거만 반영하면 저도 어푸루브 할게요!

2022-08-02 11:19 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
>      private final MemberService memberService;
오 `MyInfoController`는 모두 서비스를 의존하는군여👀

2022-08-02 11:19 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWithIdDto.java
> +import javax.validation.constraints.NotBlank;
```suggestion
import com.woowacourse.levellog.levellog.domain.Levellog;
import javax.validation.constraints.NotBlank;
```
사용하지 않는 import 정리 부탁드립니다!

2022-08-02 14:25 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/levellog/dto/LevellogWithIdDto.java
> +    private String content;
Oops👍

2022-08-02 14:38 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/member/presentation/MyInfoController.java
>      private final MemberService memberService;
MyInfoController에서 다른 Service에서 구현된 기능을 활용하도록 작성해보았습니다.
해당 방법이 가장 합리적이라고 생각했습니다. 다른 좋은 의견이 있다면 제안해주세용~ 😁

2022-08-02 16:16 UTC, nailseong approved these changes
고생하셨습니다. merge 전에 프론트에 API 명세 변경되는 점 다시 리마인드시켜주면 좋겠네요.

2022-08-03 03:58 UTC, 2yujeong approved these changes

2022-08-03 04:15 UTC, OzRagwort approved these changes

2022-08-03 04:32 UTC, SuyeonChoi approved these changes
수고하셨습니당👍

2022-08-03 06:12 UTC, merged