refactor: 피드백 생성, 수정 시 바뀐 정책 적용
woowacourse-teams/2022-levellog pull request #252
Opened 2022-08-09 06:17 UTC by 2yujeong

## 구현 기능
- 인터뷰 시작 도중에만 피드백을 작성, 수정할 수 있도록 검증 로직 추가
- 피드백 삭제 API 삭제

## 논의하고 싶은 내용
- Team 도메인 검증 로직
- 시간 의존 테스트 코드를 더 깔끔하게 작성하기 위한 TimeStandard 리팩토링

Close #238

2022-08-09 12:41 UTC, nailseong requested changes, later dismissed
이브 시간 관련 테스트가 좀 까다로울 수 있었는데 잘 구현하셨네요.
컨벤션 & 리팩토링 포인트 코멘트가 대부분이라서 approve할 수 있지만 조금씩 점진적으로 리팩토링하는게 좋겠다고 생각해서 RC할께요~!! 🏃‍♀️

2022-08-09 12:41 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +        final Team team = getLevellog(levellogId).getTeam();
```suggestion
        final Team team = levellog.getTeam();
```

2022-08-09 12:41 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +        final Feedback feedback = request.getFeedback().toFeedback(member, levellog);
```suggestion
        final Feedback feedback = request.getFeedback()
            .toFeedback(member, levellog);
```

2022-08-09 12:41 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +        final Team team = getLevellog(levellogId).getTeam();
ditto

2022-08-09 12:41 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
>          feedback.validateAuthor(member, "자신이 남긴 피드백만 수정할 수 있습니다.");
`feedback.validateAuthor` 메서드가 update에서만 쓰고있는데요. 메시지를 `validateAuthor` 메서드 내부에 감추는건 어떨까요?

2022-08-09 12:41 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/FeedbackServiceTest.java
> +        void save_alreadyClosed_exceptionThrown() {
```suggestion
        @Test
        @DisplayName("인터뷰 종료 후 피드백을 작성하면 예외를 던진다.")
        void save_alreadyClosed_exceptionThrown() {
```
🙈

2022-08-09 12:41 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
> +    class ValidateBeforeStartAt {
```suggestion
    @DisplayName("validateAfterStartAt 메서드는")
    class ValidateAfterStartAt {
```

2022-08-09 12:41 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
> +                    .andDo(print());
`ControllerTest`에 있는 메서드 픽스처를 활용해서 리팩토링해주세요 😉

2022-08-09 12:41 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
>              final String token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiaWF0IjoxNjU4ODkyNDI4LCJleHAiOjE2NTg5Mjg0Mjh9.G3l0GRTBXZjqYSBRggI4h56DLrBhO1cgsI0idgmeyMQ";
클래스 변수로 추출한 token을 사용해도 괜찮겠네요
추가로 클래스 변수 token은 `static final`로 선언하는게 좋아보입니다.

2022-08-09 12:41 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
>              final String token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiaWF0IjoxNjU4ODkyNDI4LCJleHAiOjE2NTg5Mjg0Mjh9.G3l0GRTBXZjqYSBRggI4h56DLrBhO1cgsI0idgmeyMQ";
`@Nested`가 붙은 inner 클래스 이름을 파스칼 케이스로 변경해주세요. 😉

2022-08-10 04:35 UTC, OzRagwort approved these changes
수고하셨습니다 이브 잘 해주신 것 같아요 !

제가 받았던 피드백 하나 남겨봤습니다!

2022-08-10 04:35 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
> +            perform.andExpect(status().isBadRequest());
메시지에 대한 테스트도 해주시면 좋을 것 같아요!

2022-08-10 05:45 UTC, kbsat reviewed
안녕하세요 이브. 어려웠을텐데 잘 구현해주셨네요.
다른 리뷰어가 리뷰 남겨주셔서 중복되는거 지우니 리뷰가 많이 없네요.
한번 보시고 생각해보세요!

2022-08-10 05:45 UTC, kbsat commented on backend/src/docs/asciidoc/feedback.adoc
>  operation::feedback/save/exception/levellog[]
[피드백 작성 예외] 목록에 들어간 때부분의 경우 response만 반환시켜줬었는데
`존재하지 않는 레벨로그에 대해 피드백을 작성하려는 경우` <- 이것만 operation으로 남겨놓은 이유가 있으신가요?? 😛

2022-08-10 05:45 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
>          }
이브 코드 뿐만아니라 우리 모든 검증 로직을 보면 헷갈리는 부분이 좀 보여요.
`validateAfterStartAt()` -> StartAt 이후인지 검사. StartAt 이후면 통과!
`validateAlreadyClosed()` -> 이미 종료되었는지 검증. 이미 종료되었으면 예외 발생!

validate 뒤에 나오는 것만 봤을 때 AfterStartAt 에서는 StartAt 이후면은 통과이지만 AlreadyClosed면 Already Closed면 예외가 발생하네요. 뭔가 헷갈립니다. validate 뒤에는 우리가 원하는 참인 조건이 들어가야할까요? 예외 조건이 들어가야할까요? 고민되네요

2022-08-10 06:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
>          }
저는 보통 참인 조건을 생각하고 네이밍을 정하는데, 보통 참인 조건을 생각하기 이전에  validateAlreadyClosed처럼 직관적인 이름을 우선적으로 고려하다 보니 오히려 혼란을 주게 된 거 같네요🤔

2022-08-10 06:13 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
>          }
validate 뒤에는 참인 조건이 들어가야한다 한 표 던집니다.
`Objects.requireNonNull()`같은 경우 값이 null이 아니면 ok이고 null이 들어오면 예외가 터지는 것처럼요

2022-08-10 08:01 UTC, SuyeonChoi reviewed
이브 새로 변경된 피드백 정책에 맞게 API와 테스트 코드 변경하시느라 수고 많으셨습니다👏👏
다른 분들이 이미 좋은 리뷰를 남겨주셔서 저는 추가적으로 남길건 없는거 같아요ㅎㅎ
`Comment`로 남겨둘테니 RC 리뷰 해결되면 머지하면 좋을거 같습니다~!🚀

2022-08-10 08:24 UTC, 2yujeong commented on backend/src/docs/asciidoc/feedback.adoc
>  operation::feedback/save/exception/levellog[]
URL의 levellogs/{levellogId}에 존재하지 않는 ID를 넣어서 요청을 보내면 해당 예외가 터진다는 걸 같이 보여주면 좋을 거 같아서 Request까지 문서에 포함했습니다!

2022-08-10 11:10 UTC, kbsat approved these changes

2022-08-10 11:13 UTC, merged