feat: 레벨로그 생성, 수정 시 바뀐 정책 적용
woowacourse-teams/2022-levellog pull request #254
Opened 2022-08-09 08:00 UTC by kbsat

## 구현 기능
- 레벨로그 생성 시 인터뷰 시작 전에만 레벨로그 생성 가능
- 레벨로그 수정 시 인터뷰 시작 전에만 레벨로그 수정 가능
- 레벨로그 삭제 기능 제거 ( 🚨 프론트에게 알려야함 )

## 논의하고 싶은 내용
- TimeStandard에 대한 논의

## 공유하고 싶은 내용
- TimeStandard를 조금 손봤습니다.
  - 기존에 시간 의존적인 테스트는 팀을 만드는 시간을 꼭 유의해서 작성해야합니다. ( 이제 거의 모든 통합테스트가 시간에 민감해짐 )
  - TimeFixture를 만들어서 내부에 `AFTER_FAKE_NOW_TIME`, `BEFORE_FAKE_NOW_TIME` 를 만들었습니다.
  - `AFTER_FAKE_NOW_TIME` : 현재 시간의 5일 + 1시간
  - `BEFORE_FAKE_NOW_TIME` : 현재 시간의 5일 + 1시간
    - 왜 애매하게 1시간으로 함? -> 추후 스케쥴링이 적용되면 인터뷰 시작 하고 하루까지만 유효할 것 같아서
🚨 사용 : 통합테스트의 팀 생성할 때는 위 두 픽스쳐를 활용해서 StartAt을 넣어준다.

Close #237

2022-08-09 16:45 UTC, nailseong requested changes, later dismissed
고생했어요 로마
프로덕션 코드에서는 시간 관련 검증로직 제외하면 크게 불편한 부분은 없네요. 로직을 어떻게 할당할지 팀원들이랑 코드 보면서 이야기 더 나눠보면 좋을 것 같아요~ 

테스트 코드 관련해서 억까 코멘트좀 남겨봤어요. 확인 후 괜찮으면 반영해주세요. 😉

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +            willThrow(new InterviewTimeException("인터뷰 시작 전에만 레벨로그 작성이 가능합니다.")).given(levellogService)
```suggestion
            willThrow(new InterviewTimeException("인터뷰 시작 전에만 레벨로그 수정이 가능합니다.")).given(levellogService)
```

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +                    .getId();
`BEFORE_FAKE_NOW_TIME` 오호 👍

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
> +    private static final LocalDateTime TOMORROW = LocalDateTime.now().plusDays(3);
`TimeFixture`를 쓰는게 좋지 않을까요?

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/LevellogTest.java
> +        assertThatThrownBy(() -> levellog.validateTeamStartTime(TOMORROW.plusHours(3)))
```suggestion
        assertThatThrownBy(() -> levellog.validateTeamStartTime(TimeFixture.AFTER_FAKE_NOW_TIME))
```

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/fixture/TimeFixture.java
> +    public static final LocalDateTime BEFORE_FAKE_NOW_TIME = LocalDateTime.now().plusDays(5).minusHours(1);
로마 픽스처 잘 만드셨네요!!
다만 변수 이름이 명확하지 않아서 한번 고려해봤으면 좋겠어요.
1. `FAKE`라는 단어를 꼭 넣어야하나요? 저는 `FAKE`는 전부 빼도 괜찮아보여요.
2. 테스트 코드에서 사용되는 상황에 맞게 이름을 변경해보면 어떨까요?
아래의 느낌으로 변경하면 테스트 코드를 읽기 더 수월할 것 같아요. 😉

|              |현재                       |          (1시간)미래                   |       (1시간)과거                         |
|----------|--------------------------|--------------------------------------|-----------------------------------------|
|   AS-IS  |  `FAKE_NOW_TIME`  |  `AFTER_FAKE_NOW_TIME`  |  `BEFORE_FAKE_NOW_TIME`  |
|   TO-BE  |   `NOW`  |  `FUTURE`  |    `PAST`    |

---

추가로 아래와 같이 바꾸는게 좋아보이네요
```suggestion
    public static final LocalDateTime FAKE_NOW_TIME = LocalDateTime.now().plusDays(5);
    public static final LocalDateTime AFTER_FAKE_NOW_TIME = FAKE_NOW_TIME.plusHours(1);
    public static final LocalDateTime BEFORE_FAKE_NOW_TIME = FAKE_NOW_TIME.minusHours(1);
```

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +                    .save(request, authorId, teamId);
BDDMockito.willThrow로 변경 해주세요 😉
```suggestion
            willThrow(new InterviewTimeException("인터뷰 시작 전에만 레벨로그 작성이 가능합니다.")).given(levellogService)
                    .save(request, authorId, teamId);
```

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +            perform.andDo(document("levellog/save/exception-after-start"));
snippet을 폴더 단위로 생성되게 하는게 좋아보입니다.
```suggestion
            perform.andDo(document("levellog/save/exception/after-start"));
```

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>          }
```suggestion
        private ResultActions requestUpdateLevellog(final Long teamId, final Long levellogId, final Object request)
                throws Exception {
            return requestPut("/api/teams/" + teamId + "/levellogs/" + levellogId, ACCESS_TOKEN, request);
        }
```

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>          private ResultActions requestSaveLevellog(final Long teamId, final String requestContent) throws Exception {
ditto

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>              // when
`ControllerTest.requestGet` 메서드를 사용해주세요.

2022-08-09 16:45 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>              // when
`@Nested`를 붙이는 inner 클래스는 Test를 때주세요.
ex) `SaveTest` -> `Save`

2022-08-09 16:45 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        final Levellog savedLevellog = levellogRepository.save(request.toLevellog(author, team));
걍 levellog라고 하면 안되나요?
```suggestion
        final Levellog levellog = levellogRepository.save(request.toLevellog(author, team));
```

2022-08-10 01:27 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        savedLevellog.validateTeamStartTime(timeStandard.now());
예외가 터지면 롤백되겠지만 흐름상 저장 후 검증 보다는 검증 후 저장이 좋을 거 같아요!
save는 쓰기지연 없이 바로 쿼리가 나가는 걸로 아는데 예외 검증을 할 거라면 save 전에 하는 게 좋지 않을까요??

2022-08-10 01:27 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/fixture/TimeFixture.java
> +    public static final LocalDateTime BEFORE_FAKE_NOW_TIME = LocalDateTime.now().plusDays(5).minusHours(1);
픽스처 덕분에 테스트 흐름을 이해하기 더 수월해졌네요👍🏼

2022-08-10 01:27 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/fixture/TimeFixture.java
> +    public static final LocalDateTime BEFORE_FAKE_NOW_TIME = LocalDateTime.now().plusDays(5).minusHours(1);
FAKE 빼는 거 좋아요👍🏼
단순히 PAST 보다는 테스트 상의 현재 시점(NOW)과 비교했을 때 과거인 걸 알 수 있는 이름이 덜 헷갈릴 거 같아요

2022-08-10 01:27 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        levellog.updateContent(member, request.getContent(), timeStandard.now());
팀에 대한 검증 로직(validateTeamStartTime)이 save는 서비스에서 직접 호출되고 update는 레벨로그 도메인 내에서 호출되는데 한 곳으로 통일시켜주는 건 어떨까요?

2022-08-10 05:49 UTC, OzRagwort requested changes
수고하셨습니다 로마 

몇 가지 남겨봤어요!

2022-08-10 05:49 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +        @DisplayName("팀의 인터뷰가 시작된 이후에 요청하는 경우 예외를 던진다.")
```suggestion
        @DisplayName("팀의 인터뷰가 시작된 이후에 레벨로그를 저장하는 경우 예외를 던진다.")
```
와 같이 조금 더 구체적이면 좋을 것 같아요!

2022-08-10 05:49 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +        @DisplayName("팀의 인터뷰가 시작된 이후에 요청하는 경우 예외를 던진다.")
```suggestion
        @DisplayName("팀의 인터뷰가 시작된 이후에 레벨로그를 수정하는 경우 예외를 던진다.")
```
여기도요!

2022-08-10 05:49 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +        savedLevellog.validateTeamStartTime(timeStandard.now());
지금은 시간을 검증하는 부분이 Levellog안에 있어서 우선 엔티티를 만들고 난 뒤 검증을 하는 것 같아요. 

그런데 그 검증에서도 어차피 team을 사용하니 그냥 Levellog를 만들기 전 team으로 검증을 한 뒤, Levellog를 만들고 저장하는 순서면 더 좋을 것 같기도 하네요!

2022-08-10 05:49 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
> +            throw new InterviewTimeException("인터뷰 시작 전에만 레벨로그 작성이 가능합니다.", "[teamId : " + team.getId() + "]");
저장, 수정을 할 때 이 메서드로 같이 검증하다보니 메시지가 조금 어색한 것 같아요 

서비스에서 save할 때 이 메서드를 쓰지않고 team을 이용하여 바로 검증하는 식으로 바뀐다면 이 메서드를 수정에만 사용하도록 메시지를 바꿀 수 있을 것 같아요

2022-08-10 13:21 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +                    .save(request, authorId, teamId);
바꾼김에 다바꿧슴다

2022-08-10 13:23 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +            perform.andDo(document("levellog/save/exception-after-start"));
나중에 이슈 파서 한번에 바꿉시다 😊

2022-08-10 13:59 UTC, OzRagwort approved these changes
늦은 시간까지 함께한 로마 힘내세요

마감하러 갑시다 @_@

2022-08-10 14:08 UTC, nailseong approved these changes
# 😛

2022-08-11 00:16 UTC, 2yujeong approved these changes

2022-08-11 02:06 UTC, merged