feat: 인터뷰 질문 생성, 수정, 삭제 시 바뀐 정책 적용
woowacourse-teams/2022-levellog pull request #257
Opened 2022-08-09 09:42 UTC by nailseong

## 구현 기능
- 인터뷰 질문이 포함된 팀을 조회하는 `TeamRepository` 메서드
- 인터뷰 질문 **생성**, **수정**, **삭제** 시 바뀐 정책 적용

## 논의하고 싶은 내용
### 메서드 이름 추천 부탁합니다.
`InterviewQuestionService`
```java
    private void validateCanCUD(final InterviewQuestion interviewQuestion) {
        final Team team = teamRepository.findByInterviewQuestion(interviewQuestion)
                .orElseThrow(() -> new TeamNotFoundException(
                        "인터뷰 질문에 해당하는 팀이 존재하지 않습니다. [interviewQuestionId : " + interviewQuestion.getId() + "]",
                        "인터뷰 질문에 해당하는 팀이 존재하지 않습니다."));

        team.validateAlreadyClosed();
        team.validateAfterStartAt(timeStandard.now(), "인터뷰 시작 전입니다.");
    }
```
### 쿼리 수정 & 가독성 측면 의견 주세요
`TeamRepository`
```java
    @Query(value = "SELECT t "
            + "FROM Team t "
            + "INNER JOIN Levellog l ON t = l.team "
            + "INNER JOIN InterviewQuestion iq ON l = iq.levellog "
            + "WHERE iq = :interviewQuestion")
    Optional<Team> findByInterviewQuestion(@Param("interviewQuestion") final InterviewQuestion interviewQuestion);

```

Close #239

2022-08-10 02:26 UTC, 2yujeong requested changes

2022-08-10 02:26 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        final Team team = teamRepository.findByInterviewQuestion(interviewQuestion)
현재 지연로딩이 적용되어 있지 않기 때문에 인터뷰 질문을 조회하면 레벨로그, 팀까지 모두 한꺼번에 조회가 될 거 같은데 teamRepository에서 해당 쿼리를 호출해서 Team을 가져오는 이유가 있을까요??

2022-08-10 02:26 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        validateCanCUD(savedInterviewQuestion);
현재 네이밍은 CUD 관련 모든 검증 로직이 들어있어야 할 거 같은 느낌이긴 하네요🧐
저는 직관적으로 validateInterviewTime / validateInterviewInProgress 괜찮은 거 같습니다!

2022-08-10 02:26 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
> +            final InterviewQuestionDto request = InterviewQuestionDto.from("업데이트된 질문 내용");
```suggestion
```

2022-08-10 02:26 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
> +            final InterviewQuestionDto request = InterviewQuestionDto.from("업데이트된 질문 내용");
```suggestion
```

2022-08-10 02:26 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
> +abstract class RepositoryTest {
이 부분은 #258 에서 리뷰하면 될까요??👀

2022-08-10 02:26 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/InterviewQuestionControllerTest.java
> +            perform.andDo(document("interview-question/findAll/exception/levellog/not-found"));
adoc에서는 levellog-not-found로 되어있어서 스니펫을 찾아오지 못하네요
save에서 member-not-found, levellog-not-found로 생성하고 있으니 여기서도 levellog-not-found 어떨까요

2022-08-10 05:43 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        final Team team = teamRepository.findByInterviewQuestion(interviewQuestion)
객체 그래프 탐색으로 해결할 수 있었네요... InterviewQuestion에서 Team까지 탐색이 안되는 줄알고 쿼리를 만들었습니다 ㅎ;;

2022-08-10 06:16 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/domain/RepositoryTest.java
> +abstract class RepositoryTest {
넹

2022-08-10 06:40 UTC, kbsat submitted a review, later dismissed
고생하셨습니다 릭 😉
리뷰 남겨봤으니 한번 확인해주시고 수정부탁드립니다 !😁

2022-08-10 06:40 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        validateCanCUD(savedInterviewQuestion);
저도 `validateInterviewInProgress`가 좋은 것 같습니다.😊

2022-08-10 06:40 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +            throw new InterviewTimeException("이미 종료된 인터뷰입니다.", "[teamId : " + getId() + "]");
👍

2022-08-10 06:40 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackRepositoryTest.java
> +                        1));
new Team에서 개행하지 않아도 될 것 같아요!

2022-08-10 06:40 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/InterviewQuestionServiceTest.java
> +            team.close(timeStandard.now());
LocalDateTime 클래스를 직접 넣어줄 수 있기 때문에 timeStandard를 받을 필요는 없을 것 같네요 😜

2022-08-10 06:47 UTC, OzRagwort requested changes
릭 아픈와중에 수고해주셔서 감사합니다

파이팅파이팅!

2022-08-10 06:47 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        validateTeamInProgress(savedInterviewQuestion);
이 검증에서는 CUD를 할 수 있는 시점을 확인하는데, 사용하는 메서드가 다 team에 있는 것 같습니다. 

save 메서드의 두번째 줄에 있는 레벨로그에서 팀을 가져와 그 검증을 미리 한 뒤 save를 하는 식으로 해도 되지 않을까요?

메서드 이름은 `validateInProgress(levellog.getTeam())` 으로 바꾸는 식으로 하면서요

2022-08-11 07:32 UTC, 2yujeong approved these changes
많은 일을 하셨군요 릭👍🏼

2022-08-11 07:32 UTC, OzRagwort approved these changes

2022-08-11 07:37 UTC, merged