feat: 팀 수정, 삭제 시 바뀐 정책 적용
woowacourse-teams/2022-levellog pull request #260
Opened 2022-08-10 02:44 UTC by SuyeonChoi

## 구현 기능
- 사용자에게 팀에 대한 수정, 삭제 기능 구현
  - Team 삭제 Soft Delete로 구현
  - Participant 삭제 Soft Delete로 구현
- 팀의 상태를 `종료전`, `종료됨`에서 `시작전`, `진행중`, `종료됨`으로 수정한다.

## 논의하고 싶은 내용
Participant도 soft delete로 적용했기 때문에 이미 `deleted` 상태가 된 팀에 대해 또 팀 삭제 요청을 보내는 경우 ➡️ `HostNotFoundException`이 터집니다.

```java
    @Transactional
    public void deleteById(final Long teamId, final Long memberId) { // 팀 삭제 로직에서 삭제 전에
        final Team team = getTeam(teamId);
        // 호스트 검증을 함. 이미 host인 participant의 deleted = true 이므로 조회되지 않음. 호스트 없음 예외 터짐
        validateHost(memberId, team); 

        team.delete(timeStandard.now());

        final Participants participants = new Participants(participantRepository.findByTeam(team));
        participants.delete();
    }
```

## 공유하고 싶은 내용
- 생각보다 까다로운 Soft Delete..
  - [How to Implement a Soft Delete with Spring JPA](https://www.baeldung.com/spring-jpa-soft-delete)
  - [[JPA] JPA + Hibernate 기반의 개발 환경에서 Soft Delete 구현하기](https://velog.io/@nmrhtn7898/JPA-JPA-Hibernate-%EA%B8%B0%EB%B0%98%EC%9D%98-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-Soft-Delete-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0#%EA%B5%AC%ED%98%84)

## 기타
- 저희 도메인 용어가 `Interview`가 아닌 `Team`이므로 `InterviewTimeException`을 `TeamTimeException` 으로 네이밍을 변경하였습니다. 

Close #236

2022-08-10 07:49 UTC, kbsat requested changes
복잡하셨을텐데 고생해주셨네요.😊
확실히 두 이슈가 한번에 작업되다보니 수정된 코드량이 많아 리뷰하기 어렵네요 ㅜ
일단은 이정도 리뷰하고 다음에 또 리뷰하러 오겠습니다 굿봉주 🏃‍♀️ 💨

2022-08-10 07:49 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participant.java
> +    }
AllArgsConstructor를 떼고 생성자를 직접 만드신 이유가 있을까요?
추가 검증로직이 없어보이는데 동일한 동작이지 않을까 싶네용 🏃‍♀️

2022-08-10 07:49 UTC, kbsat commented on backend/src/docs/asciidoc/team.adoc
> +operation::team/update/exception/participants/duplicate[]
예외의 경우에는 response만 보여주는 것이 가독성이 좋아보여요!
물론 경우에 따라서는 request도 같이 보여줘야 이해되는 경우도 있겠구요 😄

2022-08-10 07:49 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +@Where(clause = "deleted = false")
옹 신기한 문법 👀 레미나 해주시죠

2022-08-10 07:49 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +        this.deleted = false;
수정할 때마다 isClosed 와 deleted를 false로 바꿀 이유가 있을까요? 👀

2022-08-10 07:49 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/TeamDto.java
>  public class TeamDto {
단순 TeamDto 다보니 역할이 헷갈리는 것 같아요. 보니까 생성, 수정의 역할만 하는 것 같은데 보기에는 조회 DTO 같아요. `TeamWriteDto` 같은 이름이 나을 것 같네요.

2022-08-10 07:49 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
>                  .collect(Collectors.toList());
findAll를 테스트에 delete 된 것도 추가로 조회해오는지? 를 테스트하는 코드도 적어주면 좋을 것 같아요!

2022-08-10 08:20 UTC, 2yujeong reviewed
soft delete가 생각보다 구현이 까다로웠네요😖 고생하셨어요 페퍼!!!

2022-08-10 08:20 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +    private void validateTeamAfterStartAt(final LocalDateTime presentTime) {
전체적인 메소드 순서 확인해주세용!

2022-08-10 08:20 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +        this.deleted = true;
@SQLDelete 대신 변경 감지로 팀 삭제를 구현하신 이유가 있을까용??
지금 방식도 좋지만 링크 주신 문서에서는 모두 @SQLDelete를 활용하고 있길래 다르게 하신 이유가 있는지 궁금해서 질문 남깁니다👀

2022-08-10 08:20 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
>          final Team team = getTeam(teamId);
전체 조회 findAll에서 상세 조회 findByTeamIdAndMemberId를 호출하고 있으니 findByTeamIdAndMemberId와 findAllByMemberId의 순서를 바꿔주는 게 어떨까요??
findAllByMemberId는 MyInfo 컨트롤러에서만 호출되는 메소드이기도 하고 findAll 다음에 findByTeamIdAndMemberId이 오는 게 더 코드를 읽기 수월할 거 같아요!

2022-08-10 08:20 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +            savedParticipantsMemberIds.add(participant3);
```suggestion
            // given
            final Member member1 = saveAndGetMember("릭");
            final Member member2 = saveAndGetMember("페퍼");
            final Member member3 = saveAndGetMember("이브");
            final Team team = saveAndGetTeam("잠실 제이슨조", 1, LocalDateTime.now().plusDays(6));
            final List<Long> savedParticipantsMemberIds = saveAllParticipant(team, member1, member2, member3);
```

2022-08-10 08:20 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +        @DisplayName("이미 삭제된 팀 인터뷰를 종료하려고 하면 예외가 발생한다.")
```suggestion
        @DisplayName("이미 삭제된 팀을 삭제하려고 하면 예외가 발생한다.")
```

2022-08-10 08:20 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +        @DisplayName("호스트가 아닌 사용자가 인터뷰를 종료하려고 하면 예외가 발생한다.")
```suggestion
        @DisplayName("호스트가 아닌 사용자가 팀을 삭제하려고 하면 예외가 발생한다.")
```

2022-08-10 13:43 UTC, nailseong requested changes, later dismissed
페퍼 구현하느라 고생 많았어요. Team 도메인은 늘 빡세죠...
테스트 코드에 코멘트 남겼어요. 확인 후 괜찮으면 반영해주세요 😉

2022-08-10 13:43 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +            assertTrue(actual.get().isDeleted());
Team 엔티티에 달아놓은 `@Where(clause = "deleted = false")` 어노테이션은 모든 쿼리에 `WHERE team.deleted = false`가 붙도록 하죠.
그런데 지금 테스트 코드는 **어떻게** deleted가 true인 team을 조회하는걸까요? 
`teamRepository.findById` 호출 전에 EntityManage를 주입받아서 flush & clear를 해보면 테스트가 실패하는데요. 왜 실패하는걸까요? 🤔

한번 고민해보시고 해당 테스트의 검증 코드를 변경해봅시다

2022-08-10 13:43 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +        void alreadyDeleted_Exception() {
마찬가지로 EntityManager를 주입 받고 flush & clear 코드를 삽입 후 테스트를 실행해보세요. 😉

2022-08-10 13:43 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +        validateAlreadyDeleted();
`validateAlreadyDeleted()`
팀 삭제 전에 삭제 여부를 확인해서 예외를 던질 필요가 있나요? 이미 삭제되었다면 예외를 던지지 않고 그냥 넘어가도 괜찮을것 같아요.

물론 `TeamService.deleteById` 에서 이미 삭제된 팀이라면 `getTeam`메서드 호출 시점에 `TeamNotFoundException`가 먼저 터지기 때문에 `validateAlreadyDeleted`메서드가 실제로 동작하지 않을것으로 보이네요.

2022-08-10 13:43 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +            perform.andDo(document("team/delete/exception/already-close"));
```suggestion
            perform.andDo(document("team/delete/exception/already-deleted"));
```

2022-08-10 13:43 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +                    .andDo(print());
requestDelete 메서드 사용해주세요 😉

2022-08-10 13:43 UTC, nailseong commented on backend/src/docs/asciidoc/team.adoc
> +
`팀 정보는 startAt 이후로 수정할 수 없다.` 정책도 문서화 해주세요😉

2022-08-10 13:43 UTC, nailseong commented on backend/src/docs/asciidoc/team.adoc
> +
`인터뷰 역할 조회 응답`의 표 처럼 팀 목록/상세 조회 시 status를 표로 문서화 해주면 좋겠네요!!

2022-08-10 13:43 UTC, nailseong commented on backend/src/docs/asciidoc/team.adoc
> +==== 호스트가 아닌 사용자가 인터뷰를 삭제하려는 경우
```suggestion
==== 호스트가 아닌 사용자가 팀을 삭제하려는 경우
```

2022-08-10 13:43 UTC, nailseong commented on backend/src/docs/asciidoc/team.adoc
> +==== 이미 종료된 인터뷰를 삭제하려는 경우
```suggestion
[[delete-exception-already-deleted]]
==== 이미 삭제된 팀을 삭제하려는 경우
```

2022-08-10 13:48 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
> +            assertTrue(actual.get().isDeleted());
팀에 소속된 Participant 들은 hard delete 되었는지 검증하면 좋겠네요 😉

2022-08-11 11:04 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +    private void validateTeamAfterStartAt(final LocalDateTime presentTime) {
https://github.com/woowacourse-teams/2022-levellog/issues/271

2022-08-11 12:16 UTC, OzRagwort approved these changes

2022-08-11 12:17 UTC, 2yujeong approved these changes
고생하셨어요!!!!!🧚🏻

2022-08-11 12:18 UTC, kbsat approved these changes
고생하셨습니다. approve 하겠습니다. 😋

2022-08-11 12:22 UTC, merged