refactor: 컨트롤러 테스트 리팩토링
woowacourse-teams/2022-levellog pull request #276
Opened 2022-08-12 06:56 UTC by kbsat

## 구현 기능
- 이슈 댓글 참고 부탁드립니다. https://github.com/woowacourse-teams/2022-levellog/issues/186#issuecomment-1212777527

Close #186

2022-08-12 07:49 UTC, nailseong requested changes
롬 & 펲 고생했어요. 리팩토링 포인트 코멘트로 남겼어요. 읽어보시고 괜찮으면 반영 부탁합니다.
반영하시면 테스트 코드가 많이 깔끔해질 것 같아요. 😉

2022-08-12 07:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
> +    protected ObjectMapper objectMapper;
제발 빨간줄 없애주세요.
![image](https://user-images.githubusercontent.com/68512686/184306503-b7741b85-fd64-426b-922b-fbb352fd0a8e.png)

2022-08-12 07:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
>                      .andDo(print());
ControllerTest의 requestXXX 메서드를 활용해서 when절을 리팩터링해주세요 😉
`MyInfoControllerTest` & `TeamControllerTest` 확인해주세요잉

2022-08-12 07:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
팀 생성을 왜 모킹해야하나요? 지워주세요 😉

2022-08-12 07:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
then 절의 검증 코드를 andExpectAll로 통일하는게 좋아보입니다. 😉

## AS-IS
```java
            // then
            perform.andExpect(status().isNotFound())
                    .andReturn().getResponse().getContentAsString().contains("팀이 존재하지 않습니다.");
```

## TO-BE
```java
            // then
            perform.andExpectAll(
                    status().isNotFound(),
                    jsonPath("message").value("팀이 존재하지 않습니다.")
            );
```

2022-08-12 07:49 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
예외를 던지는 메서드의 경우 예외 메시지를 변수로 추출하면 어떨까요? 😉

## AS-IS
```java
        @Test
        @DisplayName("인터뷰 시작 시간 후에 삭제하려고 하면 예외가 발생한다.")
        void delete_afterStart_exceptionThrown() throws Exception {
            // given
            final Long teamId = 1L;
            willThrow(new InterviewTimeException("인터뷰가 시작된 이후에는 삭제할 수 없습니다."))
                    .given(teamService)
                    .deleteById(teamId, 1L);

            // when
            final ResultActions perform = mockMvc.perform(delete("/api/teams/" + teamId)
                            .header(HttpHeaders.AUTHORIZATION, "Bearer " + VALID_TOKEN)
                            .contentType(MediaType.APPLICATION_JSON))
                    .andDo(print());

            // then
            perform.andExpectAll(
                    status().isBadRequest(),
                    jsonPath("message").value("인터뷰가 시작된 이후에는 삭제할 수 없습니다.")
            );

            // docs
            perform.andDo(document("team/delete/exception/after-start"));
        }
```

## TO-BE
```java
        @Test
        @DisplayName("인터뷰 시작 시간 후에 삭제하려고 하면 예외가 발생한다.")
        void delete_afterStart_exceptionThrown() throws Exception {
            // given
            final Long teamId = 1L;
            final String message = "인터뷰가 시작된 이후에는 삭제할 수 없습니다.";
            willThrow(new InterviewTimeException(message))
                    .given(teamService)
                    .deleteById(teamId, 1L);

            // when
            final ResultActions perform = requestDelete("/api/teams/" + teamId);

            // then
            perform.andExpectAll(
                    status().isBadRequest(),
                    jsonPath("message").value(message)
            );

            // docs
            perform.andDo(document("team/delete/exception/after-start"));
        }
```

2022-08-12 07:54 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
테스트 메서드 이름을 통일시켜 주세요.

## AS-IS
```java
    @Nested
    @DisplayName("findMyRole 메서드는")
    class FindMyRole {

        @Test
        @DisplayName("요청한 사용자가 소속된 팀이 아니면 예외를 던진다.")
        void notMyTeam_exceptionThrown() throws Exception {
```

## TO-BE
```java
    @Nested
    @DisplayName("findMyRole 메서드는")
    class FindMyRole {

        @Test
        @DisplayName("요청한 사용자가 소속된 팀이 아니면 예외를 던진다.")
        void findMyRole_notMyTeam_exceptionThrown() throws Exception {
```

2022-08-12 07:58 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
스니펫 생성 식별자를 통일시켜 주세요.
- 카멜케이스 vs 케밥케이스
- exception 명시 방법 등등..

`team/delete/exception/notfound` ➡️ 없는 팀을 제거하려고 하면 예외를 던진다.
`myinfo/update/nickname-invalid-length` ➡️ 닉네임에 50자를 초과한 문자열이 들어올 경우 예외를 던진다.

2022-08-13 08:16 UTC, 2yujeong reviewed
고생하셨습니다 롬펲🍀 코멘트 읽어 보시고 괜찮으면 반영해주세요~!

2022-08-13 08:16 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/ControllerTest.java
>              throws Exception {
```suggestion
    protected ResultActions requestPost(final String url, final Object request) throws Exception {
```
GET, DELETE는 개행을 안 했는데 POST, PUT에서만 하고 있네용

2022-08-13 08:16 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
> +                    request);
```suggestion
            final ResultActions perform = requestPost("/api/levellogs/" + levellogId + "/feedbacks", request);
```
다른 데서도 request 전에 개행을 하고 있네요👀

2022-08-13 08:16 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>              final ResultActions perform = requestSaveLevellog(teamId, request);
FeedbackControllerTest에서는 매번 request + url을 직접 작성해 주고 있고 
InterviewQuestionControllerTest에서는 getUrl 메소드를 추출하여 request만 호출하고 있고 
LevellogControllerTest에서는 request + url을 한꺼번에 메소드로 추출해서 활용하고 있네요 
한 가지 방식으로 통일시켜주는 건 어떨까요??

2022-08-13 08:16 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>          void titleNull_Exception(final String title) throws Exception {
여기선 테스트가 여러 번 돌아도 스니펫은 한 가지 경우에 대해서만 생성될 거 같은데 `@ParameterizedTest`가 필요할까요??
여러 번 돌면서 null / empty / 공백 모든 케이스에 대해 테스트 하는 건 `@Valid` 어노테이션에 대한 테스트 같아서 굳이 필요 없어 보여요!

2022-08-13 08:16 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +            final ParticipantIdsDto participantIds = new ParticipantIdsDto(List.of(1L, 5L));
팀을 생성할 때 hostId는 토큰으로부터 추출하고 참가자 목록에서는 hostId를 제외하고 있어용 
모킹이라 중요한 건 아니지만 mockLogin의 getPayload에서 호스트의 Id를 1L로 반환할텐데 참가자 Id 목록을 4L, 5L에서 1L, 5L로 바꾼 이유가 있을까요??

2022-08-13 08:16 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +                    .save(request, 1L);
여기서도 테스트를 봤을 때 참가자 목록에 호스트의 Id까지 포함 시키는 건지 아닌지 헷갈릴 거 같아요 
이건 팀 명에 관한 예외 테스트니까 다른 예외(참가자 중복) 유발 요소는 빼주는 게 낫지 않을까요👀

2022-08-13 12:53 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
> 스니펫 생성 식별자를 통일시켜 주세요.
> 
> * 카멜케이스 vs 케밥케이스
> * exception 명시 방법 등등..
> 
> 지금은 아래와 같이 되어있는데 중구난방인 느낌이에요. `team/delete/exception/notfound` ➡️ 없는 팀을 제거하려고 하면 예외를 던진다. `myinfo/update/nickname-invalid-length` ➡️ 닉네임에 50자를 초과한 문자열이 들어올 경우 예외를 던진다.


- 해당 이슈는 AcceptanceTest 리팩터링 이슈에서 해결하겠습니다.

2022-08-13 13:27 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
> 테스트 메서드 이름을 통일시켜 주세요.
> 
> ## AS-IS
> ```java
>     @Nested
>     @DisplayName("findMyRole 메서드는")
>     class FindMyRole {
> 
>         @Test
>         @DisplayName("요청한 사용자가 소속된 팀이 아니면 예외를 던진다.")
>         void notMyTeam_exceptionThrown() throws Exception {
> ```
> 
> ## TO-BE
> ```java
>     @Nested
>     @DisplayName("findMyRole 메서드는")
>     class FindMyRole {
> 
>         @Test
>         @DisplayName("요청한 사용자가 소속된 팀이 아니면 예외를 던진다.")
>         void findMyRole_notMyTeam_exceptionThrown() throws Exception {
> ```

ditto

2022-08-14 05:52 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>      }
andReturn() 으로는 검증이 안됩니다 😱

2022-08-14 08:10 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
>              final ResultActions perform = requestSaveLevellog(teamId, request);
LevellogControllerTest의 방식을 이용해보겠습니다.

2022-08-14 08:14 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>          void titleNull_Exception(final String title) throws Exception {
스니펫은 결국 한가지에 대해서만 생성이 되는게 맞네요.
그래도 null, empty, 공백에 대한 모든 케이스에 대해 테스트하는 건 나빠보이진 않네요 ^.^

2022-08-14 08:22 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +            final ParticipantIdsDto participantIds = new ParticipantIdsDto(List.of(1L, 5L));
다시보니 participants가 이상하게 설정되어있어서 수정했습니다.
( 기존 TeamControllerTest 코드에서 mockLogin에서 뱉는 id가 1L이 아닌 4L로 되있었어요 🥲 )

2022-08-14 08:23 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
> +                    .save(request, 1L);
ㅇㅈ합니다

2022-08-14 09:19 UTC, nailseong approved these changes
고생하셨어요오 🐋
코멘트로 리팩토링 포인트 제안드렸는데 참고만 해주세요 :)

![image](https://user-images.githubusercontent.com/68512686/184530460-934a6904-488e-467e-9048-dae2cc45e443.png)

2022-08-14 09:19 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
> +    }
요청 메서드를 한번더 추상화하셨네요! 너무 좋아요 😉

각각의 메서드는 `Save`, `Update`, `FindAll` Nested Class 에서만 사용하고 있어요.
각각의 메서드를 사용되는 Nested Class 내부에 배치하는건 어떨까요?

(FeedbackControllerTest 뿐만 아니라 다른 클래스도 마찬가지네요)

2022-08-14 09:19 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
>      class Save {
스니펫 생성 경로 `BASE_SNIPPET_PATH`를 Nested Class 내부에 상수로 추출하면 컨벤션으로 지키기 더 쉽지않을까요?

e.g.
```java
    @Nested
    @DisplayName("save 메서드는")
    class Save {

        private static final String BASE_SNIPPET_PATH = "interview-question/save/";

        ...
```

2022-08-14 13:03 UTC, 2yujeong approved these changes
굿~~~

2022-08-14 16:28 UTC, OzRagwort approved these changes
수고하셨습니다 진짜 깔끔해지고 이해하기도 쉬워졌네요 멋쪄요!! 진짜 짱

2022-08-14 16:28 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/presentation/TeamControllerTest.java
>              final TeamWriteDto request = new TeamWriteDto(title, "트랙룸", 1, LocalDateTime.now().plusDays(3),
테스트에는 문제없지만 전체적으로 `LocalDateTime.now()`대신 `TEAM_START_TIME`을 쓰자고 했던 것 같아서 여기서도 바꿔주면 어떨까요? 😄

2022-08-15 06:23 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/presentation/FeedbackControllerTest.java
>      class Save {
#300 해당 이슈는 다른 이슈에서 반영하겠습니다 🫡

2022-08-15 06:24 UTC, merged