feat: 관리자 기능 추가
woowacourse-teams/2022-levellog pull request #371
Opened 2022-08-19 16:30 UTC by nailseong

## 구현 기능
- 관리자 로그인 & 페이지
- 팀 목록 조회 & 페이지
- 팀 상태 여부에 상관없이 삭제하는 기능

Close #320

2022-08-19 17:52 UTC, 2yujeong reviewed
👍🏼

2022-08-19 17:52 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/AdminAcceptanceTest.java
> +class AdminAcceptanceTest extends AcceptanceTest {
전체 팀 목록 조회 인수 테스트는 없나용?

2022-08-19 17:52 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/authentication/support/JwtTokenProvider.java
> +            }
메소드로 추출하는 건 어떠신가요

2022-08-19 18:55 UTC, yunjin-kim approved these changes
풀스택 개발자분들! 실력이 대단하시네요👍👍👍

2022-08-19 18:55 UTC, yunjin-kim commented on backend/src/main/resources/static/src/admin.js
> +    fetch('/admin/teams/' + teamId + "?token=" + getAdminToken(), {
``으로 하는게 더 좋을 것 같아요
`/admin/teams/${teamId}` 이런 형식으로?

2022-08-19 18:55 UTC, yunjin-kim commented on backend/src/main/resources/static/src/admin.js
> +        alert(teamId + " 팀이 삭제되었습니다.");
이것도 위와 동일

2022-08-19 18:55 UTC, yunjin-kim commented on backend/src/main/resources/templates/admin-login.hbs
> +<center>
center 보다는 main 이 좋을 것 같아요
https://www.w3schools.com/tags/tag_main.asp

2022-08-19 18:55 UTC, yunjin-kim commented on backend/src/main/resources/templates/admin-teams.hbs
> +            <div>
table tag 내부에서는 div tag를 넣지 않는 것이 좋을 것 같아요.
tr td만 넣고 div는 table tag를 감싸는 방식으로 하는 것이 좋을 것 같아요

2022-08-20 03:47 UTC, 2yujeong approved these changes
굿굿굿굿굿

2022-08-20 04:06 UTC, kbsat approved these changes
👍 고생하셨습니다. 이만 Approve 하겠습니다.

2022-08-20 04:06 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
> +                        final TimeStandard timeStandard, final TeamRepository teamRepository, final ParticipantRepository participantRepository) {
```suggestion
                        final TimeStandard timeStandard, final TeamRepository teamRepository,
                         final ParticipantRepository participantRepository) {
```
라인이 초과하네요 👀

2022-08-20 04:06 UTC, kbsat commented on backend/src/main/resources/application.yml
> +      ddl-auto: none
👀

2022-08-20 04:27 UTC, SuyeonChoi reviewed
오~~ 알린 & 릭 수고하셨습니다!!
알린 자스코드좀 치시네요!?!?!?!🤪
팀 Close 기능도 관리자에게 부여하는건 어떨까요?
사용자가 인터뷰를 했는데 `Close` 하지 않은 경우에 관리자가 이를 처리할 수 있도록용😉😉

그리고 해당 작업을 로컬에서 실행하기 위한 작업들이 필요한데 이를 PR 내용에 정리해주시면 더 좋을거 같습니다.

2022-08-20 04:27 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/admin/presentation/AdminController.java
> +                .build();
```suggestion
        return ResponseEntity.noContent().build();
```
다른 컨트롤러랑 컨벤션을 맞춰볼까용?

2022-08-20 04:27 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/fixture/RestAssuredTemplate.java
> +    }
삭제 픽스쳐👍

2022-08-20 04:27 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/AdminServiceTest.java
> +    @DisplayName("deleteTeamById 메서드는")
```suggestion
    @Nested
    @DisplayName("deleteTeamById 메서드는")
```
🥺

2022-08-20 04:27 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/AdminControllerTest.java
> +class AdminControllerTest extends ControllerTest {
문서화를 안한다면 삭제해주세요!

2022-08-20 04:28 UTC, SuyeonChoi requested changes
리뷰 반영 부탁드릴게요ㅎㅎ

2022-08-20 04:33 UTC, SuyeonChoi approved these changes
전지훈련 첫번째 PR 수고하셨습니다🎉🎉🎉

2022-08-22 06:27 UTC, merged