feat: 인터뷰 질문을 검색하고 좋아요 기능을 추가
woowacourse-teams/2022-levellog pull request #436
Opened 2022-09-19 10:14 UTC by OzRagwort

## 구현 기능
- 인터뷰 질문 검색
- 좋아요 기능

## 공유하고 싶은 내용
- 몰랐는데 엔티티 이름 마지막에 sql 예약어 넣으니까 안만들어지더라(예를들면 InterviewQuestionLike)

2022-09-19 15:52 UTC, nailseong requested changes
알린 고생하셨습니다. 코멘트가 사소한 변경도 있지만 고민이 필요한 내용이 있어요.
API가 빨리 나와아 한다면 가벼운 코멘트만 반영 후 머지하는게 좋아보입니다.
(인수 테스트 given절, then절 검증은 꼭 보강해주세요 😉)

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +                                                             final Long memberId) {
해당 메서드는 DB를 많이 찌르는 메서드네요. 쿼리를 개선하는게 좋아보여요.
만약 `/api/interview-questions?size=1000000` 과 같은 요청이 들어오면 쿼리가 100만 1개가 나가니까요.

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +    private void validateAlreadyExist(final Long interviewQuestionId, final Long memberId) {
- **무엇**이 이미 존재하는지 검증하나요?
- 존재하는 보다 비즈니스를 더 잘 표현할 수 있는 표현을 쓰는게 좋아보여요. (e.g. 좋아요를 하지 않았는지 검증)

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        interviewQuestion.upLike();
인터뷰 질문에 좋아요를 누르거나/취소하면 `InterviewQuestionLikes` 테이블과 `InterviewQuestion` 테이블에 변경이 생기네요.
`InterviewQuestion` 테이블에 `likes` 컬럼을 추가한 이유가 있나요?

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +    private final InterviewQuestionLikesRepository interviewQuestionLikesRepository;
`InterviewQuestionService`와 `InterviewQuestionSearchService`를 분리하는건 어떨까요?
지금은 인터뷰 질문 CRUD, 질문 검색, 좋아요 관련 기능, 각종 검증 private 메서드가 마구 섞여 있어서 가독성이 많이 떨어진다고 생각해요. 하나의 도메인이 하나만 가질 필요는 없으니 분리하는것도 좋아보여요.

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
> +    private int likes = 0;
`InterviewQuestionSearchResultDto`는 해당 값을 likeCount로 표현하고있어요.
해당 컬럼명도 likeCount가 더 적절하다고 생각하는데 알린은 어떠신가요??

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionLikeNotFoundException.java
> +}
```suggestion
public class InterviewQuestionLikeNotFoundException extends LevellogException {

    private static final String CLIENT_MESSAGE = "인터뷰 질문을 '좋아요'하지 않았습니다.";

    public InterviewQuestionLikeNotFoundException(final DebugMessage debugMessage) {
        super(CLIENT_MESSAGE, debugMessage, HttpStatus.NOT_FOUND);
    }
}
```

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionLikesRepository.java
> +}
```suggestion
public interface InterviewQuestionLikesRepository extends JpaRepository<InterviewQuestionLikes, Long> {

    boolean existsByInterviewQuestionIdAndLikerId(Long interviewQuestionId, Long likerId);

    Optional<InterviewQuestionLikes> findByInterviewQuestionIdAndLikerId(Long interviewQuestionId, Long likerId);
}
```

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionLikeNotFoundException.java
> +}
404보다 400은 어떨까요? 
좋아요를 하지 않은 인터뷰 질문의 좋아요를 취소한다는 것은 좋아요가 존재하지 않는다는 예외보다는 잘못된 요청이라는 예외가 더 어울린다고 생각해요.

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/presentation/InterviewQuestionSearchController.java
> +            @Authentic final Long memberId) {
```suggestion
    public ResponseEntity<InterviewQuestionSearchResultsDto> searchBy(@RequestParam final String keyword,
                                                                      final Pageable pageable,
                                                                      @Authentic final Long memberId) {
```

2022-09-19 15:52 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/acceptance/InterviewQuestionSearchAcceptanceTest.java
> +        void searchBy_login() {
로그인한 경우와 로그인하지 않은 경우는 무엇을 검증하려고 하셨나요?
테스트 코드와 API 문서 모두 다른 점이 없어요. 테스트 코드 보강이 필요해 보입니당

2022-09-19 15:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionSearchResultDto.java
> +    private boolean like;
`canLike`는 어떨까요?
```suggestion
    private boolean canLike;
```

2022-09-20 07:26 UTC, kbsat approved these changes
안녕하세요 알린. 고생많으셨습니다.
릭이 대부분 리뷰달아주셨고 대면으로 이야기해드려서 따로 더 리뷰는 남기지는 않겠습니다 😊
고생하셨습니다

2022-09-20 07:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
> +    }
```suggestion
    public void like() {
        this.likes++;
    }

    public void unLike() {
        this.likes--;
    }
```
이건 어떠신가요 ? 👀

2022-09-20 07:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionLikeNotFoundException.java
> +}
동의합니다.

2022-09-20 07:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/exception/InterviewQuestionLikesAlreadyExistException.java
> +    private static final String CLIENT_MESSAGE = "인터뷰 질문에 대한 좋아요가 이미 존재합니다.";
InterviewQuestionLikeNotFoundException 에서는 `'좋아요'` 라고 표시했는데 여기서는 `좋아요` 라고 되어있네요.
하나로 통일해주세요

2022-09-20 07:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/dto/InterviewQuestionSearchResultsDto.java
> +    }
생성자를 사용하지 않고 정적 팩토리 메서드를 사용한 이유가 있나요?

2022-09-20 12:43 UTC, nailseong approved these changes
고생하셨습니다 알리스타.

2022-09-20 12:44 UTC, merged