refactor:
woowacourse-teams/2022-levellog pull request #479
Opened 2022-10-04 05:29 UTC by nailseong

## 구현 기능
- Team 제외 `Member 의존성 제거`
  - Member -> Long memberId
- `@Authentic`을 처리하던 **MethodArgumentResolver**가 Long이 아닌 `LoginStatus` 반환
  - `@PublicAPI` 와 `@Authentic`이 같이 달린 API에서 memberId가 **-1**로 설정되는 레거시 코드를 개선
  - **로그인 여부에 따라서 응답이 달라지는 쿼리**를 `LoginStatus`를 활용해서 개선 (e.g. 팀 상세 조회)

## 논의하고 싶은 내용
- DB에 외래키 제약 조건을 제거할 것인가?
- Member 의존 관계가 제거되면서 기존에 객체 그래프 탐색으로 Member에 접근하는 로직(쿼리)에 변화가 생겼어요.
  - 해당 쿼리들은 추후에 성능 측정 및 성능 개선이 필요해보여요.

## 공유하고 싶은 내용
- CUD로직은 Member의 ID만 의존하기 때문에 쉽게 의존 관계를 끊을 수 있다.
- Read로직은 Member를 포함해서 응답해야 하는 케이스가 많다.
    - NativeQuery를 날려서 해결
- NativeQuery에 반복되는 `?` 문제
    - **NamedParameterJdbcTemplate**으로 해결
- memberId를 -1로 세팅하는 문제
    - Long 타입을 대체하는 값 객체 `LoginStatus` 도입
        - `@Authentic` 어노테이션 제거를 고려해볼 필요가 생김 → AOP에서 타입으로 찾으면 될듯?
- 로그인 여부에 따라서 memberId가 달라지는 쿼리가 -1인 memberId를 조건으로 넣어서 성능 저하를 일으키는 문제
    - 매개 변수를 Long → `LoginStatus`로 변경
    - LoginStatus를 활용해서 `동적 쿼리`를 작성해서 해결 → **단, 쿼리를 이해하기 힘들어지는 문제 발생**

Close #476

2022-10-04 06:27 UTC, nailseong reviewed
코드 이해를 위해 간단하게 코멘트 남겼습니다. 리뷰에 참고해주세요.

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/aspect/LoginStatusValidator.java
> +    public void validateMemberId(final JoinPoint joinPoint) {
`application` 패기지에 포함된 메서드에 대해서 해당 aspect가 동작합니다.

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginStatusResolver.java
> +            return LoginStatus.fromNotLogin();
AS-IS
- 로그인 🙆 ➡️ 토큰에서 추출한 id
- 로그인 🙅 ➡️ -1

TO-BE
- 로그인 🙆 ➡️ LoginStatus.fromLogin(토큰에서_추출한_id)
- 로그인 🙅 ➡️ LoginStatus.fromNotLogin()

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +    private final RowMapper<FeedbackDto> feedbackRowMapper = (resultSet, rowNum) -> new FeedbackDto(
Feedback 관련 기능 중 Member 관련 데이터를 포함해서 응답해야 하는 경우가 있음.
더 이상 객체 그래프 탐색으로 member에 접근 불가능 & memberRepository에 의존하지 않기 위해서 JOIN으로 해결

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackRepository.java
> -    List<Feedback> findAllByToOrderByUpdatedAtDesc(@Param("member") Member member);
`FeedbackQueryRepository` 참고 👀

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +        final Long id = feedbackService.save(request, levellogId, loginStatus);
`@Authentic` 어노테이션에 대한 MethodArgumentResolver는 **LoginStatus**를 반환한다.
`Long` -> `LoginStatus`

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> -        final Member member = memberRepository.getMember(fromMemberId);
불필요한 `memberRepository.getMember()`는 필요하지 않음. (`LoginStatusValidator`가 한다.)

2022-10-04 06:27 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
> +                + createLikerCondition(loginStatus)
`LoginStatus`를 활용해서 비로그인일 때 불필요한 JOIN, SELECT, WHERE절 조건 등을 제거

2022-10-04 09:23 UTC, OzRagwort approved these changes
릭 78개의 파일 체인지와 +1300 -1000... 고생하셨습니다.

보다보니 모든 도메인에 레거시를 넣었다가 수정하는 등 고생의 흔적이 느껴집니다.. 👍 

핵심적인 로직은 원래 우리가 생각했던 것들을 만족한 것 같아서 approve하겠습니당

2022-10-04 09:23 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/FeedbackContentDto.java
> +    public Feedback toFeedback(final Long fromId, final Levellog levellog) {
실제 코드에서는 `request.getFeedback().toFeedback()`와 같이 사용이 되면서 Feedback을 Feedback으로 바꾼다는 식으로 읽혀서 조금 어색한 것 같아요 toFeedback()은 toEntity와 같은 식으로 네이밍하는건 어떠세요?

2022-10-04 09:23 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/aspect/LoginMemberIdChecker.java
> +            final Authentic authentic = arg.getClass().getDeclaredAnnotation(Authentic.class);
한줄에 점하나 써주세요(억까한번 해보고 싶었음)

2022-10-07 05:38 UTC, SuyeonChoi requested changes
릭 리팩터링하시느라 수고 많으셨어요!!
파일 변경이 어마어마하게 많은데,,, 릭이 커밋 메세지를 잘 작성해줘서 이를 따라가면서 리뷰해보니까 편하드라구요!👍👍 중간중간 이해하기 쉽게 코멘트도 달아주셔서 감사합니다🙇‍♀️🙇‍♀️

코멘트를 많이 달진 않았지만 수정되면 좋을거 같은 항목들이 있어 RC 보냅니다,,ㅎㅎ
조금만 더 화이팅🔥🔥🔥

++ 추가)
그리고 전 외래키 제약 조건 제거에 한표요👍
객체간에서 연관관계가 없는데 DB에서 연결하는 게 어색하고, 신경써주는게 불편할거 같습니다. 그리고 연관관계를 끊었을 때의 느낌도 맛보고 싶어요😋

2022-10-07 05:38 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +    public FeedbacksDto findAllByLevellog(final Long levellogId) {
```suggestion
    public FeedbacksDto findAllByLevellogId(final Long levellogId) {
```
아주 사소하지만 `findAllByLevellogId(levellogId)`는 어떨까요? 레벨로그 객체가아닌 id를 인자로 보내주고 있고 `JpaRepository` 메서드 네이밍 형식에 따라 일관성있게 맞추는게 좋을거 같아서용!😊

2022-10-07 05:38 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/domain/FeedbackQueryRepositoryTest.java
> +    @DisplayName("findById 메서드는 입력된 멤버가 받은 피드백을 수정일 기준 내림차순으로 조회한다.")
```suggestion
    @DisplayName("findById 메서드는 id에 해당하는 피드백을 조회한다.")
```
`findAllByTo()`테스트의 DisplayName을 복붙하셨군요!!😏

2022-10-07 05:38 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +        return jdbcTemplate.queryForObject(sql, param, feedbackRowMapper);
`queryForObject`는 1개가 아닌 결과가 반환되면 오류가 터질거 같아요. 얘도 `PreQuestionQueryRepository`처럼 Optional로 감싸서 반환해주는게 어떨까요? 🤓🤓

2022-10-07 05:38 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +    private final NamedParameterJdbcTemplate jdbcTemplate;
오오 `NamedParameterJdbcTemplate`을 활용한 이름 기반의 파라미터 설정👍👍

2022-10-07 05:38 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
> +        return ", NULL preQuestionId ";
와우 쿼리문을 이렇게도 짤 수 있군요,,,👍👍👍

2022-10-07 06:09 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +        return jdbcTemplate.queryForObject(sql, param, feedbackRowMapper);
ㅇ0ㅇ 큰일날뻔했네용

2022-10-08 05:35 UTC, kbsat requested changes
고생 많으셨습니다 릭~! 😊
file change를 보니 테스트랑 쿼리 짜시느라 엄청 고생하셨겠네요.
테스트도 잘 보충해주셨고 member의 관계를 끊어주어서 좀 더 유연한 설계가 가능해지겠네요.
몇 가지 고민사항 적어보았으니 함께 공유해봐요~ 

### 논의사항에 관련 내용

현재 DB에 외래키 제약조건을 떼는 문제에 대해서 고민중이신데, 저는 **외래키 제약조건을 떼지 않아도 된다**는 입장이에요. 이유는 크게 세가지 정도로 들 수 있을 것 같아요.

1. 외래키 제약조건을 걸었을 경우 데이터 무결성을 유지하고, Join 성능을 향상시키는 등 이점이 분명 존재한다. 현재도 제약조건에 대한 검증을 비즈니스 로직으로 많이 처리하고 있지만 만일 비즈니스 로직에 허점이 생겨 해당 제약조건이 깨질 경우를 대비한 최소한의 안전장치를 만들 수 있다. 우리가 데이터 무결성이 깨지는 경우를 대비할 만큼 비즈니스 로직이 촘촘하게 작성되었다고 보장할 수 없다.
2. 당장에 성능에 이슈가 없다. 외래키 제약조건을 걸면서 커지는 비용 중 하나는 성능 문제일 것이다. forign key 를 사용하는 지금, 데이터 무결성을 검사하는 비용이 추가되므로 분명 성능이 약간은 저하될 수 있다. ( 성능 테스트 해보지 않아서 어느정도의 성능저하인지는 가늠이 되지 않지만 ) 하지만 현재 우리 데이터 기준으로는 성능에 이슈가 크게 없다고 생각한다. 따라서 아직은 외래키를 뗄만큼의 성능이 중요해지는 시기가 아닌 것 같다는 생각이다. (  사실 이 논리대로라면 쿼리개선 등 이 때까지의 모든 작업이 의미가 없다고 생각될 수 있다. 하지만 나는 데이터 무결성을 포기하면서까지 성능을 올릴 이유가 있느냐를 중점으로 생각해서 한 발언이다. 분명 이번 미션에서 해당 내용에 대한 고민을 해보라했으니 그 고민에서는 외래키를 떼는 것이 하나의 해결책이 될 수도 있겠다. )
3. 개발 편의성 입장에서 얻을 수 있는 효용이 많을지 고민이다. 현재 외래키 제약조건을 떼었을 때 얻는 효과 중 하나는 개발 편의성(with 테스트 용이성)인 것 같다. 개발 편의성 입장에서는 정합성을 무시한채 테스트를 진행할 수 있다는 강점이 있을 것이다. 하지만 우리는 이런 불편함을 견디면서 테스트 코드작성을 상당 부분 진행했고 이런 테스트 코드 작성에 대한 불편함을 테스트 픽스쳐 등으로 약간의 개선을 해왔다고 생각한다. (그 과정에서 불편하긴 했지만 우리는 도메인 이해도가 늘었다고 생각한다.) 그래서 개인적으로는 도메인의 크기가 아직은 감내할 만한 수준이고 도메인의 설계 변경이 크게 일어날지?를 생각해보면 외래키를 뺌으로써 효용을 느끼기에는 앞으로 남은 기간으로는 부족하지않을까 싶다. ( 테스트 내에서는 외래키를 무시하도록 설정하고 하면 외래키의 효용을 느껴볼 수 있을지도? ) 

조금 보수적인 입장을 달았네요 ㅎㅎ.. 저도 실무에서 외래키 제약조건을 뗀다는 이야기를 들었을 때 솔깃하긴 했습니다. 그래서 한동안은 떼고 싶다는 생각이 가득했어요. 그런데 생각하다보니 실무에서 그렇게 한다해도 우리 프로젝트의 성격이나 그 필요성을 내부에서 절실히 느낀 이후에 변경하는 것이 옳다는 생각이 들었네요. 아직 저는 데이터 무결성을 포기할만큼 성능, 개발편의성이 얻어낼 필요성을 절실하게 느끼지는 못한 것 같아요. 그래서 현행을 유지하는 것이 좋다는 생각이에요!

2022-10-08 05:35 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
> +    private final RowMapper<SimpleInterviewQuestionDto> interviewQuestionRowMapper = (resultSet, rowNum) -> new SimpleInterviewQuestionDto(
여기 한칸 개행 추가부탁드립니다. 😊

2022-10-08 05:35 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +    List<Levellog> findAllByAuthor(@Param("authorId") Long authorId);
```suggestion
    List<Levellog> findAllByAuthorId(@Param("authorId") Long authorId);
```
가 더 명료한 것 같군요 👀

2022-10-08 05:35 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/application/FeedbackService.java
> +                .toEntity(loginStatus.getMemberId(), levellog);
FeedbackWriteDto 인 request에게 메세지를 전달해서 받는건 어떨까요?
디미터법칙을 만족해봅시다.
`request.toEntity(loginStatus.getMemberId(), levellog)`

2022-10-08 05:35 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
> +        this.toId = toId;
입력받는 toId는 levellog의 작성자와 같습니다.
toId와 levellog를 각각 받지 않고 `levellog.getAuthorId()` 해도 될 것 같다는 생각이 드네요.

2022-10-08 05:35 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/levellog/application/LevellogService.java
> +    public Long save(final LevellogWriteDto request, @Authentic LoginStatus loginStatus, final Long teamId) {
```suggestion
    public Long save(final LevellogWriteDto request, @Authentic final LoginStatus loginStatus, final Long teamId) {
```
LoginStatus에 final이 빠진거 같아요! 👀

2022-10-08 05:35 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
> +    public List<AllParticipantDto> findAllByTeamId(final Long teamId, final LoginStatus loginStatus) {
`LoginStatus` 객체는 컨트롤러에서 받아서 서비스에서 이용되는 것으로 보여요. 이 때 Domain으로 넘길 때는 값을 꺼내서 넘기고 위와 같이 레포지토리 단으로 넘길 때는 `LoginStatus` 객체 그대로 넘기고 있네요.
`LoginStatus`를 전달해주거나 값을 직접 꺼내서 전달해주는 것에 대한 기준이 존재할까요?🤔

2022-10-08 13:13 UTC, 2yujeong requested changes
FC가 많은데 정말 고생 많으셨습니다👍🏼
그래도 이전 회의에서 리팩토링 방향을 어느정도 공유한 후에 리뷰하는 거라서 크게 복잡하지 않았어요
동적 쿼리 부분도 지금은 이해하는 데 있어서 크게 어렵지 않았네용

> - DB에 외래키 제약 조건을 제거할 것인가?

만약 엔티티간 직접적인 연관관계를 끊어준다면 그에 맞게 DB 외래키 제약조건도 끊어줌으로써 객체와 테이블 사이의 간극을 줄이는 것도 좋겠다는 생각이 들어요. 그에 따른 개발의 편의성을 이번에 직접 느껴보는 것도 좋 것 같네요.
물론 외래키 제약 조건을 제거한다면 혹시나 비즈니스 로직으로 막지 못한 무결성이 깨지는 상황이 발생했을 때 DB단에서도 이걸 막아주지 못하기 때문에 추후 큰 사고로 이어질 수 있을 것 같아요. 이러한 가능성까지 생각한다면 시스템의 안정성이 우선되어야 하기 때문에, 모든 팀원들의 의견이 일치하지 않는다면 혹시 모를 위험을 감수하고 현재 시점에서 외래키 제약조건을 제거할 필요는 없다고 생각합니다.

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                     @Authentic final LoginStatus loginStatus) {
ArgumentResolver로부터 토큰 Payload를 받아올 때 쓰는 어노테이션과 서비스에서 AOP로 인증된 멤버를 받을 때 쓰는 어노테이션을 구분하는 건 어떨까요? 컨트롤러에서 쓰는 `@Athentic`은 토큰 인증만 되고 유효한 멤버 인증은 되지 않으니 다른 이름의 어노테이션을 정의해도 좋을 것 같습니다.

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        return new InterviewQuestionsDto(interviewQuestions);
인터뷰 질문의 작성자가 중복되는 Row 때문에 DTO 변환 로직이 단순하지 않았네요🥲 고생하셨습니다👍🏼 Collectors.groupingBy는 잘 몰랐는데 기존의 distinct된 작성자 수만큼 반복문을 돌던 로직보다 더 이해하기 수월해진 것 같아요.
\+ 기존에는 변환 로직을 InterviewQuestionsDto의 정적 팩토리 메소드에서 수행했는데 Service로 옮기신 이유가 있을까요?

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestion.java
> +        final boolean isNotAuthor = !getAuthorId().equals(memberId);
getter 대신 authorId를 직접 사용해도 될 것 같아요

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
> +    public Levellog(final Long authorId, final Team team, final String content) {
public으로 변경하신 이유가 있나요?

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
> +        final Member member = memberRepository.getMember(loginStatus.getMemberId());
여기서는 AOP를 거치지 않고 토큰 인증 된 memberId만 받아도 괜찮을 것 같은데 어떤가용

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +                    resultSet.getObject("fromId", Long.class),
resultSet.getObject("fromId", Long.class)와
resultSet.getLong("fromId")의 차이가 있을까요?

2022-10-08 13:13 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
>      }
이번 PR에 관련된 내용은 아니지만, 특정 엔티티에만 별다른 로직이 없는 정적 팩토리 메소드가 선언되어 있는데 정적 팩토리 메소드 작성 기준을 다시 얘기해봐도 좋을 것 같아요.

2022-10-11 02:24 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/Feedback.java
> +        this.toId = toId;
좋습니다 :)

2022-10-11 02:32 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
> +    public List<AllParticipantDto> findAllByTeamId(final Long teamId, final LoginStatus loginStatus) {
기본적인 기조는 `domain layer에는 값을 꺼내서 전달한다` 입니다.
다만 간간히 LoginStatus 객체가 그대로 domain layer에 넘어오는 경우가 있어요. 이 경우는 QueryRepository에서 LoginStatus의 `isLogin` 메서드를 활용해서 동적 쿼리를 생성하기 때문이에요. 굳이 domain layer에 LoginStatus를 그대로 넘길 필요가 없다고 생각해서 위와 같은 기준을 잡았어요. 

지금 생각해 보니까 domain layer에도 Long타입이 아닌 LoginStatus타입으로 값이 넘어온다면 **LoginStatus에서 꺼내는 memberId는 요청을 날린 유저의 id**라는 것이 명확할 수 있다는 생각도 드네요. 매개 변수로 Long 타입이 여러개가 들어오는 메서드라면 특히 좋을 것 같아요.
이 부분에 대해서 지금의 기준을 유지하는게 좋을까요? 아니면 일단 LoginStatus를 넘기고 사용하는 쪽에서 memberId를 꺼내서 사용하는게 좋을까요? 🧐🧐🧐🧐

2022-10-11 02:46 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/application/InterviewQuestionService.java
> +        return new InterviewQuestionsDto(interviewQuestions);
기존에는 Entity를 매개 변수로 변환 로직이 돌아서 코드가 복잡하지 않았지만, 리팩토링 이후에는 QueryRepository의 ResultDto를 활용해서 변환 로직이 돌게 되었어요. 그리고 전 후 코드를 살펴보면 리팩토링 이후 로직이 훨씬 복잡하다는 생각이 들었고 이 로직을 dto에 숨기는 것보다는 Service에 로직을 배치하는게 한 눈에 이해하기 쉽겠다고 판단했어요. :)

2022-10-11 02:52 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
> +    public Levellog(final Long authorId, final Team team, final String content) {
감사합니다 ㅎㅅㅎ

2022-10-11 04:28 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/member/application/MemberService.java
> +        final Member member = memberRepository.getMember(loginStatus.getMemberId());
좋습니당

2022-10-11 04:29 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                     @Authentic final LoginStatus loginStatus) {
좋은 의견이네요!! 다만 어노테이션 이름을 지어야하는데..................

2022-10-11 05:39 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/domain/FeedbackQueryRepository.java
> +                    resultSet.getObject("fromId", Long.class),
`getLong`은 반환 타입이 `long`이에요. 민약 쿼리로 조회한 결과가 null인 경우 getLong의 반환값이 `null이 아닌 0`이 되죠.
따라서 응답이 null일 수 있는 경우 `getObject(xxx, Long.class)`를 사용해야 null을 할당할 수 있어요.
(쿼리 결과 null이 나올 수 없는 경우에는 getLong으로 변경하겠습니당 😉)

2022-10-11 05:41 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/Levellog.java
>      }
동의합니다. 개발이 잔행되면서 뒤죽박죽된 느낌이들어요 ㅜ.,ㅜ

2022-10-11 07:04 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                     @Authentic final LoginStatus loginStatus) {
@SuyeonChoi @OzRagwort @kbsat @2yujeong 
## 어노테이션 이름짓기 공모전 열겠습니다.

2022-10-11 07:08 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                     @Authentic final LoginStatus loginStatus) {
- `@AuthenticMember` 🌟🌟🌟🌟
- `@AuthenticExistsMember`🌟🌟🌟
- `@ExistsMember`🌟🌟
- `@ValidateMember`🌟

2022-10-11 07:08 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                     @Authentic final LoginStatus loginStatus) {
컨트롤러 : `@TokenValid` `@MemberToken` `@TokenMember` 
서비스 : `@Athentic`

2022-10-11 07:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/feedback/presentation/FeedbackController.java
> +                                     @Authentic final LoginStatus loginStatus) {
`@LoginMember`

2022-10-11 08:30 UTC, nailseong reviewed
@SuyeonChoi @kbsat @2yujeong 
피드백 주신 부분 반영해봤어요~!!! 확인 부탁합니당 :)

2022-10-11 08:30 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/support/Verified.java
> +public @interface Verified {
써비스에는 `@Verified` 어노테이션을 달아주세요. :)

2022-10-11 08:30 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/support/Extracted.java
> +public @interface Extracted {
컨트롤러에는 `@Extracted` 어노테이션을 달아주세요. :)

2022-10-11 08:36 UTC, 2yujeong approved these changes
피드백 반영 굿,, 고생하셨습니다~!

2022-10-11 08:58 UTC, SuyeonChoi approved these changes
릭 수고하셨어요🙇‍♀️🙇‍♀️
제가 리뷰 드린거 반영은 확인했으니 빠른 머지를 위해 approve 하세요,,,!
이슈 해결하시느라 수고하셨습니다👍👍

2022-10-11 11:24 UTC, kbsat approved these changes
잘 고쳐주셨군요 ...
이만 어프루브하겠습니다. 고생하셨습니다.

2022-10-11 11:26 UTC, merged