refactor: dto 네이밍 수정
woowacourse-teams/2022-levellog pull request #480
Opened 2022-10-04 07:03 UTC by OzRagwort

## 구현 기능
- JDBC로 조회 후 응답용 DTO는 `XXXQueryResult` 로 통일 (dto.query 패키지에 위치시킨다.)
- 일반적인 요청 dto → XXXRequest
- 일반적인 응답 dto → XXXResponse
- 요청, 응답 dto는 분리한다.

## 논의하고 싶은 내용
- 팀 목록 조회 DTO가 TeamListDto -> TeamListResponses로 변경되었는데 네이밍 어떠신가요?
- `InterviewQuestionSearchResultDto`와 `InterviewQuestionSearchResultsDto`가 `InterviewQuestionSearchResultResponse`와 `InterviewQuestionSearchResultResponses`로 수정 되었는데 네이밍 어떠신가요?
- 그 외엔 거의 대부분 단순 네이밍 변경(dto -> XXXRequest, XXXResponse, XXXQueryResult) 입니다

2022-10-04 09:21 UTC, nailseong reviewed
고생했습니다 알린!!
Team쪽 dto이름은 팀원들과 논의를 해보면 좋을것 같아요.

2022-10-04 09:21 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/feedback/dto/response/FeedbackResponses.java
> +public class FeedbackResponses {
`XXXResponses` -> `XXXListResponses`는 어떨까요?
XXXResponses와 XXXResponse가 구분이 잘 안되더라구요.

2022-10-04 09:21 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllParticipantQueryResult.java
> +public class AllParticipantQueryResult {
1. Participant보다는 Team이라는 키워드를 넣기
2. 해당  DTO를 생성하는 쿼리의 목적이 묻어나는 이름 (e.g. 팀 상세 조회, 팀 목록 조회 등)

2022-10-04 09:21 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllSimpleParticipantQueryResult.java
> +public class AllSimpleParticipantQueryResult {
`All`, `Simple`과 같은 키워드는 의미를 잘 나타내지 못한다고 생각해요.

2022-10-04 09:21 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/dto/response/TeamListResponses.java
> +public class TeamListResponses {
TeamListResponse가 더 좋아보여욤

2022-10-07 06:13 UTC, SuyeonChoi approved these changes
알린 DTO 네이밍 변경하느라 수고하셨습니다👏👏
네이밍에 대해서 전 크게 신경쓰이는 부분은 없는거 같아요~! 대부분 무난무난하게 이해됐습니다👍
논의하고 싶은 내용에 대해 제 생각을 남기고 갑니당,,
제가 혹시라도 잘못이해한 부분이 있다면 말해주세요! 바로 디엠 주셔도 됩니다,,

그리구 저도 나름 빠르게 리뷰한거 같은데.... 햄버거.. 줄서봅니다^.^🍔키키
우리에게 머지데이(D-5)도 있으니까,,,다른 리뷰어들도 리뷰해줄때까지 조금만 더 기다려보죵,,
그럼 화이팅화이팅화이팅!!!🔊🔊🔊

---
알린이 논의하고 싶다는 내용에 대한 제 생각입니다😊😊
> 목록 조회에 사용되는 DTO의 네이밍 규칙을 XXXResponses에서 XXXListResponses처럼 통일 시켜봄 - 릭 피드백 반영
피드백 목록조회 dto가 FeedbackResponses에서 FeedbackListResponses처럼 된다는 의미
기존 팀 목록 조회도 TeamListDto처럼 사용중이었음
팀 목록 조회 DTO가 TeamListDto -> TeamListResponses로 변경되었는데 네이밍 어떠신가요?
InterviewQuestionSearchResultDto와 InterviewQuestionSearchResultsDto가 InterviewQuestionSearchResponse와 InterviewQuestionSearchResponses로 수정 되었는데 네이밍 어떠신가요?

혹시 `XXXListResponse`는 어떨까요? List에서 복수를 표현해줬는데 Response에서 또다시 `s`로 나타내는게 불필요하다고 느껴지네요,,! 기존에도 `TeamListDtos`가 아닌 `TeamListDto`를 사용했던 것처럼요!

2022-10-07 06:13 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +public class AllTeamDetailQueryResults {
목록을 반환하는 query DTO의 클래스들도 `s`가 아닌 `AllTeamDetailListQueryResult`로 구분하는건 어떨까요?

2022-10-08 13:34 UTC, 2yujeong requested changes
고생하셨습니다 알린👍🏼
> - `InterviewQuestionSearchResultDto`와 `InterviewQuestionSearchResultsDto`가 `InterviewQuestionSearchResponse`와 `InterviewQuestionSearchResponses`로 수정 되었는데 네이밍 어떠신가요?

이 부분은 PR 코멘트 내용 참고해서 RC 하나 남겼는데 확인해주세용

\+ 저도 페퍼 의견처럼 `XXXListResponse`가 좋을 것 같습니다!

2022-10-08 13:34 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
> +    public List<InterviewQuestionSearchResponse> searchByKeyword(final String keyword, final Long memberId,
JDBC 조회 결과로 바로 응답하기 위한 DTO니까 `XXXQueryResult`여야 하지 않을까요?

2022-10-08 17:31 UTC, kbsat requested changes
![image](https://user-images.githubusercontent.com/52696169/194719538-b8cab510-febd-4628-9b2f-7487ef1419d5.png)

안녕하세요 알린. 리뷰어 로마입니다. 🧚‍♀️
고생해주셨네요 덕분에 QueryService가 깔끔해졌어요! 
로직 범벅이었는데 다 적절하게 객체 안으로 넣어주었기 때문이겠죠? ㅋㅋ 문득 위 짤이 생각나서 가져와봤습니다
Team 도메인 내에 service와 queryResult 위주로 리뷰 달아보았으니 보시고 반영해주세요~😊

### 논의 사항

> 목록 조회에 사용되는 DTO의 네이밍 규칙을 XXXResponses에서 XXXListResponses처럼 통일 시켜봄 
> 팀 목록 조회 DTO가 TeamListDto -> TeamListResponses로 변경되었는데 네이밍 어떠신가요?
- 저는 좋은 것 같은데욤 
- 다른 리뷰어분들이 `TeamListResponses` -> `TeamListResponse` 로 바꾸자는 의견 달아주셨는데 기존 `TeamListResponse` 는 뭘로 바꿔야할까요?? 🥹

> InterviewQuestionSearchResultDto와 InterviewQuestionSearchResultsDto가 InterviewQuestionSearchResponse와 InterviewQuestionSearchResponses로 수정 되었는데 네이밍 어떠신가요?
- 이건 이브의 의견과 동일합니다.

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +        return TeamResponse.from(id, title, place, startAt, teamProfileUrl, interviewerNumber, isClosed);
AllTeamDetailQueryResult에서 다양한 DTO로 변경되는군요!

한가지 의문은 `TeamResponse` 로 전환하는만 정적팩토리를 쓰네요. 생성자와 정적 팩토리를 결정하는 알린만의 기준이 있을까요?

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +                .getTeamStatus(nowTime);
getAllTeamListQueryResult로 한번 전환하는 것보다는 TeamStatus를 바로 얻어내는 것이 디미터 법칙도 만족하고 객체에 메세지를 잘 전달하는 것 같아보이네요.
현재 맞춤 쿼리를 제작하고 있으니 `AllTeamDetailQueryResult` -> `AllTeamListQueryResult`로 갈 경우도 많이 없을 것 같으니 `getAllTeamListQueryResult`가 필요해보이진 않네요. 🧚‍♀️

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +    public TeamDetailResponse toResponses(final Long memberId, final LocalDateTime time) {
toResponse
```suggestion
    public TeamDetailResponse toResponse(final Long memberId, final LocalDateTime time) {
```
TeamDetailResponse 타입으로 변하니 위 네이밍이 적절해보이네요. 😊

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
> +        return TeamListResponses.from(results, timeStandard.now());
TeamQueryService에서 `findAll`,`findAllByMemberId`는 정적 팩토리 메서드를 활용하여 Responses를 만들고 있고 `findByTeamIdAndMemberId` 에서는 일급컬렉션에 메세지를 보내서 만들어내고 있네요.

알린이 설정한 기준이 무엇인지 궁금하고 어떤 쪽으로 맞춰야 좋을지 한번 고민해보면 좋을 것 같아요 😊

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +    List<AllTeamDetailQueryResult> results;
```suggestion
    private final List<AllTeamDetailQueryResult> results;
```
👀

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +                .collect(Collectors.toList());
```suggestion
        return filteredParticipants.stream()
                .filter(it -> it.getSimpleParticipant().isParticipant())
                .map(AllTeamDetailQueryResult::getParticipantResponse)
                .collect(Collectors.toList());
```
😊
개인적으로는 SimpleParticipant로 한번 거쳐가지 않아도 될 것 같네요.

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +        return new SimpleParticipants(participants);
```suggestion
        return filteredParticipants.stream()
                .map(AllTeamDetailQueryResult::getSimpleParticipant)
                .collect(Collectors.collectingAndThen(Collectors.toList(), SimpleParticipants::new));
```
이것도 가능하겠군요 😊

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +    private SimpleParticipants toSimpleParticipants(final List<AllTeamDetailQueryResult> filteredParticipants) {
개인적으로는 filteredParticipants라는 말이 납득이 잘 안되네요. results를 그냥 전달해주는건데요~ 
그리고 필드로 존재하는데 꼭 인자로 받아야하나요?👀
이 외에 다른 메서드에서도 필드값을 주입해서 사용하고 있네요😢

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +    public AllTeamListQueryResult getAllTeamListQueryResult() {
여기 있는 메서드 모두 protected로 해도 될거같은데요 👀

2022-10-08 17:31 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
> +        final List<AllTeamDetailQueryResult> actual = teamQueryRepository.findAllByTeamId(team.getId(), roma.getId());
이 테스트 어떻게 돌아가죠?
그리고 해당 테스트 메서드의 네임과 DislayName이 잘못 설정된 것 같아요.

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +    public AllTeamDetailQueryResult(final Long id, final String title, final String place, final LocalDateTime startAt,
builder 한번 써보시겠어요? 😉

2022-10-08 17:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/response/TeamListResponses.java
> +        return new TeamListResponses(responses);
위에처럼 collectingAndThen 사용해보십숑 😊

2022-10-11 07:12 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +        return TeamResponse.from(id, title, place, startAt, teamProfileUrl, interviewerNumber, isClosed);
기존 코드가 그렇게 되어있어서 사용했습니다.

생성자를 사용하는 경우
- 기본 생성자
- 필수적인 필드가 모두 파라미터로 들어간 생성자

정적 팩토리 메서드를 사용하는 경우
- 다른 도메인이 파라미터로 오는 경우
- 그 외 대부분의 경우

하지만 지금은 기존에 `TeamResponse`가 `@AllArgsConstructor(access = AccessLevel.PRIVATE)`로 생성자가 private이었습니다. 

따라서 정적 팩토리 메서드를 사용하였습니다.

2022-10-11 07:13 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +                .getTeamStatus(nowTime);
맞아요 꼭 필요하지 않는 부분입니다

필드가 너무 많고 다른 dto와 중복으로 사용되는 것들이 너무 많아보여서 저렇게 수정해봤는데 다시 잘 리팩해봐야겠네요

2022-10-11 07:28 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamQueryService.java
> +        return TeamListResponses.from(results, timeStandard.now());
일급 컬렉션에서 메시지를 보내는 방식으로 하나의 방식으로 통일해보겠습니다. 

---

## 고민했던 것

제 기준은

1. 코드가 깔끔해지고 역할이나 책임의 분리가 되는 방식. 큰 상관 없다면 기존의 있는 방식
2. 일급 컬렉션에서 결과를 만들어 반환하는 방식
3. 정적 팩토리 메서드를 이용하는 방식
인 것 같습니다. 

Service에 로직을 이동시키면서 리팩하는 방식은 아래 2가지 방식이 있을 것 같습니다. 
1. TeamListResponse에서 정적 팩터리 메서드를 사용하자. 
2. List<AllTeamListQueryResult>를 묶는 일급 컬렉션을 만들어 toTeamListResponse() 메서드를 만들자.

팀 목록 조회에서는 1번, 팀 상세 조회에서는 2번 방식을 이용한 것 같아서 2번 방식으로 통일하도록 수정하겠습니다.

2022-10-11 07:40 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +        return new SimpleParticipants(participants);
collectingAndThen 감사합니다 배웠네유

2022-10-11 07:42 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +    private SimpleParticipants toSimpleParticipants(final List<AllTeamDetailQueryResult> filteredParticipants) {
기존의 코드를 그대로 옮기면서 생각하지 못했네요 찾아주셔서 감사합니다

2022-10-11 07:50 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +    public AllTeamListQueryResult getAllTeamListQueryResult() {
그렇군요 다 같은 패키지 내에서 사용되고 있어서 protected로 수정해주었습니다.

2022-10-11 07:53 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/TeamQueryRepositoryTest.java
> +        final List<AllTeamDetailQueryResult> actual = teamQueryRepository.findAllByTeamId(team.getId(), roma.getId());
해당 dto가 필드를 DTO로 가지도록 수정하면서 이렇게 수정했는데 다시 바꾸면서 then 절을 다시 수정했습니다.

2022-10-11 08:08 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +        return TeamResponse.from(id, title, place, startAt, teamProfileUrl, interviewerNumber, isClosed);
젤 위에 적어주신 `다른 리뷰어분들이 TeamListResponses -> TeamListResponse 로 바꾸자는 의견 달아주셨는데 기존 TeamListResponse 는 뭘로 바꿔야할까요?? 🥹`는 

팀목록조회
`TeamListResponse`가 `List<TeamListDetailResponse>`를 가지는 식으로 수정했습니다.

2022-10-11 08:14 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +public class AllTeamDetailQueryResults {
전체적으로 싹 바꿨습니다!

2022-10-11 08:34 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/interviewquestion/domain/InterviewQuestionQueryRepository.java
> +    public List<InterviewQuestionSearchResponse> searchByKeyword(final String keyword, final Long memberId,
그렇게 수정했습니다. !

2022-10-11 08:36 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResult.java
> +    public AllTeamDetailQueryResult(final Long id, final String title, final String place, final LocalDateTime startAt,
개인적으로 lombok의 builder가 편하긴 한데 선호하지 않는 편이기는 해요 롬복에 의존된 코드가 되는 것 같아서요 ㅠㅠ.. 

전체적으로 이런 경우 다 빌더를 사용한다면 여기에서도 사용해도 되겠지만 아니라면 다같이 사용하지 않는건 어떨까요?

2022-10-11 12:58 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailQueryResults.java
> +public class AllTeamDetailQueryResults {
`s`를 추가하도록 수정했습니다

2022-10-11 12:58 UTC, kbsat requested changes
안녕하세요 알린, 리뷰어 로마입니다.
잘 고쳐주셨네요. 소소한 부분 리뷰해보았으니 반영부탁드려요 😊

2022-10-11 12:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamDetailListQueryResult.java
>          final TeamStatus status = toTeamStatus(result, time);
29번째 라인 : 
toTeamStatus 보다 result.getTeamStatus(time); 이 더 명료한 것 같아요

2022-10-11 12:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/query/AllTeamListQueryResult.java
> +
한칸만 뛰십쇼 🤔

2022-10-11 12:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/dto/AllParticipantDto.java
> -package com.woowacourse.levellog.team.dto;
이것도 지워주세요~! 😊

2022-10-11 12:58 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/prequestion/dto/request/PreQuestionWriteRequest.java
> +        return new PreQuestionWriteRequest(content);
정적 팩토리 메서드를 사용하는 이유가 없는 것 같아요 ㅜ.ㅜ

2022-10-11 13:04 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/prequestion/dto/request/PreQuestionWriteRequest.java
> +        return new PreQuestionWriteRequest(content);
제말이요...

2022-10-11 13:38 UTC, 2yujeong approved these changes
👍🏼

2022-10-11 13:39 UTC, kbsat approved these changes
알린 고생하셨습니다 🙉🥹🙉 
이만 머지하겠습니다.

2022-10-11 13:39 UTC, merged