refactor: mariaDB를 연결했을 때 깨지는 쿼리 및 테스트 수정
woowacourse-teams/2022-levellog pull request #485
Opened 2022-10-07 10:03 UTC by SuyeonChoi

어떻게 돌아가는지 확인하고 다시 적겠소이...
## 구현 기능
- 구현한 기능을 적습니다.

## 논의하고 싶은 내용
- 논의할 내용을 적습니다.

## 공유하고 싶은 내용
- 학습한 내용, 공유할 내용 등을 적습니다.
- 위키에 작성했다면 링크 첨부, 없는 경우 삭제

## 기타
- 기타 추가할 내용이 있다면 추가합니다.
- 없는 경우 삭제

Close #이슈번호

2022-10-07 12:28 UTC, nailseong requested changes
페퍼 부상 투혼중에 고생하셨습니다!!!! 덕분에 MariaDB 환경에서 문제를 찾을 수 있었네요 👍👍

테스트 환경은 h2를 현상유지가 좋겠네요. 인터뷰 질문 검색 전문 검색 쿼리는 member 외래키 제거 후 다른 쿼리들 인덱스 걸 때 함께 튜닝하는게 좋겠어요.

추가로 작업 중에 변경한 설정 파일들이 있는데 해당 파일들 확인해보시고 롤백해주세용

2022-10-07 12:28 UTC, nailseong commented on backend/docker/db/config/my.cnf
> -default-character-set           = utf8mb4
요녀석은 도커 띄울 때 mysql 설정 파일이라 지우면 안됩니당...ㅠㅡㅠ
혹시 이 파일 때문에 문제가 생기나요?

2022-10-07 12:28 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/common/domain/BaseEntity.java
> +    @Column(columnDefinition = "DATETIME(6)", updatable = false, nullable = false)
`columnDefinition = "DATETIME(6)"`  <- 설명이 있으면 좋겠어염

2022-10-07 12:28 UTC, nailseong commented on backend/src/main/resources/application-test.yml
> +    show-sql: true
옵션을 켜면 테스트 환경에서 sql 2번씩 찍혀요 👀

2022-10-07 12:28 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
> +                + "t.id teamId, t.title, t.place, t.start_at, t.profile_url teamProfileUrl, t.is_closed, t.created_at, "
팀 생성 시간을 조회하는 이유가있나요?

2022-10-08 17:45 UTC, kbsat requested changes
안녕하세요 봉주, 리뷰어 로마입니다. DB때문에 고생많이 하셨네요 🧚‍♀️ 미지의 영역인데 잘 탐구해주시고 단점도 잘 뽑아주셨네요 💯
아쉬운 점은 많지는 않지만 수정된 사항들이 보이는데 어떤 수정인지 알기 어렵다는 점이에요.
이슈도 없고 어떻게 깨지는지 코드만으로는 알기 힘들어서 수정 내용에 대해서는 코멘트를 달기 어렵네요~ 🥲
어떻게 깨지는지에 대한 설명을 코멘트로 추가로 달아주시면 해당 부분 리뷰해드릴게요! 🙂


### 논의 내용
> 본래 가장 중요한 목적이었던 전문 검색(FULLTEXT SEARCH)을 사용하지 않을 예정인데 과연 DB 변경을 해야하는가
- 전문검색 사용을 하지 않으니 저는 안해도 된다는 생각이네요~! 테스트가 느려지고 드문드문 깨지는 테스트가 존재하는 것으로 보아 사이드 이펙트가 커보이네요 🤧
>TestContainer를 사용하며 느낀점
- 페퍼 덕분에 TestContainer라는 걸 처음 알게되었네요 👍 도커를 띄우는 비용이 있기 때문에 과연 젠킨스 서버에서도 버틸지도 의문이 들고 깃헙 CI에서도 TestContainer로 테스트가 가능할지 궁금하긴 하네요~

2022-10-11 10:18 UTC, SuyeonChoi commented on backend/docker/db/config/my.cnf
> -default-character-set           = utf8mb4
헉,, 다시 추가했습니다! 하지만 해당 파일때문에 나는 오류는 아닙니다ㅠㅠ 추가해도 테스트 몇개가 깨지는건 똑같네요🥲🥲

2022-10-11 10:22 UTC, OzRagwort approved these changes
수고하셨습니다 페퍼

지금 있는 리뷰들만 수정되면 머지해도 될 것 같습니다

2022-10-11 11:06 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/common/domain/BaseEntity.java
> +    @Column(columnDefinition = "DATETIME(6)", updatable = false, nullable = false)
H2 데이터베이스를 이용하였을 때는 DATETIME이 기본적으로 시간이 소수점 6자리까지 찍혀서 저희가 millisecond 단위로 테스트를 할 수 있었습니다.
[h2 공식문서](http://www.h2database.com/html/datatypes.html?highlight=date&search=date#timestamp_type)
<img width="627" alt="스크린샷 2022-10-11 오후 7 30 50" src="https://user-images.githubusercontent.com/28749734/195067361-b96eee7a-f27d-4477-ab39-5146ae88d771.png">

하지만 실제 MariaDB를 연결하면 소수점에 해당되는 초단위까지 찍히지 않습니다. 실제 데이터베이스의 데이터를 확인해봤을 때도 아래와 같이 저장되어있음을 알 수 있습니다. 
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/28749734/195071034-cb843825-c461-404f-9812-1fa0ddcf6b09.png">

따라서 millisecond 단위까지 저장하기 위해 해당 속성을 추가하였습니다!

[추가 참고 자료](https://stackoverflow.com/questions/50310477/java-8-time-api-with-hibernate-using-millisecond-nanosecond-precision)

2022-10-11 11:06 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamQueryRepository.java
> +                + "t.id teamId, t.title, t.place, t.start_at, t.profile_url teamProfileUrl, t.is_closed, t.created_at, "
이부분은 테스트하면서 이것저것 찍어본 뒤 복구를 안한거 같습니다🥲
꼼꼼한 리뷰 감사해요 릭!

2022-10-12 08:59 UTC, nailseong approved these changes
고생하셨습니다 페퍼!! 👍

2022-10-12 12:21 UTC, kbsat approved these changes
구두로 설명 들었으니 이만 Approve 하겠습니다.

2022-10-12 12:22 UTC, merged