refactor: Team, Participant 간 일대다 양방향 연관관계 추가 및 리팩토링
woowacourse-teams/2022-levellog pull request #489
Opened 2022-10-07 13:15 UTC by kbsat

## 구현 기능
- #482 참고

## 논의하고 싶은 내용
- participant -> team 으로의 연관관계는 양방향 매핑을 이용했기 때문에 존재하지만 연관관계를 이용한 작업을 하지 않기 때문에 해당 연관관계를 간접 참조로 변경하는 방식을 고민중입니다
- team을 teamDetail과 participants로 나누고 생성 시 teamDetail과 participantsIngredient를 필요로합니다. 각 객체의 책임이 적절한지  논의하고 싶습니다. 개선안이 있으시면 이야기해주시길 바랍니다.

## 공유하고 싶은 내용
- TeamWriteDto에 존재하는 데이터를 각 `TeamDetail` 과 `ParticipantsIngredient` 로 전환하는 로직이 추가되었습니다.
- 이제 앞으로의 참가자 관련 로직은 team을 통해 처리하게 됩니다.
- ParticipantRepository를 제거했습니다.
- Team을 가져올때는 fetch join을 활용해 participants까지 가져와야 participants 관련 검증을 진행할 수 있습니다. ( feedback, interviewQuestion 등에서 fetch join을 통해 가져오도록 하고 있음 )

Close #482

2022-10-09 08:11 UTC, nailseong reviewed
안녕하세요 이브&로마 😝
TeamService 다이어트를 열심히 시켰네요!!!!!! 역시 천재개발자가 페어를 하니까 코드 퀄리티도 훌륭하군요.
몇몇 디테일한 부분에서 놓친 부분이 있으신것 같아서 코멘트 남겨봤어요. 괜찮다면 반영 부탁합니당 구조적으로 크게 아쉬운 부분은 없어서 `comment`로 남기겠습니당 고생하셨어요 (햄버거 2개 잘 먹겠습니다 😋🍔🍔)

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
> +                timeStandard.now());
```suggestion
        teamRepository.getTeamWithParticipants(teamId)
                .update(request.toTeamDetail(), request.toParticipantsIngredient(memberId), timeStandard.now());
```

`validateHostAuthorization`와 같은 검증 메서드를 도메인 객체 내부로 감추는건 어딸까요?
해당 검증 메서드는 도메인 객체의 상태를 변경하기 전에 호출하는 메서드이므로 해당 메서드를 application 계층에 노출할 필요는 없어보여요.

+) **`close`, `delete`역시 마찬가지네요** :)

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
> +    default Team getTeamWithParticipants(final Long teamId) {
기존의 getTeam 메서드는 삭제하고 해당 메서드를 `getTeam`으로 이름을 변경하는건 어떨까요?
Team과 Particiapnts는 생명 주기가 같으니까 getTeam으로 조회한 team에 Participant 역시 로딩되어있다고 생각할 가능성이 높다고 생각해요. 만약 기존의 `getTeam`으로 조회한 team에 Participants가 필요한 메서드를 호출하면 NPE가 터질태니까요. 이런 가능성을 없애려면 Participants를 로딩하지 않는 기존의 getTeam은 삭제하고 해당 메서드를 getTeam으로 변경하는게 좋아보여요.

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
> +                request.toParticipantsIngredient(hostId));
```suggestion
        final Team team = request.toEntity(host.getProfileUrl());
```
dto에게 team 엔티티의 생성 책임을 위임하는건 어떨까요?

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +                    .append("teamId", getId()));
```suggestion
        status(presentTime)
            .validateInProgress(getId(), presentTime));
```
이런식으로 `TeamStatus`에게 책임을 위임할 수 있겠네요.

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamDetail.java
> +    }
```suggestion
    public TeamDetail(final String title, final String place, final LocalDateTime startAt, final String profileUrl,
                      final int interviewerNumber) {
        setTitle(title);
        setPlace(place);
        setStartAt(startAt);
        setProfileUrl(profileUrl);
        setInterviewerNumber(interviewerNumber);
    }
    
    // 1번
    private void setTitle(final String title) {
        if (title == null || title.isBlank()) {
            throw new InvalidFieldException("팀 이름이 null 또는 공백입니다.", DebugMessage.init()
                    .append("title", title));
        }
        if (title.length() > DEFAULT_STRING_SIZE) {
            throw new InvalidFieldException("팀 이름은 " + DEFAULT_STRING_SIZE + " 이하여야 합니다.", DebugMessage.init()
                    .append("title 길이", title.length()));
        }
        this.title = title;
    }
    
    // 2번
    private void setTitle(final String title) {
        validateTitle(title);
        this.title = title;
    }
    
    // 생략
```

setter를 private으로 위와 같이 활용할 수 있는데요. 어떤가요?

**AS-IS** 
`생성자` -> `validate()` -> 각 필드의 `validateXXX` -> `this.XXX`

**TO-BE**
`생성자` -> 각 필드의 `setXXX()` -> `this.XXX`

이런 식으로 추상화 단계를 1단계 생략할 수 있는 장점이 있어요.

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
```suggestion
    public static Participants of(final Team team, final ParticipantsIngredient ingredient) {
    ingredient.toParticipants(team);
    }
```
`ParticipantsIngredient`에게 생성의 책임을 위임하는건 어떨까요?

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +    private List<Long> toParticipantIds() {
해당 메서드를 사용하는 메서드의 로직을 개선하면 해당 메서드를 제거할 수 있겠네요.
굳이 Participant를 Long으로 변경해서 로직을 수행할 필요가 없어보여요.

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
>      }
마찬가지로 `Participant`에게 메시지를 던져볼까요?

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/ParticipantsIngredient.java
> +public class ParticipantsIngredient {
혹시 이름으로 고민이었다면 `ParticipantsFactory`는 어떨까요?
`Participants`의 생성 책임을 해당 객체로 위임한다면 XXXFactory라는 이름이 더 적절하다고 생각해요.
`Participants`의 생성 책임을 해당 객체로 위임하면 생성자와 Participants를 생성하는 factory 메서드를 제외한 모든 메서드가 private으로 잠길태니까요 :)

2022-10-09 08:11 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +        return findLevellogWithTeamAndParticipantsById(levellogId)
Team과 Participant의 life cycle이 동일하다는 관점에서 `getLevellogWithTeamById`는 어떤가요?

2022-10-09 08:11 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsIngredientTest.java
> +package com.woowacourse.levellog.team.domain;
```suggestion
package com.woowacourse.levellog.domain;
```
domain 패키지 하위로 옮겨주세요 ^0^

2022-10-10 10:09 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
> +                timeStandard.now());
동의합니다. 고쳐볼게요. 😀

2022-10-12 07:11 UTC, OzRagwort requested changes, later dismissed
안녕하세요 로브(로마이브)

고민이 많으셨을 것 같은 PR이네요 하지만 역시 잘 해주셨습니다. 

억까 조금 해봤습니다 파이팅입니당

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
> +            // FIXME : Participants 변경 테스트 추가
혹시 의도하고 남겨둔 FIXME 일까요?

PR 메시지에라도 적어주시면 좋을 것 같아요

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
> +        team.close(presentTime.plusDays(1));
어드민이기 때문에 무조건 팀을 지우기 위해 1일을 더해주는 것 같다고 생각이 되는데요 그렇다면 주석으로 설명을 해두는건 어떨까요? 

그리고 이름이 presentTime이기 때문에 지금 시간에 1을 더하는 이유가 뭐지? 라는 생각이 들 수도 있을 것 같아요!

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
>      public boolean isContains(final Long memberId) {
values 안에 member id 가 있는지 아닌지를 확인하는 메서드로 보이는데 그럼 isContains 보다 hasMemberId 와 같은 닉네임은 어떨까요?

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +    Optional<Levellog> findLevellogWithTeamAndParticipantsById(@Param("levellogId") Long levellogId);
중요한건아닌데 파라미터 이름이랑 `@Param("XXX")`의 이름이 같으면 `@Param`을 제외해도 된다고 들었어요

빼라는건 아니고 그런게 있다고 들어서 알려드려유

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +    Optional<Levellog> findLevellogWithTeamAndParticipantsById(@Param("levellogId") Long levellogId);
여기 뿐 아니라 여기 저기에서 join을 한다는 이유로 이름이 XXXWithXXX의 형식인데요

결국 Levellog를 반환하고 파라미터로도 Team이나 Participants를 받지 않아서 꼭 WithXXX를 달아줘야하나 싶어요

메서드 명에 꼭 넣어야 할까요?

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
> +        final Team team = teamRepository.getTeamWithParticipants(teamId);
이런 곳에서도 메서드 명에 With가 필요한가 싶어요

2022-10-12 07:11 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +@Embeddable
신기하네요 👍

2022-10-12 09:08 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/domain/TeamTest.java
> +            // FIXME : Participants 변경 테스트 추가
FIXME 처리하고 지웠습니다!

2022-10-12 09:12 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/admin/application/AdminService.java
> +        team.close(presentTime.plusDays(1));
주석 추가했습니다!

2022-10-12 09:28 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +    Optional<Levellog> findLevellogWithTeamAndParticipantsById(@Param("levellogId") Long levellogId);
👍🏼

2022-10-12 09:31 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/team/domain/ParticipantsIngredientTest.java
> +package com.woowacourse.levellog.team.domain;
수정했습니다😄

2022-10-12 10:47 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/application/TeamService.java
> +                timeStandard.now());
고민점
- validateHostAuthorization를 위한 memberId를 ParticipantsIngredient에서 getter로 얻어와야 함
- AdminService.closeTeam 때문에 팀의 hostId를 구해오는 로직이 추가되어야 함

2022-10-12 10:48 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +                    .append("teamId", getId()));
고민점
- 로그 메시지를 남기기 위해 TeamStatus 검증 메소드에서 teamId 또는 presentTime을 매개변수로 받아야 함

2022-10-12 10:50 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
> +    private List<Long> toParticipantIds() {
고민점
- concatSameTwice를 위해 List\<Participant\>에서 해당 멤버의 인덱스를 구하는 로직을 어떻게 해결해야 할지 모르겠음
`final int from = participantIds.indexOf(memberId) + 1;`

2022-10-13 06:07 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamRepository.java
> +    default Team getTeamWithParticipants(final Long teamId) {
고민해본 결과, 비즈니스 로직에서 `Team` 홀로 이용되는 경우는 없는 것을 확인했습니다.
- 팀 수정 시 팀 내용 뿐만 아니라 무조건 Participants와 함께 수정된다.
- levellog, feedback, interviewQuestion, PreQuestion은 모두 팀에 참가자인지 확인하는 로직이 존재한다. 이는 Team이 아닌 Participants가 필요한 로직인데 이를 위해서는 항상 `fetch join`해서 가져와야한다.
릭이 말하는 것처럼 함께 동작하는 하나의 도메인이라고 생각이 되므로 이를 항상 함께 가져오도록 해도 좋을 것 같네요.

2022-10-13 06:24 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Team.java
> +                    .append("teamId", getId()));
`TeamStatus` 에 해당 로직 외에 Ready 검증 로직도 넣어주었습니다. TeamStatus가 관리할 책임이 맞다고 생각이 드네요.

2022-10-13 06:28 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
ParticipantsFactory에게 위임했습니다!

2022-10-13 06:31 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/TeamDetail.java
> +    }
해당 변경 사항은 논의가 더 필요한 것 같은데~ 논의가 끝나면 다른 이슈로 파서 진행을 해도 좋을 것 같습니다 😊

2022-10-13 06:38 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/team/domain/ParticipantsIngredient.java
> +public class ParticipantsIngredient {
ParticipantsFactory 적용했습니다😀
https://github.com/woowacourse-teams/2022-levellog/pull/489/commits/774e79603c26a9714b819822c4f13e7de50c9b65

2022-10-13 06:57 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +    Optional<Levellog> findLevellogWithTeamAndParticipantsById(@Param("levellogId") Long levellogId);
저희는 특정 정보를 fetch join해서 함께 가져온다는 것을 명료하게 표현해주는 것이 좋지 않을까 싶네요 😊

2022-10-13 07:00 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/levellog/domain/LevellogRepository.java
> +        return findLevellogWithTeamAndParticipantsById(levellogId)
현재 Participants 정보 없이 Team 정보만 필요한 로직(LevellogService의 update())이 존재하기 때문에 지연 로딩이 필요해요. 레벨로그-팀만 가져오는 경우와 레벨로그-팀-Participants를 모두 가져오는 경우를 구분하기 위해선 getLevellogWithTeamAndParticipantsById를 유지해야 할 것 같습니다🙂

2022-10-13 08:26 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/team/domain/Participants.java
>      public boolean isContains(final Long memberId) {
둘다 큰 차이는 없어 보여서 isContains로 해도 될까요 ? 🥹

2022-10-13 09:32 UTC, SuyeonChoi approved these changes
구두로 리뷰 했습니다~! 수고하셨어요 로마&이브👍

2022-10-13 13:14 UTC, nailseong approved these changes
고생하셨습니다!!!!!!

2022-10-13 13:15 UTC, merged