feat: `InterviewTeams` 페이지의 웹 접근성을 개선
woowacourse-teams/2022-levellog pull request #503
Opened 2022-10-14 13:06 UTC by jihyeok-um

## 구현 기능

### 전반적인 내용

- `InterviewTeams` 페이지 (Home)의 웹 접근성 개선
- 스크린리더가 적절하게 요소를 읽어주도록 개선
- `tab`, `shift+tab` 을 통해 상호작용할 수 있는 모든 요소에 접근 가능 

---

### 헤더

- [x] 레벨로그 로고
  - [x] "메인 페이지로 이동 링크" 
- [x] 로그인/유저정보 드롭다운
  - [x] 로그인
    - [x] "로그인 버튼"
  - [x] 유저정보 드롭다운
    - [x] "로그인한 사용자 정보 드롭다운 버튼" 
    - [x] "로그아웃 버튼"
 ---

### 컨텐트 헤더 (인터뷰 팀 필터링)

- [x] 필터링 버튼
  - [x] "팀 필터링 버튼 목록 3개 항목 포함" (혹은 2개)
  - [x] "`진행중인 인터뷰` 필터 버튼 목록 항목"
  - [x] "`종료된 인터뷰` 필터 버튼 목록 항목"
  - [x] "`나의 인터뷰` 필터 버튼 목록 항목"
  - [x] 적용 중인 필터링 버튼에 `aria-disabled` 적용
  - [x] nav, ul, li 태그로 교체

---

### 팀 카드 링크 요소

- [x] 호스트 이미지
- [x] 팀 이름
- [x] 인터뷰 장소
- [x] 인터뷰 날짜/시간
- [x] 참여자 목록

---

### 팀 추가 버튼

- [x] "`팀 추가하기` 버튼 팀 추가페이지로 이동 링크"

---

### 푸터

- [x] "저작권 페이지로 이동 링크"

---

## 논의하고 싶은 내용

- `ul, li` 태그를 사용할 일이 많았습니다. 기존에 `~Container` 나 `~Box` 로 사용하던 `styledComponent`의 네이밍을 좀 더 명확하게 하고싶어 `~Ul`, `~Li` 로 바꾸어 봤습니다. 어떤 방식이 더 좋은지 의견 공유해주세요!

-  InterviewTeams 페이지 (이제는 Home 페이지)의 접근성을 개선한다고 말씀을 드렸는데 아무래도 "인터뷰 질문 검색" 부분을 건드리는건 이슈 침범이 되지 않을까 싶어 건들이지 않았습니다!

- "팀 호스트 이미지" 라고 팀 대표 이미지를 읽게 되는데 (host에 대한 정보가 팀 전체 조회에 없음) 반복문으로 host 정보를 구해서 접근성을 높이는게 좋을 지 아니면 이대로 유지할 지가 고민이네요!

- 모바일 환경에서 테스트해보고 싶으나 테스트서버에 배포를 하고 할 수 있을 것 같아 chrome 스크린 리더로만 테스트했습니다!

Close #497

2022-10-16 14:41 UTC, yunjin-kim requested changes

2022-10-16 14:41 UTC, yunjin-kim commented on frontend/src/pages/teams/TeamFilterButtons.tsx
> +    <S.FilterUl>
기존에  `~Container` 나 `~Box` 라고 명명한 이유는 어떠한 내용을 감싸주는 컴포넌트를 지칭하기 위해 컨벤션으로 통일한 것인데 이를 `styledComponent`의 네이밍을 더 명획하게 하기 위해 어기는 것은 좋지 않은 것 같습니다. 그리고 `styledComponent`의 네이밍을 명확하게 하기 위함인데 `styledComponent`에서 Tag 네임을 붙여주는 것이 명시적인지는 잘 모르겠습니다.

2022-10-16 14:41 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +  ...props
Image 컴포넌트에 `...props` 와 인덱스 시그니처를 다는 것은 타입스크립트 관점에서 좋지 않은 방법입니다. 이렇게 된다면 Image 컴포넌트에는 어떠한 props가 내려온다 하더라도 타입 에러가 생기지 않습니다.

2022-10-16 14:41 UTC, yunjin-kim commented on frontend/src/components/header/Profile.tsx
> +          ? '로그인한 사용자 정보 드롭다운'
`로그인한 사용자 정보 드롭다운` 보다 조금 더 명시적으로 네이밍하면 좋을 것 같습니다.

2022-10-16 14:41 UTC, yunjin-kim commented on frontend/src/components/teams/InterviewTeam.tsx
> +            alt={`팀 호스트 이미지`}
흠..반복문으로 구할 수 있는 데이터인지는 잘 모르겠네요.
저는 그냥 `aria hidden`하는 것이 좋을 것 같습니다.

2022-10-17 05:06 UTC, jihyeok-um commented on frontend/src/components/teams/InterviewTeam.tsx
> +            alt={`팀 호스트 이미지`}
따로 응답에서 호스트에 대한 정보를 받지 않는만큼 `aria-hidden` 로 수정하겠습니다~

2022-10-17 06:17 UTC, jihyeok-um commented on frontend/src/pages/teams/TeamFilterButtons.tsx
> +    <S.FilterUl>
대부분의 `~Container`나 `~Box` 가 div 태그를 사용하길래 특수케이스인 것 같아 한 번 제안해봤습니다!
기존의 컨벤션과 동일하게 바꾸도록 하겠습니다~

2022-10-17 06:34 UTC, jihyeok-um commented on frontend/src/components/@commons/Image.tsx
> +  ...props
```tsx
export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string | undefined;
  sizes: ImageSizeType;
  boxShadow?: boolean;
  borderRadius?: boolean;
  githubAvatarSize?: number;
}
```

와 같이 변경했습니다. `Button` 컴포넌트도 동일한 방식을 사용하고 있는데,
이는 이후 같이 타입스크립트 리팩터링 일정이 있기 때문에 그대로 두었습니다!

2022-10-17 06:38 UTC, jihyeok-um commented on frontend/src/components/header/Profile.tsx
> +          ? '로그인한 사용자 정보 드롭다운'
```tsx
aria-label={
  loginUserProfileUrl.includes('avatars.githubusercontent')
    ? `${loginUserNickname}의 정보 드롭다운`
    : '로그인'
}
```

으로 변경하여 사용자에 대한 정보까지 주도록 변경해봤습니다!

2022-10-17 06:42 UTC, jihyeok-um commented on frontend/src/components/@commons/Image.tsx
> +  ...props
[refactor: ImageProps 타입 좁히기](https://github.com/woowacourse-teams/2022-levellog/pull/503/commits/73dcccb96c6d2494dd414df3452774296144b1f2)

@jihyeok-um

2022-10-17 06:42 UTC, jihyeok-um commented on frontend/src/components/header/Profile.tsx
> +          ? '로그인한 사용자 정보 드롭다운'
[refactor: 드롭다운 버튼의 정보에 사용자 nickname 추가](https://github.com/woowacourse-teams/2022-levellog/pull/503/commits/be819586932e3e41a8b3b28e3b56e9a781939436)

2022-10-17 06:42 UTC, jihyeok-um commented on frontend/src/pages/teams/TeamFilterButtons.tsx
> +    <S.FilterUl>
[refactor: 제안한 네이밍 다시 컨벤션대로 수정](https://github.com/woowacourse-teams/2022-levellog/pull/503/commits/c9f5cc82f4c30e525991e47818db46314aadc089)

2022-10-17 07:11 UTC, yunjin-kim approved these changes
👍

2022-10-17 07:50 UTC, jihyeok-um commented
이제 merge하셔도 될 것 같습니다

2022-10-17 07:54 UTC, yunjin-kim requested changes

2022-10-17 07:54 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
React.ImgHTMLAttributes<HTMLImageElement> 를 extends 하면 불필요한 타입까지 허용해주는 것이 아닌가요?

2022-10-17 07:54 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
alt?: string | undefined;
        crossOrigin?: "anonymous" | "use-credentials" | "" | undefined;
        decoding?: "async" | "auto" | "sync" | undefined;
        height?: number | string | undefined;
        loading?: "eager" | "lazy" | undefined;
        referrerPolicy?: HTMLAttributeReferrerPolicy | undefined;
        sizes?: string | undefined;
        src?: string | undefined;
        srcSet?: string | undefined;
        useMap?: string | undefined;
        width?: number | string | undefined;
        
너무 많은뎅;;;

2022-10-17 07:56 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
React.ImgHTMLAttributes<HTMLImageElement>에 게다가 sizes라는 속성도 있는데 저희 image props에도 sizes가 있어서 힘들 것 같네요..

2022-10-17 10:41 UTC, jihyeok-um commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
제 생각에는 `img` 태그를 사용한 `Image` 컴포넌트에는 `React.ImgHTMLAttributes`에 있는 속성들까지
들어올 수 있다고 기대하는게 좋지 않을까? 라는 생각이 들어요. 
그렇지 않으면 필요할 때마다 img 태그에서 사용할 수 있는 속성들을 일일이 추가해줘야하니까요!

```tsx
export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement>
```

를 사용해서 기본 속성을 모두 허용하고, `ImageProps`에는 저희가 만든 커스텀 속성의 타입을 정의해주는건 어떨까요?
+ 커스텀 속성의 `sizes`가 기본 속성과 네이밍이 겹친다면 커스텀 속성의 네이밍을 바꿔주는게 맞는 것 같습니다.

2022-10-17 10:55 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
흠..Image 컴포넌트에 `src` 속성과 `alt` 속성이 옵셔널로 들어오는 것이 맞나 생각이 드네요.
지금은 이전에 이미지에 alt을 붙여주지 않아서 임시로 옵셔널을 해놓는 것이라고 생각합니다.
저 많은 속성 중에 어떠한 속성을 쓸지도 잘 모르겠어요.

2022-10-17 11:29 UTC, jihyeok-um commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
Image 태그에서는 어떠한 속성을 쓸지 잘 모를 수도 있습니다.
당장 `@commons/Button` 컴포넌트에서는 사용할 때도 있고 사용하지 않을 때도 있는 
조건부 props들이 매우 많습니다. `disabled`, `color`, `type` 등등인데요.

```tsx
interface ButtonProps {
  children: string;
  type?: string;
  disabled?: boolean;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
  color?: string;
  [props: string]: any; 
}
```
 `React.ButtonHTMLAttributes<HTMLButtonElement>` 을 상속받아서 사용하면 더 간결하게 타입을 작성할 수 있지 않을까요?
`alt`, `src` 와 같이 옵셔널로 주지 않는게 맞는 속성들은

```tsx
// 설명을 위한 예시 코드입니다. 
export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
}
```
과 같이 필수 속성으로 바꿔주면 해결될 일이라고 생각합니다!

2022-10-17 12:00 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
React.ButtonHTMLAttributes<HTMLButtonElement> 을 상속받아서 사용하면 더 간결하게 타입을 작성할 수 있지 않을까요?
alt, src 와 같이 옵셔널로 주지 않는게 맞는 속성들은

// 설명을 위한 예시 코드입니다. 
export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
}
과 같이 필수 속성으로 바꿔주면 해결될 일이라고 생각합니다!

그러면 그냥 alt props 타입 추가하면 되는 일 아닌가요? `src`와 `alt`를 강제하기 위해  `  src: string;
  alt: string;` 이렇게 한다면 현재 Image 컴포넌트의 props 타입은 어떠한 타입도 `React.ImgHTMLAttributes<HTMLImageElement>`이 타입에 속하지 않습니다.

저희 서비스가 이미지에 대해 많은 처리가 필요한 서비스도 아닌데 `React.ImgHTMLAttributes<HTMLImageElement>`를 통해 타입을 확장하는지 이해가 잘 되지 않습니다.

2022-10-17 12:09 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
그리고 아무리 공통 컴포넌트라도 인덱스 시그니처를 통해 타입을 정의하는 것은 좋지 않은 방법인 것 같네요. 
공통 컴포넌트에 들어오는 props가 타입에 다 정의되어 있어야 제 3자(ex 새로 들어온 개발자)가 봐도 알기 쉽지 않을까요? 
간결하게 타입을 작성하는 것도 좋지만 간결한 것보다는 명확한 것이 저는 더 좋은 것 같네요.

2022-10-17 12:23 UTC, jihyeok-um commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
> 그리고 아무리 공통 컴포넌트라도 인덱스 시그니처를 통해 타입을 정의하는 것은 좋지 않은 방법인 것 같네요.

여기는 아주 동의합니다. 바로 리뷰를 반영하기도 했고요.

> 공통 컴포넌트에 들어오는 props가 타입에 다 정의되어 있어야 제 3자(ex 새로 들어온 개발자)가 봐도 알기 쉽지 않을까요?

여기는 제 생각으로 의도에 따라 다를 것 같긴합니다.

img 태그를 사용하듯이 `Image` 컴포넌트를 사용하기를 의도 했다면, img 태그에 있는 모든 속성을 사용할 수 있도록 타입을 작성하는 게 좋을 것 같고, `Image` 컴포넌트를 저희가 짜놓은 틀 안에서만 사용하기를 바란다면 결의 방식이 좋을 것 같습니다!

다시 생각해보면 저희의 `Image` 컴포넌트는 짜놓은 틀 안에서만 사용하기를 바라는 게 맞으므로
```tsx
interface ImageProps {
  src: string | undefined;
  alt: string; // 당장은 "alt?: string"
  sizes: ImageSizeType;
  boxShadow?: boolean;
  borderRadius?: boolean;
  githubAvatarSize?: number;
}
```
으로 결정하는게 좋을 것 같습니다!

2022-10-17 12:28 UTC, yunjin-kim commented on frontend/src/components/@commons/Image.tsx
> +export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
>img 태그를 사용하듯이 Image 컴포넌트를 사용하기를 의도 했다면, img 태그에 있는 모든 속성을 사용할 수 있도록 타입을 작성하는 게 좋을 것 같고,

2022-10-17 16:14 UTC, yunjin-kim approved these changes

2022-10-17 16:14 UTC, merged