chore: Webpack에 포함된 타입스크립트 빌드 환경을 재검토
woowacourse-teams/2022-levellog pull request #505
Opened 2022-10-16 11:04 UTC by jihyeok-um

## 구현 기능
`Webpack` 에 포함된 타입스크립트 빌드 환경을 `local` , `dev` , `prod` 로 나누어 재검토해봤습니다.

###  **local**
  - 기존의 `babel-loader`를 `esbuild-loader`로 교체
  - `babel-loader` 와만 제대로 호환되는 `react-refresh-webpack-plugin` 관련 종속성 제거 

###  **dev, prod** 
 - 기존의 `ts-loader`를 유지하되, 타입체크와 컴파일을 분리함
 - `fork-ts-checker-webpack-plugin` 사용

## 공유하고 싶은 내용

기존의 레벨로그 빌드 환경의 의도에서 벗어나지 않도록 타입스크립트 컴파일 환경을 한 번 설정해봤습니다.
- **local**: VSCode의 ts-server가 정적으로 타입 검사를 해주고, dev, prod에서 타입 검사를 할 예정이니, 개발 환경에서는 타입 검사를 포기하고 더 빠르게 빌드할 수 있는 `babel-loader` 를 사용한다.
- **dev, prod**: 테스트, 운영서버에 배포하기 위한 빌드 파일을 생성해야함으로 `ts-loader`를 사용해 다소 느리더라도 타입 검사를 한다.

### local (esbuild-loader vs babel-loader)

![제목 없는 디자인](https://user-images.githubusercontent.com/75592315/196031101-1a41a071-b45a-4810-81cc-e98d0acbe874.png)

`esbuild-loader` 와 기존 설정 `babel-loader + react-refresh-webpack-plugin` 의 초기 빌드 속도 비교입니다. 
타입 체크까지 시행하는 `ts-loader + fork-ts-checker-webpack-plugin` 조합보다도 약간 빠른 babel-loader를 사용할 필요가 없을 것 같아서 교체했습니다. 재빌드 상황에서도 `esbuild-loader`가 두 배 이상 빠른 빌드 속도를 보여줬습니다.
  
### dev, prod

![제목 없는 디자인 (1)](https://user-images.githubusercontent.com/75592315/196031539-432805f9-6b5b-4368-a089-f84f74c655cd.png)

기존의 `ts-loader` 에서 타입 검사를 별도의 프로세스로 옮겨서 진행하게 해주는 `fork-ts-checker-webpack-plugin` 을 추가한 빌드 시간을 비교해보았습니다. dev, prod를 따로 비교하지 않고 prod만 비교해보았습니다. 

## 기타

<img width="220" alt="스크린샷 2022-10-16 오후 7 29 35" src="https://user-images.githubusercontent.com/75592315/196030445-923aec7a-022d-4bdd-8d5f-c3b179191fd4.png">

react-refresh-webpack-plugin 문서를 읽어보니
dev-server의 `hot: true` 와 함께 사용하라고 나와있던데 저희 webpack에서는 설정이 안 되어 있더라고요?
혹시 특별한 이유가 있었나요??

devDependencies에 있어야 할 친구들이 dependencies에 있길래 옮겨줬습니다~

Close #504

2022-10-16 14:59 UTC, yunjin-kim requested changes
- TypeScript `월요일`
    - 빌드 환경에 포함된 TypeScript 컴파일 전략을 구체적이고 상세하게 포함하고 발표한다.
        - TypeScript를 컴파일하는 Loader 대상과 선정한 이유, 지표를 포함한다.
        - 빌드 환경 개선 경험이 있다면 해당 내용도 포함한다.
    - 타입 정리

이 주제에 대해서 월요일에 같이 토론하는 걸로 알고 있었는데 pr 보내시니 좀 당황스럽네요;;;

일단 제 의견을 말씀 드리면 
로컬에서는 `babel-loader` + `ReactRefreshWebpackPlugin` 으로 가는 것이 좋을 것 같습니다.
왜냐하면 `esbuild-loader`를 통해 빌드를 한다면 매 코드 수정시마다 전체를 다시 빌드하게 되어서 수정할 때마다 화면이 깜박이죠. 그러나 `ReactRefreshWebpackPlugin` 이  플러그인은 수정한 파일 하나만 다시 재빌드하기 때문에 코드를 수정해도 화면이 깜박이지 않습니다. 개발 중에 수정할 때마다 화면이 깜박이면 조금 불편할 것 같습니다.
development, production
저는  `esbuild-loader` + `ForkTsCheckerWebpackPlugin` 으로 가는 것이 좋을 것 같습니다.
왜냐하면 `esbuild-loader`가 `ts-loader`보다 빠른 것은 알고 계시는 것 같네용. `esbuild-loader`도 `babel-loader`와 마찬가지로 타입 검사를 하지 않습니다. 그래서 `ForkTsCheckerWebpackPlugin`이 플러그인을 통해 타입 검사를 하는 것이지요. 그래서 `ts-loader`는 필요없게 되고 빠른 빌드와 타입 검사를 위해 `esbuild-loader` + `ForkTsCheckerWebpackPlugin` 이 조합이 좋다고 생각합니다.

2022-10-16 14:59 UTC, yunjin-kim commented on frontend/.webpack/webpack.js
> -    new ReactRefreshWebpackPlugin(),
흠...이걸 왜 없앤거죠...ㅜㅜ 이 플러그인 캡숑짱인데

2022-10-16 14:59 UTC, yunjin-kim commented on frontend/.webpack/webpack.prod.js
> +    new ForkTsCheckerWebpackPlugin(),
이 플로그인과 ts-loader를 같이 쓰면 타입 검사를 두번하는게 됩니다.
ts-loader에서 options에 transpileOnly 를 true로 해줘야 ts-loader에서 타입검사를 하지 않습니다.

2022-10-17 04:16 UTC, jihyeok-um commented on frontend/.webpack/webpack.prod.js
> +    new ForkTsCheckerWebpackPlugin(),
![스크린샷 2022-10-17 오후 1 15 17](https://user-images.githubusercontent.com/75592315/196088179-e54cb220-9e9b-4d01-8a29-db8c0f3bd5e9.png)

공식문서에 `ts-loader` 버전이 9.3.0 이하일 때 해당 구문을 추가해주라고 나와있습니다
저희는 `ts-loader` 버전이 9.3.1 이라 추가하지 않았습니다

2022-10-17 04:22 UTC, jihyeok-um commented
> 이 주제에 대해서 월요일에 같이 토론하는 걸로 알고 있었는데 pr 보내시니 좀 당황스럽네요;;;

앗, 이 PR대로 하자거나, merge 해달라는 의미가 아니라 토론 전에 개인적으로 작업해보고
공유하기 위함 + 토론에서 사용할 자료 용도가 컸습니다! 갑작스럽게 PR을 날리셔서 당황하셨을 것 같네요 죄송합니다!

2022-10-17 07:03 UTC, jihyeok-um commented
> * development, production
>   저는  `esbuild-loader` + `ForkTsCheckerWebpackPlugin` 으로 가는 것이 좋을 것 같습니다.
>   왜냐하면 `esbuild-loader`가 `ts-loader`보다 빠른 것은 알고 계시는 것 같네용. `esbuild-loader`도 `babel-loader`와 마찬가지로 타입 검사를 하지 않습니다. 그래서 `ForkTsCheckerWebpackPlugin`이 플러그인을 통해 타입 검사를 하는 것이지요. 그래서 `ts-loader`는 필요없게 되고 빠른 빌드와 타입 검사를 위해 `esbuild-loader` + `ForkTsCheckerWebpackPlugin` 이 조합이 좋다고 생각합니다.

추가적인 비교를 해봤습니다
- `esbuild-loader` + `ForkTsCheckerWebpackPlugin` 와 `ts-loader` + `ForkTsCheckerWebpackPlugin` 의 빌드 타임  
(로컬 머신에서의 prod 빌드타임)은 8000ms ~ 9000ms로 미비한 차이가 났습니다.
여기서 `esbuild-loader`에서 제공하는 `ESBuildMinifyPlugin`를 사용하면 3000ms ~ 4000ms 정도로 빌드 타임이 줄어듭니다!

**`esbuild-loader` + `ForkTsCheckerWebpackPlugin` + `ESBuildMinifyPlugin`** 조합이 가장 빠르네요!

2022-10-17 07:50 UTC, jihyeok-um commented
토론한 결과대로 변경했습니다!

2022-10-17 16:18 UTC, yunjin-kim approved these changes

2022-10-17 16:18 UTC, merged