feat: 인터뷰 질문 검색 기능에 대한 웹 접근성 추가
woowacourse-teams/2022-levellog pull request #506
Opened 2022-10-16 14:14 UTC by yunjin-kim

## 구현 기능
- 인터뷰 질문 검색
  - 기존 왼쪽에 존재하던 검색아이콘을 오른쪽으로 옮김
- 인터뷰 질문 검색 결과
  - 검색 결과가 없을 시 : 검색결과가 없습니다 라고 읽어줌
  - 검색 결과 존재 시 : 검색 결과의 총 length를 읽어줌
- 인터뷰 질문 검색 결과 상세
  - 인터뷰 질문 검색 결과 텍스트, 좋아요 수, 좋아요 버튼 클릭 여부(이미 누른 좋아요/누르지 않은 좋아요)
  - 좋아요 버튼 클릭시 좋아요 개수가 올라갔다는 것을 읽어줌
- 스낵바
  - 스낵바가 생길 때마다 스낵바의 내용을 읽어줌

## 공유하고 싶은 내용
- 비로그인시 인터뷰 질문 검색하면 토큰이 없는데도 헤더에 실리는 문제 때문에 오류나는 것 수정

Close #498

2022-10-17 11:41 UTC, jihyeok-um requested changes

2022-10-17 11:41 UTC, frontend-jihyeok-um commented on frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
> +          <S.Button type={'button'} onClick={handleClickRemoveSearchTextButton}>
```tsx
  Button: styled.button`
  // styled(Button)
```
바꿔서 사용하면 어떨까요? "type={'button'}"을 따로 명시해줄 이유가 없어질 것 같네요!
지금까지 해온 버튼 스타일 컴포넌트를 만든 방식에도 부합하고요!

2022-10-17 11:41 UTC, jihyeok-um commented on frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
> +        <S.Button type={'submit'}>
돋보기 아이콘을 오른쪽으로 옮긴 것에는 반대입니다.
사실 "검색을 하는 버튼"의 역할보다는 "검색창 임을 알리는 이모지"의 역할이 더 크다고 생각하는데
지금 스타일로는 버튼처럼 보이지 않아서 사용하기에 더 혼란스럽네요

2022-10-17 11:41 UTC, jihyeok-um commented on frontend/src/components/interviewQuestion/InterviewQuestionSearchResults.tsx
> +        <S.SearchResultAriaText role={'status'}>검색 결과가 없습니다.</S.SearchResultAriaText>
굿 예외케이스까지 놓치지 않는 꼼꼼함 좋네요!

2022-10-17 11:41 UTC, jihyeok-um commented on frontend/src/components/@commons/Image.tsx
>  interface ImageProps {
이 타입에 대한 토론이 길어지고 있는 것 같은데
내일 zoom에서 이야기 해보는거나 해서 결론을 내면 좋을 것 같네요!
아니면 타입스크립트 리팩터링으로 미루거나!

2022-10-17 15:54 UTC, yunjin-kim commented on frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
> +        <S.Button type={'submit'}>
흠 그런 의도였군요 디자인을 릭이 했던걸로 기억하는데
구글을 참고했던 것 같네요. 구글은 `검색창 임을 알리는 이모지`이니 aria hidden을 추가해서 왼쪽에 배치하였습니다.

2022-10-17 16:00 UTC, yunjin-kim commented on frontend/src/components/interviewQuestion/InterviewQuestionSearchForm.tsx
> +          <S.Button type={'button'} onClick={handleClickRemoveSearchTextButton}>
좋습니다!

2022-10-18 01:24 UTC, jihyeok-um approved these changes

2022-10-18 01:24 UTC, merged