test: 유틸함수 테스트 코드 작성
woowacourse-teams/2022-levellog pull request #507
Opened 2022-10-17 03:55 UTC by yunjin-kim

## 구현 기능
- 유틸함수에 대한 테스트를 작성하였습니다.

## 공유하고 싶은 내용
기존 checkFirstWordFinalConsonant 함수(앞 문자가 받침이 있으면 이를 붙여주고 없다면 가를 붙여주는 함수)는 boolean을 반환해서 그 boolean 값을 토대로 UI 로직에서 삼항연산자로 `이/가`를 붙여줬는데 이를 해당 유틸함수 내에서 하는 것이 각자의 역할에 맞는 것 같아 변경했습니다. 

Close #499

2022-10-17 11:46 UTC, jihyeok-um requested changes

2022-10-17 11:46 UTC, jihyeok-um commented on frontend/src/utils/util.ts
> +  console.log('startAt', startAt);
console.log!

2022-10-17 11:46 UTC, jihyeok-um commented on frontend/src/utils/util.ts
> +  if ((uniCode - 44032) % 28 !== 0) {
`44032`, `55203`, `28` 등의 값은 무슨 의미인지 바로 알아보기가 힘들 것 같아요
상수화 해보는 건 어떨까요?

2022-10-17 16:10 UTC, yunjin-kim commented on frontend/src/utils/util.ts
> +  if ((uniCode - 44032) % 28 !== 0) {
```
const HangeulFirstTextUnicode = 44032;
const HangeulLastTextUnicode = 55203;
const finalConsonantNumber = 28;
```

2022-10-18 04:20 UTC, jihyeok-um approved these changes

2022-10-18 04:20 UTC, merged