refactor: 트랜잭션 범위에서 외부 리소스 요청 분리
woowacourse-teams/2022-levellog pull request #511
Opened 2022-10-18 08:16 UTC by SuyeonChoi

## 구현 기능
- 트랜잭션 범위 내에 존재하는 외부 리소스 요청 로직(Github OAuth API)을 분리하였습니다. 자세한 내용은 이슈 #509 를 참고해주세요.
- 외부와 통신하는 RestTemplate에 connect timeout, read timeout을 설정하였습니다.

**AS-IS**
![Untitled-10](https://user-images.githubusercontent.com/28749734/196374908-066d2e3a-cd1e-4048-be03-dfebac50245b.jpg)
**TO-BE**
![Untitled-10](https://user-images.githubusercontent.com/28749734/196375069-f33b13ad-83db-4eba-b868-b1caf53261e0.jpg)

## 논의하고 싶은 내용

### MemberLogin에 대하여..
- `@Service` vs. `@Component`
  - 현재 MemberLogin은 외부 API호출 로직과 로그인 비즈니스 로직(정보가 있으면 로그인하고 없으면 회원가입까지 처리한 뒤 로그인)을 엮어주는 역할을 가진 클래스입니다. 이는 저희의 서비스 비즈니스 로직과는 거리가 멀다는 느낌이 들어 현재 `@Component`를 통해 빈으로 등록하였습니다. 혹시 `@Service`가 더 적합하다는 의견이 있다면 말해주세요🤗🤗
- 테스트 여부
  - 위(`@Service` vs. `@Component`) 내용과 비슷한 이야기입니다. 결국 저희의 핵심 로그인 비즈니스 로직은 결국 `OAuthService`가 처리하기 때문에 테스트를 구현하지 않았습니다. 테스트해야할 중요한 비즈니스 로직과 다름을 구분하기 위해 `@Component`를 사용한 이유도 있습니다

## 공유하고 싶은 내용
- `connection-timeout`: server 자체에 client가 접근을 시도하는 시간
- `read-timeout`: client가 server에 접속 성공 후, 서버의 응답을 기다리는 시간

### 참고자료
- [CONNECTION TIMEOUT과 READ TIMEOUT 차이](https://inyl.github.io/programming/2017/12/02/timeout.html)
- [[Spring] RestTemplate 타임아웃(Timeout), 재시도(Retry), 로깅(Logging) 등 설정하기](https://mangkyu.tistory.com/m/256)

Close #509

2022-10-18 08:16 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +public class MemberLogin {
네이밍에 좋은 의견이 있다면 리뷰로 남겨주세요!🙇‍♀️

2022-10-18 08:16 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
> +                .setReadTimeout(Duration.ofSeconds(5))
Timeout에 대해 더 적합한 시간이 있다면 추천해주세요! 현재는 5초입니다

2022-10-18 10:54 UTC, OzRagwort requested changes
안녕하세요 페퍼 

이 부분은 상상도 못했던 부분인데 대단하신 것 같아요

그리고 실제로 트랜잭션이 잘 분리된 것 같기도 하구요

네이밍에 대한 부분은 몇 가지 코멘트 적은 부분이 정해지면 다시 의견내볼게요!

사실 페퍼만 괜찮으면 approve해도 될 것 같이 잘 짜주신것같은데 아직 아무도 리뷰 안해서 rc한번 날려봅니당 😃

2022-10-18 10:54 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +public class MemberLogin {
의견이니 적용 안해도 되는 리뷰)

수정하신 부분이 크게 보면 아래 두 가지 기능이 하나의 트랜잭션으로 묶여있었는데, 2번만 트랜잭션으로 묶고 1번은 밖으로 뺀 것 같아요(맞나요? ㅠ_ㅠ)

1. 깃허브와 연동하여 프로필 정보를 가져오는 기능
2. 가져온 프로필로 로그인을 하는 기능

지금은 1번 로직(`MemberLogin.login()`)안에서 2번 로직(`OAuthService.login()`)을 실행하는 것 같은데 1번 로직과 2번 로직을 컨트롤러에서 따로따로 실행하면 어떤가요? 지금은 불필요하게 두 클래스가 의존되고 있는 것 같아서요!

물론 컨트롤러가 1, 2번 기능을 하는 두개의 서비스(?)를 가지고 있어야겠지만 뭔가 그렇게 하는게 완전히 두개를 분리한 것 같아서요. 

그렇다면 현 `MemberLogin`의 `login()`은 `GithubProfileResponse`를 반환하게 될테고 `OAuthService`는 `GithubProfileResponse`를 받아서 로그인 로직을 수행하도록 될 것 같아요. 

`MemberLogin`은 `OAuthClient`만 가지고 깃허브랑만 통신하는 녀석이 될 수 있지않을까 생각했어요

만약 이렇게 된다면 `MemberLogin`과 `OAuthService` 모두 이름이 조금 바뀔 것 같아요

2022-10-18 10:54 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +        final GithubProfileResponse githubProfile = oAuthClient.getProfile(githubAccessToken);
지금은 github로만 oauth를 이용하고있는데 혹시 나중에 카카오나 네이버 로그인 등이 추가된다면 dto나 해당 메서드를 조금 바꿔야할 것 같네요.

지금 생각할 일이 아닐 수도 있긴 하지만 갑자기 그런 상황이 생각이 나서 적어봤어요
(고치라는건 아니고 그냥 메모용)

2022-10-18 10:54 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
> +                .setReadTimeout(Duration.ofSeconds(5))
좋습니당 운영서버나 개발서버에서 테스트할때 1초~1초 초중반 정도 나왔던 것 같아서 괜찮을 것 같아요!

2022-10-18 10:54 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +    public LoginResponse login(final GithubCodeRequest request) {
위에 `MemberLogin`과 `OAuthService`가 의존하지 않게 분리해보면 어떻냐는 것이랑 이어져서 이 메서드가 하는 일이 많은 것 같기도 해요

login()이라는 이름에서 깃허브와의 통신과 로그인하는 과정이 포함되어 있는 것 같아서요 😃

2022-10-19 09:43 UTC, nailseong approved these changes
고생하셨습니다 페퍼!!!! 덕분에 DB가 더 많은 요청을 처리할 수 있겠네요 😊
잘 구현하셔서 크게 불편한 부분은 없네요. 논의하고 싶은 내용을 남기셔서 간단한 의견만 남기고 approve합니당. :)

제가 남긴 코멘트를 반영 하신다면 어노테이션은 `@Service`를 붙이는게 좋아보이네요.
테스트는 딱히 추가할 필요는 없어보여요. (Jacoco가 억까하면 어쩔수없지만...)

2022-10-19 09:43 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +public class MemberLogin {
`OAuthController`는 `OAuthService`라는 이름의 객체를 의존하는게 좋아보여요.

OAuthService는 아래 두 개의 객체를 의존하면 어떨까요?
- 깃헙에서 유저 정보를 조회해오기 위한 `OAuthClient`
- 로그인 로직과 트랜잭션을 관리하는 `LoginService`

아래와 같이 이름이 바뀔것 같습니당
MemberLogin -> OAuthService
OAuthService -> LoginService

2022-10-19 09:43 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
> +                .setReadTimeout(Duration.ofSeconds(5))
5초 괜찮아보여요

2022-10-19 10:00 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
> +                .setReadTimeout(Duration.ofSeconds(5))
저도 5초 좋습니다.

2022-10-19 10:17 UTC, OzRagwort approved these changes

2022-10-20 12:40 UTC, SuyeonChoi reviewed
리뷰 반영했습니다^0^

2022-10-20 12:40 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +public class MemberLogin {
네네! 알린이 정리한 플로우가 맞아용! 아주 정확하게 이해하셨습니다👏👏

`MemberLogin`과 `OAuthService`에서 수행하는 로직의 순서가 명확하게 한 방향으로 흐르고 있어요.
서비스끼리 의존해서 추후 상호 의존 문제 잠재성을 키우는것보단 알린 의견을 따라 컨트롤러가 가지고 있는 것이 훨씬 좋을거 같네요!!

정말 좋은 피드백 감사합니다 바로 반영할게요 :D 
역시 어릴적부터 개발 욕망가 알린!!!!🚀🚀

2022-10-20 12:40 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +public class MemberLogin {
역시 릭! 좋은 네이밍 추천 감사합니다🙇‍♀️🙇‍♀️ 네이밍 변경 반영하겠습니다!

>  OAuthService는 아래 두 개의 객체를 의존하면 어떨까요?

해당 부분을 언급해서 그런데 알린의 의견대로 컨트롤러에서 두 개의 서비스를 의존하면 어떨까요?
릭이 주신 네이밍을 반영한다면 `OAuthService`와 `LoginService`를 컨트롤러에서 의존하게 될거 같아요😉😉

2022-10-20 12:40 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +        final GithubProfileResponse githubProfile = oAuthClient.getProfile(githubAccessToken);
오오! 확장성 고려 너무 훌륭합니다🚀🚀
현재 이슈에서 고려하기는 다소 버거울거 같아서 좋은 의견 다른 백엔드 크루들에게 노티만 주도록 하죠!!
그럼 누군가 한명은 나중에 기억해서 처리해줄지도...?!?!

@kbsat @nailseong @2yujeong

2022-10-20 12:40 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +    public LoginResponse login(final GithubCodeRequest request) {
GithubProfile을 가져오는 메서드명을 `requestGithubProfile()`로 변경해보았어요.
더 좋은 네이밍이 있다면 의견주세요!!
@OzRagwort @kbsat @nailseong @2yujeong

2022-10-21 00:53 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +    public LoginResponse login(final GithubCodeRequest request) {
굳굳~

2022-10-21 00:54 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/MemberLogin.java
> +public class MemberLogin {
트랜잭션 문제만 없다면 상관없습니둥 :0

2022-10-21 03:53 UTC, 2yujeong approved these changes
깔끔하네요!!

2022-10-23 05:06 UTC, kbsat approved these changes
좋은 고민 감사합니다. 역시 봉주 😊
다른 분들이 좋은 의견 남겨주셔서 깔끔한 코드가 된 것 같네요 딱히 남길 말 없습니다.
이만 머지하겠습니다. 고생하셨어요.

2022-10-23 05:06 UTC, merged