feat: Github 로그인 기능을 구현한다.
woowacourse-teams/2022-levellog pull request #52
Opened 2022-07-15 04:59 UTC by kbsat

## 구현 기능
- Github를 활용한 로그인 기능을 구현했습니다.

## 논의하고 싶은 내용
- 인수 테스트 작성에 대해 논의하고 싶습니다.  ([관련 이슈](https://github.com/woowacourse-teams/2022-levellog/issues/26#issuecomment-1184084422))
- 현재 Github의존성이 깊은 코드에 대해서는 테스트 코드 작성을 하지 않았습니다. 좋은 방법 있으신 분 알려주십쇼

## 공유하고 싶은 내용
- [노션링크](https://www.notion.so/WIP-Github-a47ad2208473455f990b666f03ff7c68)

Close #26

2022-07-16 03:55 UTC, nailseong requested changes
고생 많았어요. 간단한 수정 포인트 남겼습니당 😉

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/application/MemberService.java
> +@Transactional
길이순으로 정렬하기로 한것 같은데 아닌가요?

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/application/OAuthService.java
> +    private final JwtTokenProvider jwtTokenProvider;
```suggestion
    private final MemberService memberService;
    private final GithubOAuthClient githubOAuthClient;
    private final JwtTokenProvider jwtTokenProvider;
```

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/domain/GithubOAuthClient.java
> +        }
<img width="622" alt="image" src="https://user-images.githubusercontent.com/68512686/179331927-079167d1-3f29-4275-95c3-675d37502d95.png">
메서드 참조에서 활용하도록 만든 API라고 합니다.

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubAccessTokenRequest.java
> +    private String clientId;
`@JsonProperty` 👍

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
`LoginMemberResolver`는 bean으로 등록했는데 인터셉터는 bean으로 관리하지 않는 이유가 있나요?

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/LoginInterceptor.java
> +        return true;
Interceptor와 Resolver의 역할이 불분명해보여요.
인터셉터에서는 `jwtTokenProvider.validate(token)`와 같은 메서드를 호출해서 올바른 토큰인지 검증만 하는게 좋아보여요.

2022-07-16 03:55 UTC, nailseong commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/OAuthController.java
> +    }
```suggestion
    @CrossOrigin
    @PostMapping("/login")
    public ResponseEntity<LoginResponse> login(@RequestBody @Valid final GithubCodeRequest request) {
        return ResponseEntity.ok(oAuthService.login(request));
    }
```

2022-07-16 03:55 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +public class MemberServiceTest {
```suggestion
class MemberServiceTest {
```

2022-07-16 03:55 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/application/MemberServiceTest.java
> +import javax.transaction.Transactional;
```suggestion
import org.springframework.transaction.annotation.Transactional;
```
👀

2022-07-16 03:55 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/authentication/application/OAuthServiceTest.java
> +}
```suggestion
    }
}
```

2022-07-16 03:55 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/support/ControllerTest.java
> +}
```suggestion
    @Autowired
    protected ObjectMapper objectMapper;
}
```

2022-07-16 05:15 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/AuthenticationConfig.java
> +                .excludePathPatterns("/**");
이러면 

아직 로그인 기능을 추가할 때가 아니라고 생각해서 빼신걸까요?

2022-07-16 13:14 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
당시 생각으로는 LoginMemberResolver는 jwtTokenProvider 외에 memberService를 주입받아야하기 때문에 빈으로 관리하는게 편하겠다 생각이 들었지만 인터셉터에 대해서는 jwtTokenProvider만 주입해주면 되서 수동으로 주입해서 등록하는 선택을 했는데 지금 생각해보니 인터셉터를 빈으로 등록하지 않을 이유가 없는 것 같네요 😇

2022-07-16 13:27 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/authentication/presentation/LoginInterceptor.java
> +        return true;
getPayload() 메서드 내부에 존재하는 `parseClaimsJws(token)` 에서 예외에 대한 처리를 해주기 때문에 불필요하다고 생각하긴 했는데 역할과 책임을 분명히 한다는 점에서는 `jwtTokenProvider.validate(token)`로 분리해주는 것이 좋을 것 같네요.

2022-07-16 17:36 UTC, nailseong approved these changes
https://github.com/woowacourse-teams/2022-levellog/issues/26#issuecomment-1184084422
1. `GithubOAuthClient`를 인터페이스로 추상화
2.  프로덕션 코드 `@Configuration`에 구현 클래스를 bean으로 등록한다.
3. 구현한 가짜 `OAuthClient`를 테스트 패키지에 추가한다.
4. `@TestConfiguration`을 통해 가짜 객체를 bean으로 등록한다.
5. 인수 테스트를 작성한다.

https://github.com/woowacourse-teams/2022-levellog/issues/26#issuecomment-1186232346
환경 변수를 외부에서 삽입하는 방법이 좋아보여용
```
java -Dspring.profiles.active=dev -DDB_HOST=localhost -DTEST_DB_NAME=levellog -DTEST_DB_USER_NAME=me -DTEST_DB_PASSWORD=1234 -jar levellog-0.0.1-SNAPSHOT.jar
```
이런게 `-D{key}={value}` 옵션으로 환경번수를 애플리케이션 실행 시점에 설정할 수 있어용 (이 방법이 더 쉽다고 생각해요)

2022-07-16 17:36 UTC, nailseong commented on backend/src/test/java/com/woowacourse/levellog/authentication/application/OAuthServiceTest.java
> +                    new GithubProfileResponse("12345", "로마", "imageUrl"));
```suggestion
            BDDMockito.given(githubOAuthClient.getGithubAccessToken("githubCode"))
                    .willReturn("accessToken");
            BDDMockito.given(githubOAuthClient.getGithubProfile("accessToken"))
                    .willReturn(new GithubProfileResponse("12345", "로마", "imageUrl"));
```
Mockito.when 과 동일한 기능을 하는 BDDMockito.given이라는 메서드도 있어용 (내부 구현을 보시면 바로 아시겠지만 정말 메서드 이름 바꾸기만 해요)
저는 메서드 모킹은 주로 given 블록에 작성하는데 `when` 메서드를 호출하면 조금 어색하더라고용. 그래서 BDDMockito.given을 선호하는데 로마&페퍼는 어떠신가용

2022-07-16 20:37 UTC, OzRagwort approved these changes

2022-07-17 04:08 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/authentication/application/OAuthServiceTest.java
> +                    new GithubProfileResponse("12345", "로마", "imageUrl"));
좋은 의견 감사합니다~! 😃
페퍼와 이야기해 본 결과 `BDDMockito` 를 사용해서 `given` `willReturn` 으로 하는 것이 가독성이 좋겠다는 의견으로 모아져서 반영해 보도록 할게요!!

2022-07-18 02:12 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/authentication/dto/GithubAccessTokenResponse.java
> +    private String scope;
scope와 tokenType은 쓰이는 곳이 없는 거 같은데 함께 받는 이유가 있을까요??👀

2022-07-18 02:12 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
> +        return memberService.getById(memberId);
컨트롤러로 멤버의 ID만 넘겨줘도 될 거 같은데 비즈니스 로직을 거쳐서 Member 객체로 매핑해서 넘겨주는 이유가 있을까요??

2022-07-18 07:20 UTC, 2yujeong approved these changes
굿굿~! 반영 후 머지해주세요!

2022-07-18 08:00 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/authentication/config/LoginMemberResolver.java
> +        return memberService.getById(memberId);
비즈니스 로직을 불필요하게 거친다는 의견으로 모아졌네요!! `memberId` 만 반환하도록 변경하였습니다 🙂

2022-07-18 09:43 UTC, SuyeonChoi commented
- LoginMemberResolver에서 Member 도메인이 아닌 memberId값을 반환하도록 변경
-  멤버 전체 조회 기능 추가

2022-07-18 09:43 UTC, merged