fix: 전체 스토리북 점검
woowacourse-teams/2022-levellog pull request #527
Opened 2022-10-19 14:46 UTC by yunjin-kim

## 구현 기능
- 구현한 기능을 적습니다.

## 논의하고 싶은 내용
- 논의할 내용을 적습니다.

## 공유하고 싶은 내용
- 학습한 내용, 공유할 내용 등을 적습니다.
- 위키에 작성했다면 링크 첨부, 없는 경우 삭제

## 기타
- 기타 추가할 내용이 있다면 추가합니다.
- 없는 경우 삭제

Close #이슈번호

2022-10-21 08:20 UTC, jihyeok-um requested changes

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/button/Button.stories.tsx
> +const InterviewerButton = styled(Button)`
`Interviewer` 에  있는 버튼을 스토리북으로 작성하기 위해 `S.Button`의 코드를 그대로 복사해오셨네요
이렇게 스토리북을 작성하는건 좋은 방법이 아닌 것 같습니다.

1. 같은 코드 반복
2. 실제 버튼의 스타일이 변경 되었을 때 스토리북도 변경해주어야함

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/button/Button.stories.tsx
> +export const AbledInterviewerButton = InterviewerTemplate.bind({});
`Abled` 라는 prefix는 없는게 나을 것 같습니다.
버튼은 대체로 기본값이 "abled" 이고 특수한 경우가 "disabled" 이기도 하니까요.

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/contentHeader/ContentHeader.stories.tsx
> +import ContentHeader from 'components/@commons/contentHeader/ContentHeader';
아주 아주... 과거에 (3개월 전)부터 방치된 스토리북이라 지금의 `ContentHeader` 에 맞게 수정하는게 맞는 것 같습니다.
지금의 `ContentHeader` 는 여러개의 케이스가 있는데요.
 
1. 이미지, 타이틀
2. 이미지, 타이틀, 서브타이틀
3. 이미지, 타이틀, 서브타이틀, 필터버튼들(좌측버튼들)
4. 이미지, 타이틀, 서브타이틀, 우측버튼들

.. 등등

스토리북은 작성한 컴포넌트의 UI가 각각의 케이스에 제대로 보여지는 지 테스트하는데 의미가 있다고 보는데
그래서 저는 각각에 케이스를 커버하는 스토리들이 추가되어야할 것 같습니다.

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/contentHeader/ContentHeader.stories.tsx
> +import ContentHeader from 'components/@commons/contentHeader/ContentHeader';
이건 여담이지만 반응형에 관한 스토리도 있으면 좋겠네요!

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/image/Image.stories.tsx
> +export const Radius = Template.bind({});
주로 다루게 되는 `sizes`에 관한 스토리들도 있으면 좋을 것 같네요

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/input/Input.tsx
> +const Input = ({
지금 `Input` 에 대한 테스트는 사실상 의미가 없는 것 같아요 ㅠㅠ

2022-10-21 08:20 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/role/Role.stories.tsx
> +export const InterviewEach = Template.bind({});
`Role` 컴포넌트와 관련 이미지에서는 "상호 인터뷰" 에서 `InterviewBoth` 라고 사용하는 것 같아서 
여기도 동일하게 따라가는게 좋겠네요

2022-10-21 08:20 UTC, jihyeok-um commented on frontend/src/components/@commons/modal/Modal.stories.tsx
> +import { ComponentMeta, ComponentStory } from '@storybook/react';
전반적으로 컴포넌트가 많이 추가된 것에 비해 스토리는 기존에서 추가된 것이 별로 없는 것 같습니다.
`Interviewier` , `Feedback`, `InterviewTeam` 등등 추가할만한 것들이 많은 것 같은데 그래서 예시로 `Modal`에 관한 스토리를 한 번 추가해 봤습니다~ 참고해서 필요한 컴포넌트에 대해서 스토리를 추가해보는건 어떨까요?

2022-10-21 08:26 UTC, jihyeok-um requested changes

2022-10-21 08:26 UTC, frontend-jihyeok-um commented on frontend/src/components/@commons/button/Button.stories.tsx
> +const InterviewerTemplate: ComponentStory<typeof Button> = (args) => (
추가적으로 한 줄로 작성할 수 없으면 
```tsx

const InterviewerTemplate: ComponentStory<typeof Button> = (args) => {
  return <InterviewerButton {...args}></InterviewerButton>
};
```
와 같이 컨벤션 대로 바꿔주세요~

2022-10-23 03:03 UTC, yunjin-kim commented on frontend/src/components/@commons/button/Button.stories.tsx
> +const InterviewerButton = styled(Button)`
InterviewerButton으로 컴포넌트 분리해서 진행하였습니다.!

2022-10-23 03:05 UTC, yunjin-kim commented on frontend/src/components/@commons/modal/Modal.stories.tsx
> +import { ComponentMeta, ComponentStory } from '@storybook/react';
아무 언질없이 푸시라뇨ㅜㅜ 
제 커밋이 푸시 안 되길래 뭐 잘못했나싶었네요

2022-10-23 03:07 UTC, yunjin-kim commented on frontend/src/components/@commons/button/Button.stories.tsx
> +const InterviewerTemplate: ComponentStory<typeof Button> = (args) => (
한줄로 작성되는데 줄넘김이 되어서 IDE에서 자동으로 소괄호를 넣어주는데 이런 경우에도 중괄호 + return문으로 변경하는게 좋을까요?

2022-10-23 04:13 UTC, yunjin-kim commented on frontend/src/components/@commons/contentHeader/ContentHeader.stories.tsx
> +import ContentHeader from 'components/@commons/contentHeader/ContentHeader';
이미지, 타이틀
이미지, 타이틀, 서브타이틀
이미지, 타이틀, 서브타이틀, 필터버튼들(좌측버튼들)
이미지, 타이틀, 서브타이틀, 우측버튼들

케이스 추가하였습니다!

2022-10-23 04:15 UTC, yunjin-kim commented on frontend/src/components/@commons/image/Image.stories.tsx
> +export const Radius = Template.bind({});
반영했습니다!

2022-10-23 04:23 UTC, yunjin-kim commented on frontend/src/components/@commons/input/Input.tsx
> +const Input = ({
ㅋㅋㅋ삭제하겠습니다

2022-10-23 13:11 UTC, jihyeok-um commented on frontend/src/components/@commons/modal/Modal.stories.tsx
> +import { ComponentMeta, ComponentStory } from '@storybook/react';
오.. 제가 PR에 푸시해버리면 작업자 커밋이 푸시가 안 되는군요 죄송합니다 ㅠㅠ

2022-10-23 13:14 UTC, jihyeok-um commented on frontend/src/components/@commons/button/Button.stories.tsx
> +const InterviewerTemplate: ComponentStory<typeof Button> = (args) => (
오.. 저희 prettier 기준 100자 이상이면 줄바꿈이 되고, 줄바꿈이 된다고 따로 중괄호 + return문으로 바꿔주는 규칙을 추가하지 않았으니IDE의 설정이 저희 컨벤션과 동일하지 않은 것 같네요! 컨벤션 대로 변경하는게 좋을 것 같습니다!

2022-10-23 23:41 UTC, yunjin-kim commented on frontend/src/components/@commons/button/Button.stories.tsx
> +const InterviewerTemplate: ComponentStory<typeof Button> = (args) => (
굿입니다 완료!

2022-10-24 07:50 UTC, jihyeok-um approved these changes

2022-10-24 07:50 UTC, merged

2022-10-24 07:52 UTC, jihyeok-um commented
슬랙으로 말씀드렸던대로 사소한 수정 후에 merge했습니다~