chore: 개발용 빌드 설정 수정
woowacourse-teams/2022-levellog pull request #572
Opened 2022-11-02 06:49 UTC by jihyeok-um

## 구현 기능
- 개발용 빌드 설정 수정

## 논의하고 싶은 내용
자세한 내용은 #571 을 참고해주세요. 이 PR대로 설정이 바뀌면 기존의 문제가 발생할 수가 없습니다.
그렇기 때문에 #570 를 머지하지 않고 기존 설정을 유지해도 괜찮습니다.

Close #571

2022-11-02 07:31 UTC, yunjin-kim approved these changes
👍👍

2022-11-02 08:38 UTC, OzRagwort requested changes
develop에서도 운영빌드를 해야합니다.

build-prod와 build-dev가 똑같다면 그냥 build-dev를 없애는게 맞습니다.

2022-11-02 08:38 UTC, OzRagwort commented on .github/workflows/front-prod.yml
> -      - "develop"
다시 추가해주세요!! prod 빌드는 꼭 해야합니다.

2022-11-02 08:57 UTC, jihyeok-um commented on .github/workflows/front-prod.yml
> -      - "develop"
이유가 뭐죠? prod빌드와 dev빌드에서 차이는 `API_URL`와 같은 환경에 관한 밖에 없고, `API_URL` 등이 잘못되었다고한들, CI Build 과정에서 에러로 검출이 되지 않을 겁니다

2022-11-02 08:59 UTC, jihyeok-um commented
> build-prod와 build-dev가 똑같다면 그냥 build-dev를 없애는게 맞습니다.

환경정보는 다릅니다. 저희가 개발서버에서와 운영서버에서 요청을 보내는 주소가 다르니까요

2022-11-02 09:07 UTC, OzRagwort commented on .github/workflows/front-prod.yml
> -      - "develop"
왜 있어야 하는지는 이전 토론에서 충분히 설명이 되었고 이애했다고 해서 넘어가겠습니다. 

추가로 해리 질문에 답변하자면 prod빌드와 dev빌드가 같은지 다른지를 확인 하기위해서라도 둘다 해야한다고 생각합니다.

1.4.6까지 그렇게 해왔고 그 설정을 없앤 버전부터 그 둘이 다르다는것 때문에 실제로 문제가 발생했었으니까요.

prod 빌드를 하면 좋지만 하지 않아도 된다는 것은 "지금 두 빌드의 문제를 고쳤으니 앞으로도 문제가 없을 것이다. 믿고 확인은 안해도 된다."라는 의미로 들리는데 맞을까요? 앞으로 그 문제가 발생할지 아닐지는 모른다고 생각하기 때문에 꼭 있어야 한다고 생각합니다.

약간의 CI 속도 향상을 위해 크리티컬한 이슈가 발생할 수도 있는 코드를 서버에 올리는 위험을 감수하는것은 잘못되었다고 생각합니다.

2022-11-02 09:23 UTC, jihyeok-um commented on .github/workflows/front-prod.yml
> -      - "develop"
기존의 dev빌드는 prod 빌드와 달리 최적화 과정이 생략되는 모드를 사용 중이었습니다. 이젠 같은 모드를 사용합니다.

> 1.4.6까지 그렇게 해왔고 그 설정을 없앤 버전부터 그 둘이 다르다는것 때문에 실제로 문제가 발생했었으니까요.

이번 PR에서는 빌드 과정이 처음부터 끝까지 동일하게 바뀌었는데 어떻게 문제가 발생할 수 있을까요?

> prod 빌드를 하면 좋지만 하지 않아도 된다는 것은 "지금 두 빌드의 문제를 고쳤으니 앞으로도 문제가 없을 것이다. 믿고 확인은 안해도 된다."라는 의미로 들리는데 맞을까요? 

아뇨, 하면 좋을 이유도 없는 것이 아예 같은 빌드 과정을 거치기 때문에 두 빌드를 같이 할 필요가 없는 겁니다. 

> "왜 있어야 하는지는 이전 토론에서 충분히 설명이 되었고 이해했다고 해서 넘어가겠습니다." 

여기에 대한 전제가 바뀐 경우라고 생각합니다. 

이제 dev, prod빌드는 동일한 과정을 수행하고 "환경"에 관한 상수만 다르게 전달을 합니다.
그리고 빌드 과정에서는 전달된 상수가 잘못된 상수임을 알고 에러를 검출할 수가 없습니다. 
결국 dev, prod 빌드는 무조건 동일한 결과를 뱉을 것입니다. 

 dev, prod 빌드를 하나의 수정사항에 대해 둘 다 시행한다는 것은 똑같은 테스트를 2번 돌리는 것과 같다는 겁니다.

2022-11-02 09:39 UTC, jihyeok-um commented on .github/workflows/front-prod.yml
> -      - "develop"
> 약간의 CI 속도 향상을 위해 

추가적으로 속도 향상을 위해라기보다 할 필요가 없는 작업이라는 이야기입니다.

백엔드 PR이 올라왔는데 CI에서 혹시 모르니 검증용으로 소나큐브 빌드를 두 번하진 않잖아요?

2022-11-02 09:42 UTC, OzRagwort commented on .github/workflows/front-prod.yml
> -      - "develop"
똑같은 테스트인것을 어떻게 믿을 수 있을까?라는 답은 단지 해리가 그렇게 했기 때문일까요? 모두가 똑같은 것으로 빌드하기 때문이고 앞으로 절대 안바뀔 것이기 때문일까요?

앞으로 이 부분이 바뀌지 않을 것이라고 확신할 수도 없고 지금도 이미 잘못되었는지 아닌지도 확신할 수 없습니다. 지난 몇개 버전에서 발견되고 고친 버그들도 그렇구요

사람이기때문에 실수하고 그것을 잡기위해 CI를 한다고 생각해요. 

URL은 개발 백엔드 서버를 사용해야하니 젠킨스에서 배포할때는 dev빌드를 해야한다는것은 이해했지만 그렇기 때문에 prod빌드는 안해도 된다는 것은 납득이 어렵습니다.

2022-11-02 10:20 UTC, jihyeok-um commented on .github/workflows/front-prod.yml
> -      - "develop"
> 똑같은 테스트인것을 어떻게 믿을 수 있을까?라는 답은 단지 해리가 그렇게 했기 때문일까요? 

똑같은 테스트인것을 믿을 수 없다는 것은 "이름만 다른 완전히 구현이 같은 함수"가 동일하게 동작하지 않을 것이다.. 와 같은 전제인 것 같습니다.

> 모두가 똑같은 것으로 빌드하기 때문이고 앞으로 절대 안바뀔 것이기 때문일까요?

앞으로 이 부분이 바뀌지 않을 것이라고 확신할 수도 없고 지금도 이미 잘못되었는지 아닌지도 확신할 수 없습니다. 

webpack에는 공통된 설정을 위한 merge 라는 메서드가 있습니다. 한 쪽만 설정이 달라져서 생기는 문제는 merge를 사용하면 그럴 일이 없지 않을까요?

> 지난 몇개 버전에서 발견되고 고친 버그들도 그렇구요

CI에서 빌드 환경을 분리하면서 생긴 에러는 하나였고, 부수적인 목적이긴하지만 그 에러가 발생하지 않도록 dev prod 빌드 과정을 완전히 동일하게 바꾸는 작업을 제가 한 겁니다. 

> 사람이기때문에 실수하고 그것을 잡기위해 CI를 한다고 생각해요.

알린은 어떤 실수를 잡고 싶으신건가요? 저는 완전히 동일한 빌드 과정을 CI에서 두 번 거치는 것이 어떤 실수를 해결해줄 수 있는지 모르겠습니다.

2022-11-03 02:05 UTC, OzRagwort approved these changes
설명대로 URL을 제외한 모든 것이 같도록 수정되었면 github actions에서 prod빌드와 dev빌드가 차이가 없을 것입니다.

그렇기 때문에 dev 빌드 대신 prod 빌드를 할 필요가 없다는 의미는 반대로 prod 빌드 대신 dev 빌드를 할 필요도 없다는 말입니다. 둘 중 어느것을 해도 상관이 없다면 prod빌드를 하자는 취지였는데 소모값만 커진 느낌이네요. 

토론과 팀 규칙에 맞추어 approve하겠습니다

2022-11-03 03:27 UTC, jihyeok-um commented
토론 결과로 해당 PR은 머지하도록 하겠습니다~

2022-11-03 03:28 UTC, merged