feat: Member, Feedback, Levellog, Team 도메인을 설계하고 깨진 테스트를 수정한다.
woowacourse-teams/2022-levellog pull request #70
Opened 2022-07-16 20:26 UTC by OzRagwort

## 구현 기능
- Member, Feedback, Levellog, Team 도메인 수정
- Member, Feedback, Levellog, Team 테스트 수정

## 논의하고 싶은 내용
- 지금 우리의 브랜치 전략이 조금 이상한 것 같음. 
- 이슈를 조금 크게 묶어서 열고, 이슈 단위로 브랜치를 파고 그곳에 스쿼시 머지. 최종 완료가 되면 main에 머지하는 방식이 어떤가 싶음.
  - 지금 Team 도메인을 예로들면 BE와 FE 합쳐서 총 10개의 이슈가 생기는데 이걸 1개의 이슈로 만든 뒤 `develop/team` 브랜치 생성.
  - BE에서 구현하고 `develop/team` 브랜치에 스쿼시 머지를 함.
  - FE에서 구현/수정 된 코드로 구현하여 `develop/team` 브랜치에 스쿼시 머지를 함. 
  - Team 도메인과 관련된 기능이 모두 완성되면 main에 머지하여 기능을 추가하고 이슈를 닫음.
- 이렇게 하려는 이유
  1. 지금은 이슈가 불필요하게 많아짐.
  2. BE에서 API를 수정하고 바로 main에 배포하면 FE의 수정된 코드가 배포되기 전까지 FE 페이지에서 그 기능은 되던게 안되게 됨. 
  3. `Github Flow는 빠르게 기능을 추가하여 배포할 수 있다는 장점이 있다.` -> 기능의 단위를 다시 고민해보고 싶음.

## 기타
- Team 도메인에 대한 API명세가 없어서 Member, Feedback, Levellog, Team의 인수 테스트, Controller 테스트는 `@Disabled` 함.
- Team 도메인에 대한 API명세가 생기면 API를 구현하면서 Member, Feedback, Levellog, Team의 인수테스트와 Controller테스트를 구현해야함.
- Member에 대한 기능이 필요하여 로그인 기능이 main에 머지되지 않았지만 해당 브랜치를 가져와서 구현함.

Close #35 #53 #54 #66

2022-07-17 15:54 UTC, nailseong approved these changes
로그인 기능이 merge되지 않은 상태에서 브랜치가 분기해서 Files changed가 넘 많네용... 🥲
고생하셨습니당 귿귿 ~ 👍

2022-07-18 16:02 UTC, kbsat requested changes
안녕하세요 알린.. 정말 고생 많으셨군요 😱
몇가지 고민사항이나 제안 남겨놓았으니 참고하시어 적용해주시면 감사하겠습니다. 😊

2022-07-18 16:02 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/presentation/LevellogController.java
> +                                       @LoginMember final Member author) {
이제 ArgumentResolver에서 ID를 반환하기 때문에 `@LoginMember` 로  Member를 받을수 없겠군요 .. 🥲
아마 다른 것들도 많이 수정될 것 같네요.. ?

2022-07-18 16:02 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
> +    public ResponseEntity<Void> save(@RequestParam final Long levellogId,
`LevelogController`에서는 생성 메서드 이름이 `create`인데 여기서는 `save`네요!  뭐가 더 나은지는 잘 모르겠지만 통일감을 주는 것이 좋을 것 같아요.

2022-07-18 16:02 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/exception/FeedbackNotFoundException.java
> +public class FeedbackNotFoundException extends RuntimeException {
RuntimeException을 상속받는 것이 아닌 LevellogException으로 변경되어야 해요! ( #13  )

2022-07-18 16:02 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/domain/Feedback.java
> +    @ManyToOne
`ToOne` 이 붙은 곳에 LazyLoading 전략을 넣어주는게 어떨까요??
- 이유 1 : 현재 모든 연관관계에 Eager 전략이 들어가있어 feedback을  find 할때 이와 연관되어있는 모든 것 + 그 객체 안에서 연관되어있는 모든 것 을 조인해서 한번에 들고오게 됩니다.
  - 실험삼아 날려본 쿼리
  <img width="393" alt="스크린샷 2022-07-19 00 58 00" src="https://user-images.githubusercontent.com/52696169/179552791-a5b4f474-7183-424a-80b0-032ac10bbe6f.png">

- 이유 2: 현재는 JPQL을 사용해서 Feedback을 조회하면 멤버 2개 레벨로그 1개 총 세 개의 select 쿼리가 더 나가는 N+1 문제 발생. 이후 객체가 변경되었을 때 예상치 못한 쿼리가 추가적으로 계속 발생할 수 있다.

2022-07-19 01:51 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/domain/Feedback.java
> +    @ManyToOne
이 부분은 문제가 발생하면 다시 수정하는 것으로 하겠습니다 - 회의 결과

2022-07-19 01:53 UTC, kbsat approved these changes

2022-07-19 02:17 UTC, SuyeonChoi approved these changes
알린 많은 테스트를 고치느라 수고 많았어요!!
처음엔 수정할 내용이 별로 없을줄 알았는데 연관관계가 많다보니 이슈가 커졌네요.
앞으로는 이슈를 효율적으로 나눠봅시당ㅎㅎ

원래는 RC였는데 옆에서 바로바로 fix 하셨으니 approve하겠습니다😆😆
2차 데모데이까지 **화이팅**!!!!!🔥

2022-07-19 02:17 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
> +    public ResponseEntity<FeedbacksResponse> findAll(@RequestParam final Long levellogId,
RequestParam`@RequestMapping("/api/levellogs/{levellogId}/feedbacks")`경로의 levellogId를 `@Pathvariable`이 아닌  `@RequestParam`으로 받는 이유가 있나요?

2022-07-19 02:17 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/presentation/LevellogController.java
> +                                       @LoginMember final Member author) {
로마의 의견처럼 이제 LoginMemberResolver에서 Member객체가 아닌 githubId를 넘겨주기 때문에 추후에 수정되어야할거 같네요! 
수정되면 좋겠지만 당장은 AuthenticationConfig에서 해당 API에 인가처리를 하지 않았기 때문에 상관없을거 같습니다😏
[참고PR](https://github.com/woowacourse-teams/2022-levellog/pull/52#issuecomment-1186987751)

2022-07-19 02:17 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
> +        feedbackService.deleteById(feedbackId);
`update`는 서비스에서도 함수명을 그대로 가져가는데 `delete`는 그렇지 않은 이유가 있나요? 일관성 있게 가져가는게 컨벤션을 기억하기 편할거 같아요!

2022-07-19 02:17 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/domain/Member.java
> +    @Column(nullable = false)
👍

2022-07-19 02:17 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/acceptance/MyInfoAcceptanceTest.java
> +    }
테스트를 작성하지 않은 이유도 주석으로 써두거나 `TODO` 주석을 사용하는 것은 어떨까요?
나중에 PR까지 갈 필요없이 코드만 보고 바로 알 수 있도록요!🙂

2022-07-19 02:17 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/presentation/LevellogControllerTest.java
> +    // FIXME : 팀 API 구현 후 수정
여기는 테스트를 작성하지 않은 이유가 있었군요!

2022-07-19 02:23 UTC, kbsat approved these changes

2022-07-19 02:23 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
> +                feedbackContent.getEtc());
추후 Builder를 적용하는 것도 좋겠군요 😂

2022-07-19 02:23 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/LevellogServiceTest.java
> +    private MemberRepository memberRepository;
```suggestion
    @Autowired
    private LevellogRepository levellogRepository;
    
    @Autowired
    private MemberRepository memberRepository;
```

2022-07-19 04:29 UTC, 2yujeong approved these changes
크게 고칠 부분은 없는 거 같아서 Approve 후 merge 하겠습니다!!
고생하셨습니다 알린 dㅇ_ㅇb

2022-07-19 04:29 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/application/FeedbackService.java
> +    private List<FeedbackResponse> getFeedbackResponses(final List<Feedback> feedbacks) {
추출된 메소드 순서 기준이 있을까요?

2022-07-19 04:29 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/application/LevellogService.java
> +        final Team team = getTeam(groupId);
도메인명이 Team으로 변경됐으니 변수명도 teamId로 변경하는 게 헷갈리지 않을 거 같아요!

2022-07-19 04:29 UTC, 2yujeong commented on backend/src/main/java/com/woowacourse/levellog/presentation/FeedbackController.java
> +                                                     @LoginMember final Long memberId) {
회원 전용 기능에 대해 토큰 인증을 위해서 쓰이지 않는 memberId를 받고 있네요
지금 고민할 부분은 아니지만 @MemberOnly 같이 멤버 전용 기능임을 알 수 있는 ArgumentResolver 추가를 고려해 보는 것도 좋을 거 같아요
나중에 다양한 역할들이 추가로 정의되고 나서 고민해 보는 것도 좋을 거 같아요

2022-07-19 04:29 UTC, 2yujeong commented on backend/src/test/java/com/woowacourse/levellog/presentation/MyInfoControllerTest.java
> +@WebMvcTest(MyInfoController.class)
상위 인터페이스인 ControllerTest에서 @WebMvcTest로 MyInfoController 포함 주입 받을 컨트롤러들을 이미 명시하고 있기 때문에 구현된 테스트에서 추가로 @WebMvcTest를 달아줄 필요는 없을 거 같아요!

2022-07-19 04:29 UTC, merged