feat: 팀 수정, 삭제 기능 구현
woowacourse-teams/2022-levellog pull request #98
Opened 2022-07-20 09:36 UTC by SuyeonChoi

## 구현 기능
- 팀 수정 API 구현
- 팀 삭제 API 구현
- 인수테스트 작성

## 논의하고 싶은 내용
### 동일한 URI인 경우, 인터셉터 적용 범위 설정하기
현재 `/api/teams` API의 경우, `findAll()`과 `findById()`는 인가가 필요하지 않고, 나머지 API에서는 필요로 합니다.
이런 경우를 위한 프록시 패턴을 도입하는게 어떨까요? 아래 공유 내용을 참고해주세요🙏

### cascade 옵션
현재 Team이 삭제될 때, 팀에 해당하는 Participant도 삭제되어야합니다. 
이런 경우를 위해 CASCADE 옵션을 걸어주는 것이 좋을까요? 
하지만 CASCADE 옵션은 보통 양방향 연관관계에서 사용되기 때문에 고민하고 있습니다.🤔

### TestFixture
릭이 AcceptanceTest에 추가로 작성해준 TestFixture를 사용하면, 한 멤버가 여러 팀에 속하는 경우 속한 팀에 따라 다른 멤버로 인식됩니다. 아직 릭의 코드가 merge 되기 전이라 일단은 TestFixture를 사용하지 않고 구현했는데, 이와 관련하여 논의하고 싶습니다.

## 공유하고 싶은 내용
- [프록시 패턴으로 인터셉터 Path와 Method 설정하기](https://jujeol-jujeol.github.io/2021/08/07/%ED%94%84%EB%A1%9D%EC%8B%9C-%ED%8C%A8%ED%84%B4%EC%9C%BC%EB%A1%9C-%EC%9D%B8%ED%84%B0%EC%85%89%ED%84%B0-Path%EC%99%80-Method-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/)

Close #56

2022-07-20 13:44 UTC, kbsat requested changes
복잡한데 잘 구현하느라 애쓰셨네요! 굿~  이제 앞으로 다듬어가면 될 것 같아요~! 아래 부분은 테스트 해보면서 발생한 문제들인데 한번 수정해주세요~! 😄

2022-07-20 13:44 UTC, kbsat commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
hostId가 포함되지 않은 participants 로 save를 하면 정상적으로 로직이 수행됩니다.
하지만 이럴 때 문제는 findAll을 했을 때 `MemberNotFoundException`을 발생하는데요
이는 save 메서드에서 participants에 host가 들어있지 않으면 예외를 발생시켜주었어야 하는데 이를 막아주지 못해서 생기는 일 같습니다. 해당 내용에 대한 save 메서드에 대한 방어 메서드가 필요할 것 같습니다~

2022-07-20 13:44 UTC, kbsat commented on backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
>                          it.getId(),
```suggestion
                        it.getMember().getId(),
```
가 되야 될 것 같습니다. 현재는 participant의 id가 넣어지는 것 같습니다.

2022-07-21 01:19 UTC, SuyeonChoi commented
## (07.21) 논의하고 싶은 내용 + 추가
Team 도메인에서 `profileUrl`을 가지고 있어야할까요? 
현재는 `profileUrl`이 호스트 이미지이기 해당 필드가 Team에 존재하지 않더라도 Member에서 가져올 수 있습니다.
혹시 추후에 다른 이미지를 업로드하는 확장성을 고려해서 이렇게 도메인 구조를 가져가는건가요?

2022-07-21 01:23 UTC, nailseong commented
> 혹시 추후에 다른 이미지를 업로드하는 확장성을 고려해서 이렇게 도메인 구조를 가져가는건가요?
확장성을 고려한 설계라고 생각해요. 굳이 뜯어 고칠 필요도 없어 보이네용

2022-07-21 01:25 UTC, kbsat commented
저도 팀의 프로필 사진이 추후 충분히 변경될 수 있다고 생각하기 때문에 현재 구조를 유지하는 것이 좋아보입니다 😁

2022-07-21 02:08 UTC, OzRagwort approved these changes

2022-07-21 02:08 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
> +        final Long hostId = getHostId(participants);
(안 중요하긴 함)

`getHostId(participants)`메서드르 사용하는 모든 곳에서 `final List<Participant> participants = participantRepository.findByTeam(team);`가 선행되는 것 같고 앞으로도 그럴 것 같아요. 참가자를 찾는 로직을 `getHostId()`메서드에 포함시키고 아래처럼 수정해도 좋을 것 같아요

```suggestion
        final Long hostId = getHostIdByTeam(team);
```

2022-07-21 02:09 UTC, OzRagwort commented on backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
> +        final Long hostId = getHostId(participants);
팀 CRUD 많이 빡셌을텐데 수고하셨어요 ! 👍 👍 👍

2022-07-21 02:38 UTC, nailseong approved these changes
어려운 기능 구현하느라 고생많았어용 귿귿~~👍

2022-07-21 07:13 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
> +        final Long hostId = getHostId(participants);
코드 리팩토링을 위한 좋은 의견 감사해요 알린!!
현재 `getTeam(final Team team)` 메서드를 보면, participants가 `getHostId()` 뿐만 아니라 참가자DTO로 만들어주는 `getParticipantsResponse()`메서드에서도 필요로 하여 인자로 받고 있습니다. 
그렇기 때문에 똑같은 데이터를 두 번 조회를 하지 않도록 `participantRepository.findByTeam(team);`를 분리하였습니다. 
이에 대한 알린 생각은 어떤가요??👀

2022-07-21 07:13 UTC, SuyeonChoi commented on backend/src/main/java/com/woowacourse/levellog/application/TeamService.java
>                          it.getId(),
API 명세서에서 `participants`의 `id`가 Participant도메인의 id가 아닌, member의 아이디였군요..!
다른 곳은 모두 도메인의 `id`를 사용해서 헷갈렸네요🥲 수정하고, 명세서에도 기록해 놓겠습니다〰️
```json
{
  "teams" : [
  {
	  "id" : 1,
	  "title": "제이슨조",
	  "place": "잠실 트랙룸",
	  "startAt": "2022-07-15",
	  "teamImage": "http://image.com",
	  "hostId": 1,
	  "participants": [{
		  "id" : 1,
		  "levellogId" : null,
		  "nickname" : "페퍼",
		  "profileUrl" : "https://avatars.githubusercontent.com/u/28749734?v=4"
	  }, {
		  "id" : 2,
		  "levellogId" : 6,
		  "nickname" : "OzRagwort",
		  "profileUrl" : "https://avatars.githubusercontent.com/u/32123302?v=4"
	  }, {
		  "id" : 3,
		  "levellogId" : 4,
		  "nickname" : "유정이",
		  "profileUrl" : "https://avatars.githubusercontent.com/u/76840965?v=4"
	  }]
  }
  ]
}
```

2022-07-21 07:13 UTC, SuyeonChoi commented on backend/src/test/java/com/woowacourse/levellog/application/TeamServiceTest.java
이에 대해 논의한 내용대로, 스프린트2에서는 방을 생성한 로그인한 유저(호스트)는 무조건 참가자에 포함되도록 수정하였습니다!
(즉, 현재는 호스트에게 관전 모드란 없다.)

클라이언트에서 `participants` 리스트에 호스트 아이디는 추가해서 보내주지 않고, Authorization Header의 토큰으로부터 호스트 정보를 받아 참가자에 포함되도록 구현하였습니다.

2022-07-21 07:26 UTC, kbsat approved these changes

2022-07-21 08:10 UTC, merged